### ISSUE TITLE
Script terminates with error on ArchLinux

### ISSUE THREAD

**Issue by strasharo** [sophron/wifiphisher#1]
Hello. I tried using the script on ArchLinux on a Raspberry PI and no matter what arguments I use it always terminates like this:

[root@pie wifiphisher]# python2 wifiphisher.py -c 9 
WARNING: No route found for IPv6 destination :: (no default route?)
[*] Starting HTTP server at port 8081
[*] Starting HTTPS server at port 444
[+] Networks discovered by wlan1: 22
[+] Starting monitor mode off wlan1
Monitor is: wlan1
Traceback (most recent call last):
  File "wifiphisher.py", line 747, in <module>
    print "For the AP is: " + ap_iface
TypeError: cannot concatenate 'str' and 'bool' objects
[root@pie wifiphisher]# 

Python version is as follows:

[root@pie ~]# python2 --version
Python 2.7.8
[root@pie ~]#

**Comment by jaseg** [comment]
I'm not entirely sure, but this might well be fixed by https://github.com/sophron/wifiphisher/pull/8

**Comment by strasharo** [comment]
I confirm that changing the shebang to python2 solved the issue for me.
Thanks a lot, jaseg!
