### ISSUE TITLE
It doesn't jam the victim all the time

### ISSUE THREAD

**Issue by casperass** [sophron/wifiphisher#100]
Jamming devices: 

DHCP Leases: 

HTTP requests: 

It repeats it continuously. Fake ap appears properly but it doesnt jam.
I checked whether router is ok or not with airodump. Channel etc. everything was normal and there were 4 clients. I doesn't happen all the time. And it's not about the victim. Sometimes it perfectly jams however sometimes it doesnt jam the same target at all

Wifi adapter: Alfa AWUS036NHA

Chipset: AR9271

Note:

I use the last version of wifiphisher

**Comment by sandman6578** [comment]
Try to make a airodump-ng --bssid "BSSID" -c "CHANNEL"  at same time you jamming
but before you have to do an airmon-ng and bring your jamming device to monitor mode but before you do this start the script and choose the access point to fake and then airmon-ng start "DEVICE" 
And then airodump.
Tell me if it works or not

**Comment by sandman6578** [comment]
And you can only take the atheros for the AP because the alfa dont support. AP-Moe

**Comment by sandman6578** [comment]
Mode*

**Comment by casperass** [comment]
Yeaah, I was already doing like that. I'm checking it at the same time. The insteresting thing is, although I do everything the same, sometimes it jams sometimes not. Funny... xD

**Comment by casperass** [comment]
![screenshot from 2015-03-24 00 58 52](https://cloud.githubusercontent.com/assets/11530785/6792466/598c7f8c-d1b0-11e4-8937-b1a8331bb958.png)

Now It never jams. I manually do the jamming with aireplay or mdk3, I connected to the fake ap with my android devices. It hasn't lost its connection. As you it doesn't jam. By the way, you were wrong about the alpha. I tried to use it as the AP(with -aI command) and it works.

**Comment by sandman6578** [comment]
Thought you have the awus036h

**Comment by casperass** [comment]
Any idea why wouldnt it jam?

**Comment by casperass** [comment]
It's not about card, I can do the jam manually with aireplay or mdk3.

**Comment by Auridice** [comment]
Dear Casperass, I read that you found the solution to this problem. I consider myself an noob, so please I ask your advice me as I do the right steps.
In my case I have two antennas, the first TL-WN722N (atheros chipset) and the second TL-WN7200ND (ralink chipset), both are brand TP Link and I have no problems with Kali because acknowledges.
Now, I followed some steps of other users, but can not get favorable results in this category. Tell me please all the steps as you do for good results. Thank you for your reply.

**Comment by casperass** [comment]
Hey Auridice,
Actually I didn't do much. Download the latest version of the script. Before the start phishing make sure that you are disconnected to the Internet. Stop the monitor mode if any cards of yours are in. 

Jamming problem could be related to your wifi cards. So try to jam with the other cards typing:

python wifiphisher.py -aI wlan1 -jI wlan0

aI= AP interface  jI= Jammer interface

If you just type "python wifiphisher.py" it probably using the internal wifi(wlan0) card as the AP. Because it chooses the stronger one to discover nearby routers and to jam. But it's meaningless that if far from the victim, it's sort of impossible to reach him with the weak internal wifi card. So, I'm using the weak one to discover and jam. If the internal antenna doesn't see the victim there is nothing to do but buying an anoter strong usb adapter. Because if it can't see the victim, how can the victim see our fake AP? That's why you should use the strongest adapter as the AP.

 With the command I typed above. You can adjust which one's gonna jam or which one's gonna be the AP. That may make a difference. It will...

However all of these are not important much. You can do the jam manually which works very fine for me. Aireplay or mdk3 are very useful. And if you want you can just use this script for jamming:

https://github.com/DanMcInerney/wifijammer

**Comment by Auridice** [comment]
I will follow your recommendation and then publish the results. Thanks friend for your reply.

**Comment by Auridice** [comment]
What's up friend. I followed your recommendation, but only get this. Write: python wifiphisher.py wlan0 Ai Hee wlan1
![screenshot from 2015-04-04 05_08_31](https://cloud.githubusercontent.com/assets/11789518/6993930/72c2ceba-dacb-11e4-8aff-fb2705a88ce5.png)
I'm using these two cards, if no other adapters, even if he could deauthenticate with 2. I think about buying an alpha, hope is enough. Help me if you notice that I'm doing wrong. 
![screenshot from 2015-04-04 05_09_44](https://cloud.githubusercontent.com/assets/11789518/6993965/56b83786-dacc-11e4-9dfd-0c0a885f5474.png)

**Comment by casperass** [comment]
It works fine. Look at the first ss. It jammed all devices which connected to victim AP. After that step the only thing you need to do is waiting. You know that your fake AP need to be closer to victims or stronger than victim's router right? I mean that if you're not close enough they won't automatically connect your fake AP. If it's impossible for your fake ap to have stronger signal than router itself. Jam them to the eternity. Use wifijammer.py which I gave you above. They won't be able to use their Internet so what are they gonna do? They probably will reboot their router. Gotchaaa. If you are even a little far from the victim, they will automatically connect your fake ap.

But first you need to localize you fake web pages. For instance If you live in Peru you need to translate html web pages into spanish to make it more realistic.

But you need to know that It's illegal. I'm only trying it on my router. I saw that on you ss you were jamming lots of device. Be careful you may go to jail. I wrote everything for only educational purposes ;)

**Comment by sophron** [comment]
Check the <a href="https://github.com/sophron/wifiphisher/wiki/Frequently-Asked-Questions-%28FAQ%29#q3">FAQ</a> for some reasons that may lead to your ineffective jamming.

If you think that your issue is not closed, please report it again after reading our <a href="https://github.com/sophron/wifiphisher/wiki/Bug-reporting-guidelines">guidelines</a>.

**Comment by jamalski** [comment]
Mr sophron: i am with kali linux a few years now, in the past the wifiphisher worked perfectly. But now i can not jam my ap anymore, i tried everything but i can't. Maybe Ziggo these days has good protected modems. With wifiphisher i can not jam, no matter what i do also with mdk3, aireplay-ng, wifijammer,
Maybe you have these days the solution for me, so please help, thank you
