### ISSUE TITLE
How can instal wifiphisher on wifislax ??

### ISSUE THREAD

**Issue by shadyhayek** [sophron/wifiphisher#101]

**Comment by coolzilj** [comment]
Just git clone the repo and run the python script.

**Comment by sophron** [comment]
Hi @shadyhayek,

From what I can see <a href="http://www.wifislax.com/liberada-version-final-de-wifislax-4-10-1-version-de-mantenimiento/">here</a>, wifislax includes wifiphisher by default so there's no real need to install it.
