### ISSUE TITLE
multiple routers.....not working..

### ISSUE THREAD

**Issue by nikhiljangam** [sophron/wifiphisher#102]
hello sir,this tool is working fine with single router...but in our college there are multiple routers connected to a single network...in tthis case it does nt working....any changes to be made to inject code to ???

**Comment by sophron** [comment]
Hello,

<b>Don't try to hack your college network if you don't have permission.</b>

In case you do have permission, there is no real difference when multiple access points are used for a network. There can be a variety of reasons the tool is not working against your college's network. Check the <a href="https://github.com/sophron/wifiphisher/wiki/Frequently-Asked-Questions-%28FAQ%29#q3">FAQ</a>.
