### ISSUE TITLE
Wont Start Connected To Internet

### ISSUE THREAD

**Issue by klgiger** [sophron/wifiphisher#103]
I cant get it to start Im not connected to internet. I tried it with eth0 up and down and wlan0 up and down both not connected.

here is the error.

[*] Starting HTTP server at port 8080
[*] Starting HTTPS server at port 443
[+] Networks discovered by wlan0: 20
[+] Starting monitor mode off wlan0
[+] Interface wlan0 is connected to the Internet. Please disconnect and rerun the script.
[!] Closing

**Comment by sandman6578** [comment]
Stop hacking if you dont understand this error

**Comment by frafrichile** [comment]
You need an Ethernet connection or a separate device to connect to the internet.

**Comment by casperass** [comment]
You can connect to the internet after you typed "python wifiphisher.py" It somehow works. I tried a few times use the internet and made the phishing same time. It works well. It says you need to disconnect from the internet because it may cause problems with monitor mode. However I've never had a problem with it. I don't know whether disconnecting the internet is necessary or not. I think that it just a precaution.

**Comment by BrooksTV** [comment]
A similar bug is like user klgiger.
Internet disconnected (cable unplugged! Wi fi is not connected!

**Comment by jasonwifi** [comment]
I have the same error as BrooksTV above. Anyone have an idea what's happening with this error?

**Comment by iamprabs** [comment]
i am also having same problem as BrooksTV abv

**Comment by HassenPy** [comment]
i agree with @sandman6578, this shouldn't be noob-friendly and not all issues should be answered as it may get people who misuse this into trouble.

**Comment by sophron** [comment]
@BrooksTV, @jasonwifi, @iamprabs Just pushed a fix. Please update to the latest revision and let me know if it solves the issue.

@klgiger Can you give me the output of the `ip route` command?

**Comment by BrooksTV** [comment]
Thanks Sophron. Its worked.

**Comment by iamprabs** [comment]
hello BrooksTV...
will u pls help me out...
how it is worked for u

**Comment by jasonwifi** [comment]
Works

@iamprabs 
Apt-get update
Delete Wifiphisher folders
Install again

**Comment by BrooksTV** [comment]
sophron What is the percentage of positive result? How much time does it take to hack around?

**Comment by sandman6578** [comment]
Takes as long as your Vic needs to connect to your AP and type in the password...
Theres is no fixed timeframe

**Comment by Silent25** [comment]
Have a question, may Wifiphisher works if i have the wlan default driver on my notebook and a extra wlan USB antena connected?  Thanks

**Comment by sandman6578** [comment]
With an external directional antenna you will increase the range alot but dont forget both of your 2 wlan cards need the same antenna for good results
