### ISSUE TITLE
Instructions 

### ISSUE THREAD

**Issue by AhmedDjebali** [sophron/wifiphisher#105]
*** Please *** Can anybody here in few steps explain me how this works

**Comment by casperass** [comment]
If you read "README.md" you will find all information you need. If you don't understand what to do after reading, you need to learn first linux basics. The only thing I can say is you need 2 wireless adapter and one of them must be okay for injection. After that, open terminal and go to the wifiphisher folder using "cd" Next, stop your internet connection and type "python wifiphisher.py" Last but not least you need to choose the victim. After typed number of it press enter and lean back. It will jam the victim and makes him connect to your fake AP.

However, You need more stronger connection to victim than router itself. You can achive it increasing tx power which is not very easy and probably illegal to do. Or you can try it in my way. You will wait till the victim reboot his router. Once he did that his router won't be connectable for 1 min. He will connect your fake AP in that time automatically.

Your name is Ahmed and im not sure you live in English speaking country or not. You need to customize html page for wherever you live. I live in Turkey and localized the html page into Turkish.

If you still don't understand how to do. You need to stop hacking then learn linux and wifi basics.

**Comment by sophron** [comment]
Hi @AhmedDjebali,

I believe the script is pretty straightforward to use. There are plenty of videos and tutorials on the web if you need more guidance.
