### ISSUE TITLE
Can you use two same adapters 

### ISSUE THREAD

**Issue by updown1** [sophron/wifiphisher#108]
Gents/Ladies,

I am curious if I you can use two alfa awus036NHA adapters for jamming and creating rogue access point.  Or do they have to be different? 

So far I tested this with alfa awus036NHA & alfa awus036N and it didn't work.

Thanks for taking the time to respond!

**Comment by casperass** [comment]
I am using a awus036nha, I don't have two but I used it both as the AP and jammer. I think there won't be any problem if you use them at the same time.

**Comment by frafrichile** [comment]
I am curious. I have an Alfa AWUS036H and the Alfa AWUS036NHA. 
Do these both work? or just one of them? or none

Thank you !

**Comment by updown1** [comment]
Frafrichile - In my experimentation I was not able to get AWUS036H to work. 
Casperass - Thanks for the info! I am going to order another NHA - retest and report back!

**Comment by sandman6578** [comment]
@casperass
This is a big problem Two Cards are must.
Its because you can't send signals and receive them at the same time.
Not possible.
Maybe you have so many problems because of this

**Comment by sandman6578** [comment]
@updown1
You can you the alfa awus036h only for jamming not for the rouge accesspoint

**Comment by updown1** [comment]
Thanks Sandman6578!
 
I tried both and was not successful. So far I never managed to get anything to show anything on DHCP Leases: & HTTP requests: 

Good time to be playing with this... we had 3 days of constant rain! I also ordered another card from amazon just to be on the safe side. I can always send it back if i don't need it.

**Comment by updown1** [comment]
Sandman6578, 

Here are some pics.


![screen shot 2015-04-08 at 2 35 18 pm](https://cloud.githubusercontent.com/assets/11812038/7056523/7e3087ea-de1a-11e4-9d02-dcbd9b655b14.png)

![screen shot 2015-04-08 at 2 35 58 pm](https://cloud.githubusercontent.com/assets/11812038/7056530/85f222cc-de1a-11e4-99ee-0612f30ba847.png)

![screen shot 2015-04-08 at 2 37 46 pm](https://cloud.githubusercontent.com/assets/11812038/7056533/8db7fea0-de1a-11e4-91de-1481b8e72613.png)

**Comment by sandman6578** [comment]
It is working correct 👍

**Comment by updown1** [comment]
It looks like it is working correctly but at no point in time was I able to get any type of "upgrade" message or DHCP Leases or HTTP Request.  I tried everything over 3 days period.

Cheers,

**Comment by sophron** [comment]
@updown1, please have a look at the <a href="https://github.com/sophron/wifiphisher/wiki/Frequently-Asked-Questions-(FAQ)#q3">FAQ "I have no success using the tool / Nobody is connecting to the rogue AP. What am I doing wrong?"</a>.
