### ISSUE TITLE
Error code 404

### ISSUE THREAD

**Issue by kawaiixyrene** [sophron/wifiphisher#109]
help me please.. how can i get rid of this error:

Error response

Error code 404.

Message: File not found.

Error code explanation: 404 = Nothing matches the given URI.

( i already tried the solution from sandman6578 but the error still exist.. i appreciate any help thanks.. sorry for my english.. )

**Comment by kawaiixyrene** [comment]
i tried to change the ( access-point-pages folder ) to another directory and change the
 ##basic configuration##
PHISING_PAGE="access-point-pages/minimal"

e.g.

PHISHING_PAGE="var/www/access-point-pages/minimal"
PHISING_PAGE="var/www/wifiphisher/access-point-pages/minimal"
PHISING_PAGE="root/wifiphisher/access-point-pages/minimal"
PHISING_PAGE="root/access-point-pages/minimal"

and so on..

the server are up and running at http/proxy 8080 and https 443 and dns 53

then when i try to open the web browser in victims view i recieve

Error code 404.

Message: File not found.

Error code explanation: 404 = Nothing matches the given URI.

(」ﾟﾛﾟ)｣(」ﾟﾛﾟ)｣(◎_◎;)
----------------------------------------------------------------------------------------
---what is the correct directory for "access-point-pages/minimal"?
---is something wrong with the script " wifiphisher.py " ?
---do i missed something?
---do i need to install another program?
-----------------------------------------------------------------------------------------
++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----------------------------------------------------------------------------------------
+++server is running fine
+++deauth the victim is successful
----reaching the server phishing page failed "error code 404"



お願いします。

**Comment by phuongs3v3r** [comment]
hello kawaiixyrene

i should you follow me .

if you can change folder PHISHING_PAGE="var/www/access-point-pages/minimal" ... you copy all everything in folder wifiphisher (dowload from github) -> past var/www/

same as above
if you can change folder PHISING_PAGE="var/www/wifiphisher/access-point-pages/minimal" ... you copy all everything in folder wifiphisher (dowload from github) -> past var/www/wifiphisher/

I DON`T KNOW you want to change html default or different ... you can capture console and upload it here .

**Comment by sandman6578** [comment]
Try to give all directories in /www folder and child directories read and write rights.

**Comment by sophron** [comment]
I pushed a commit that should fix this. Please update to the latest revision and let me know if it does.

**Comment by sophron** [comment]
This should now be solved. If not, please open a new issue.
