### ISSUE TITLE
Connect With eth0 and and alfa awus036h

### ISSUE THREAD

**Issue by naflan121** [sophron/wifiphisher#110]
I heard that we need 2 wifi devices in order to perform this task.. 
My question is 
1. Can't we go on with only one device(Alfa awus036h)
2. Does it possible when the vmware is connected with a etho connection and Alfa awus036h , to use as device for injection 

Hope someone can answer this question

**Comment by casperass** [comment]
No, certainly you need two wireless cards. Because it uses one for jamming the other one for AP. You can't do any of them with ethernet.

**Comment by casperass** [comment]
Also, you cant use Awus036h as the AP. You need a wireless adapter which is compatible to create AP. I recommend awus036nha

**Comment by Zaratros** [comment]
I don't know how, but my RTL8187 is working in ap mode. I'm using it successfuly with another evil twin  tool.

**Comment by naflan121** [comment]
@zaratros correct that version works on ap mode as well can i know the other adapter used to jam

**Comment by Zaratros** [comment]
Sorry for the misunderstanding, but I'm not using wifiphisher. I'm using a script that does the jamming and the phishing using one adapter.

**Comment by naflan121** [comment]
i am happy to know that method

**Comment by Zaratros** [comment]
It's called linset. I'm using an edited version with the possibility to change the phishing page ...

**Comment by naflan121** [comment]
do u uae kali or any othere? in case does itr equire 2 adapters?

**Comment by sophron** [comment]
1) There's already #63 about this.
2) No. You will need to connect your virtual adapter directly to your VM.
