### ISSUE TITLE
[Improvement] Why not to have an option like to get your own login page?

### ISSUE THREAD

**Issue by nicefellow1234** [sophron/wifiphisher#111]
Hi,

It's quite a good approach..I appreciate it...
As I am a Web Developer/Designer I can help you to add this feature to have your own login page  and can also create a short tutorial how to have your own page.Just let me know if you people are good to go with it..

Regards,
Umair Shah

**Comment by sophron** [comment]
I'm not sure i understand what you mean. You may create your own login page and use it by modifying the `PHISING_PAGE` constant.

**Comment by sophron** [comment]
I'm closing this, feel free to re-open.
