### ISSUE TITLE
i appriciate your working but i have a problem that wifi phisher page only work for wwww.google.com. i want that phisher page work for every web page.tell me solution that what change should be made so that phisher page can open at every web page.i think this problem can be solve by modifing wifiphisher.py but what line i should modify????????

### ISSUE THREAD

**Issue by MusaMirza** [sophron/wifiphisher#114]

**Comment by MusaMirza** [comment]
i appriciate your working but i have a problem that wifi phisher page only work for wwww.google.com. i want that phisher page work for every web page . to i appriciate your working but i have a problem that wifi phisher page only work for wwww.google.com. i want that phisher page work for every web page.tell me solution that what change should be made so that phisher page can open at every web page.i think this problem can be solve by modifing wifiphisher.py but what line i should modify????????

**Comment by sophron** [comment]
I pushed a commit that fixes this. Please upgrade to the latest revision and try again.

**Comment by sophron** [comment]
This should now be solved. If not, please open a new issue.

**Comment by sophron** [comment]
This should now be solved. If not, please open a new issue.
