### ISSUE TITLE
Fake AP

### ISSUE THREAD

**Issue by mhuggins41** [sophron/wifiphisher#117]
Ok I have been using this without problems until today.   I start up the program and it starts jamming but when I check I don't see any fake ap.  I increased the wlan0 and wlan1 adapter power to 30 but still nothing.   Help please

**Comment by naflan121** [comment]
same here to me

**Comment by blackHatMonkey** [comment]
The issue should be solved now. If you still experience any issues after upgrading to the latest version feel free to open a new issue.
