### ISSUE TITLE
HTTPS won't respond.

### ISSUE THREAD

**Issue by Globalgoon** [sophron/wifiphisher#119]
Very nice piece of software!

Everything works fine except I can't get HTTPS websites to display the fake firmware upgrade page.Its working perfect with HTTP websites but with HTTPS I get an error or it times out.

**Comment by casperass** [comment]
Did you try it on another device? I mean I'm using my android phone as the victim. I am just googling random stuff after I connect the fake ap. It works well. (google uses https automatically of course)

**Comment by Globalgoon** [comment]
Yes casperass I tried it on my Iphone with the same result ...HTTP works and HTTPS won't.

**Comment by sandman6578** [comment]
for me https also dont work

**Comment by Globalgoon** [comment]
It would me incredible if wifiphisher incorporated something like SSL strip to deal with https,Still a very impressive tool.

**Comment by sophron** [comment]
Hi @Globalgoon,

What error are you getting? Please check our <a href="https://github.com/sophron/wifiphisher/wiki/Bug-reporting-guidelines>bug reporting guidelines</a> and report this in more detail.

**Comment by nhatxinh** [comment]
i meet same issue, i run wifiphisher on Kali newest, apt-get install update all
Everything works awesome, only https doest not respond. I tried with android, IOS and result the same. It would be nice if you can fix it. Thank you very much for your hardwork Sophron

**Comment by zenetio** [comment]
I am running wifiphisher on RPi 2 and trying to de-authenticate my android cell phone but no success. The cell phone continue to run normally.

**Comment by sophron** [comment]
@zenetio This has nothing to do with this issue. Please open a new one.

**Comment by mpwill** [comment]
Hum.. same issue here. I was running wireshark on the target machine and here's what I've found:

- The target machine sends a broadcast query
- The attacker machine (10.0.0.1) replies with a valid IP
- The target machine starts sending multiple DNS requests (the browser is open)
- The attacker machine never replies to the requests or sends any additional info. It just hangs in there
- Closing the browser and opening again does not make any improvements.

On the console, I can see the connected host, but the HTTP requests never populates.

Not sure if it's no handling the request properly or if it's not able to figure out the IP where the request originated from. Tried to go trough the code but I'm a newbie in python.

Thank you for this great tool and for all your hardwork making it better for all of us.

**Comment by blackHatMonkey** [comment]
Are you using the latest version?

**Comment by sophron** [comment]
I pushed some changes to the HTTP/HTTPS handling. Please update to the latest revision and let me know how it works for you.

**Comment by mpwill** [comment]
@blackHatMonkey   @sophron sophoron. Sorry for not replying sooner. swapped the wireless cards position and was able to run the app.. weird since swapping them back did not break the functionality. Got a different issue related with the https certificate but did not went into a deep investigation yet to find out what is wrong. I will try the update later on today and let you know how it goes. Thanks!

**Comment by sophron** [comment]
@mpwill Please open a new issue for this. Thanks. :)
