### ISSUE TITLE
Python 2.7 Error (Linux Mint 17)...

### ISSUE THREAD

**Issue by FurqanHanif** [sophron/wifiphisher#12]
i 'm Getting This Error (See The Image Please)... 
[img]http://i.imgur.com/hao5Tob.png[/img]

**Comment by strasharo** [comment]
This one should be fixed by https://github.com/sophron/wifiphisher/pull/8, however it's not merged yet.

**Comment by ParvJain** [comment]
try #16

**Comment by sophron** [comment]
This should be fixed now. If not, please reopen.
