### ISSUE TITLE
Won't create Fake AP

### ISSUE THREAD

**Issue by Kingbalou** [sophron/wifiphisher#120]
Hi , 
not sure if it's my Wifi usb adapter but here the problem: 

- I can jam any devices only if i put the ``` -m 6 ``` option 
- I'm on Kali linux 
- I'm using iwlwifi driver for my intern wifi card
- This [driver] (https://github.com/Kingbalou/mt7601) for the No-name wifi adapter  where USB ID is ```148f:760```

and i can't create a Fake Ap but if i use airbase-ng i can on the No-name wifi.

Any idea ? 

Thx

**Comment by Kingbalou** [comment]
Edit : i've tried with TP-LINK TL-WN725N and it can't create the FakeAp

**Comment by sophron** [comment]
Hello,

This is probably because `hostapd` fails to initialize the driver network card using `nl80211` interface. Please upgrade to the latest revision and see if you are getting this error. The way to proceed is to specify a different wireless interface using the `-aI` option.

**Comment by blackHatMonkey** [comment]
The issue should be solved now. If you still experience any issues after upgrading to the latest version feel free to open a new issue.
