### ISSUE TITLE
Fake AP not connecting

### ISSUE THREAD

**Issue by nazar2sfive** [sophron/wifiphisher#121]
i tried the following taking my samsung galaxy s5 hotspot ..
but it doesnot work with others private wifi as well...
jamming success!
fake AP will be created without any encryption key
won't connect fake AP [by the way is there any way to enable the victim to autoconnect my fake AP?]
DHCP leaches [ thus not done...] blank
HTTP requests: [ i don;t will that ever work for me?]

is this to do with my adapter  ... ? plz recommend me one if that is so... which is the best and powerful?

airmon-ng
![screenshot from 2015-06-11 11_29_10](https://cloud.githubusercontent.com/assets/12841320/8101515/99105406-1037-11e5-9eac-318737a77a7c.png)

airodump-ng and my target here... other target are similar...
![screenshot from 2015-06-11 11_31_38](https://cloud.githubusercontent.com/assets/12841320/8101514/990ead68-1037-11e5-9a21-efd08cc88e00.png)

well this works
![screenshot from 2015-06-11 11_36_01](https://cloud.githubusercontent.com/assets/12841320/8101516/9911a8ba-1037-11e5-8a5f-3d486928d944.png)

and next stuck here forever....
![screenshot from 2015-06-11 11_42_42](https://cloud.githubusercontent.com/assets/12841320/8101517/9911e60e-1037-11e5-9de7-5daf4b126d8f.png)

this is how i had previously connected to the ap
![screenshot from 2015-06-11 11 26 45](https://cloud.githubusercontent.com/assets/12841320/8101531/aff4627a-1037-11e5-9a26-a8279350359f.png)

well the jamming got success here
![screenshot from 2015-06-11 11 43 34](https://cloud.githubusercontent.com/assets/12841320/8101530/aff26128-1037-11e5-9d98-16e0acc5834f.png)

now cannot connect the fake AP...
![screenshot from 2015-06-11 11 46 21](https://cloud.githubusercontent.com/assets/12841320/8101532/aff63262-1037-11e5-8bac-880bec9799d0.png)

**Comment by mehranexpert** [comment]
i think it used Your Alfa Card for AP and Your other card for Jamming , as i know but i dont  know why wifiphisher not support ALFA AWUS036H Cards . you must reverse it and for Jamming Use Alfa and AP in your Another Card maybe work .

**Comment by sandman6578** [comment]
Yes use this commands.
aI-wlano jI-wlan1

**Comment by sophron** [comment]
Hello,

This is probably because hostapd fails to initialize the driver network card using nl80211 interface. Please upgrade to the latest revision and see if you are getting this error. The way to proceed is to specify a different wireless interface using the -aI option.

**Comment by blackHatMonkey** [comment]
The issue should be solved now. If you still experience any issues after upgrading to the latest version feel free to open a new issue.

**Comment by moneydream07** [comment]
I tried wifiphisher on my own router and checked my other devices which were connected to the router but there was no fake AP was created hence no fake web page.

**Comment by moneydream07** [comment]
Someone tell me how to solve this problem
