### ISSUE TITLE
Question about List of Requirements

### ISSUE THREAD

**Issue by VicCebedo** [sophron/wifiphisher#122]
Hi,

I understand that this project requires Kali Linux to work.
However, I would like to know which specific packages I need.
What if I am running on a different Linux distro (like Arch)?

This is a very nice project.
Thank you very much.

**Comment by sophron** [comment]
Hi @VicCebedo,

Wifiphisher is developed to work primarily on Kali Linux. People have made it work to other distros without much hassle though.

Some of the dependencies you will probably need are scapy, dnsmasq & hostapd.

**Comment by VicCebedo** [comment]
You have been very informative.
Thank you @sophron.
