### ISSUE TITLE
Error in line 20 

### ISSUE THREAD

**Issue by cyfugr** [sophron/wifiphisher#123]
sudo python ./wifiphisher.py 
Traceback (most recent call last):
  File "./wifiphisher.py", line 20, in <module>
    from scapy.all import *
ImportError: No module named scapy.all

 I am running  Linux Mint.. any idea ??

**Comment by sophron** [comment]
Hi @cyfugr,

`sudo apt-get install python-scapy` should work for you.

**Comment by davyh87** [comment]
Ive got the same error
even when i have python scapy installed

root@dav:~/Desktop/wifiphisher/bin# python wifiphisher
/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "wifiphisher", line 11, in <module>
    
  File "/root/Desktop/wifiphisher/wifiphisher/pywifiphisher.py", line 21, in <module>
    import interfaces
  File "/root/Desktop/wifiphisher/wifiphisher/interfaces.py", line 6, in <module>
    import pyric
ImportError: No module named pyric

**Comment by sophron** [comment]
@davyh87 You need to `python setup.py install` first.

**Comment by Davy0** [comment]
Lol srry forgot to install pyric ^^
Thanks for reply..
