### ISSUE TITLE
Wifiphisher pn kali linux

### ISSUE THREAD

**Issue by StrawHat13** [sophron/wifiphisher#125]
Hello when I choose which network I get this error:

Traceback (most recent call last):
  File "wifiphisher.py", line 1001, in <module>
    dhcp(dhcpconf, ap_iface) 
  File "wifiphisher.py", line 532, in dhcp
    dhcp = Popen(['dnsmasq', '-C', dhcpconf], stdout=PIPE, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

PLEASE HELP

**Comment by DoomTaper** [comment]
by chossing network if you mean choosing Access Point , then i would say you should update your cloned repo as well as your kali as I am not getting this error after selecting Access Point

**Comment by StrawHat13** [comment]
Okay man thank you I'll try it.

**Comment by StrawHat13** [comment]
Hello I updated everything but I'm still getting the same error :S any other ideas?

**Comment by sophron** [comment]
`dnsmasq` is not installed in your system.

On a Debian-based system `apt-get install dnsmasq` should do the trick.

**Comment by StrawHat13** [comment]
thank you man it works great :D :D

**Comment by StrawHat13** [comment]
hey again when I choose the access point and it starts it displays:
Jamming Devices:
MAC address - the channel - SSID 

Is it working or should I choose another AP?

**Comment by StrawHat13** [comment]
Hello I installed dnsmasq and no errors but another issue appeared that when I choose the AP it displays
Jamming devices:
MAC address - channel - SSID

Any ideas of what should I do?


-----Original Message-----

**Comment by sophron** [comment]
You should understand how the tool works. Read the README file or if you don't find that enough there are plenty of guides and HOWTOs on the web.
