### ISSUE TITLE
DHCP not work Alfaawus036H

### ISSUE THREAD

**Issue by mehranexpert** [sophron/wifiphisher#126]
Hi , i have Two Alfaawus036H , but it seems DHCP not work for it cause when i connected to fake ap , i cant get ipaddress from DHCP and Rouge AP not work ,

**Comment by sandman6578** [comment]
Your Card Does NOT work with wifiphisher and so on you NEED also 2 card i suggest atheros chipsets works like charm

 

Von: mehranexpert [mailto:notifications@github.com] 
Gesendet: Freitag, 31. Juli 2015 14:36
An: sophron/wifiphisher
Betreff: [wifiphisher] DHCP not work Alfaawus036H (#126)

 

Hi , i have Two Alfaawus036H , but it seems DHCP not work for it cause when i connected to fake ap , i cant get ipaddress from DHCP and Rouge AP not work ,

**Comment by mehranexpert** [comment]
why Alfa AWUS036H ( Best Card for injection ) not work with wifiphiser ? why dont fix this issue ? many people use AWUS036H Card .

**Comment by sandman6578** [comment]
Come on guys. Is google that complicated?? I don’t think so.

Alfa AWUS036H does NOT support Access point mode.

There is no possible solution to fix this….

 

Von: mehranexpert [mailto:notifications@github.com] 
Gesendet: Sonntag, 2. August 2015 13:13
An: sophron/wifiphisher
Cc: Sandro
Betreff: Re: [wifiphisher] DHCP not work Alfaawus036H (#126)

 

why Alfa AWUS036H ( Best Card for injection ) not work with wifiphiser ? why dont fix this issue ? many people use AWUS036H Card .

**Comment by mehranexpert** [comment]
Who said AWUS036H Not work in AP Mode ? airbase-ng -e <ESSID> -c <CH#> -P wlan0mon 

also it work Evil Twin Attack .

**Comment by sandman6578** [comment]
its only the truth.
if dont know what are writing here pls dont do it.
RTL8187 does NOT support AP-mode.
what did you think why you cant connect to your alfa?.
You can create an Accesspoint but you can`t connect to it.

**Comment by sandman6578** [comment]
You can use it for jamming the ass of the others and e.g. an Atheros (works smothly on my pc) for the Rouge-AP.

**Comment by mehranexpert** [comment]
if you dont know about Alfa AWUS036H then Shut your mouth and do learning . 

just play with Evil Twin attack it Work well with 1 Wireless card for Jamming and AP , also i connect to it as AP Success , When you dont Know about something don't Speak . 
Thanks .

**Comment by frafrichile** [comment]
I have following this hub for a while. Could you explain how to get Alfa AWUS036H  to work? I have one as well and would like to know.

**Comment by sandman6578** [comment]
Dont make empty words if you find a way to make the card work.

Then explain how you did it.?.

Don’t be smartass…

Von: frafrichile [mailto:notifications@github.com] 
Gesendet: Sonntag, 2. August 2015 20:47
An: sophron/wifiphisher
Cc: Sandro
Betreff: Re: [wifiphisher] DHCP not work Alfaawus036H (#126)

 

I have following this hub for a while. Could you explain how to get Alfa AWUS036H to work? I have one as well and would like to know.

**Comment by sandman6578** [comment]
and so on if i see your Activity on Hub why did you critizise me?
Your activity and helpness is not really high soo please kiddy stop with these kind of words.
We live in Peace here.
We are all up fo the same here.

**Comment by Zaratros** [comment]
I also read that RTL8187 doesn't support ap mode, but it's working with mine. I'm using another evil twin tool, but it does the work.

**Comment by mehranexpert** [comment]
yes it work on evil twin on RTL8187 . then it Shoud be work on Wifiphisher , sophron should fix it .

**Comment by heska77240** [comment]
hello, can you say me if this TPLINK 722N is compatible with AP MODE and if someone has already try it on AP MODE with wifiphisher ?

thank you

**Comment by frafrichile** [comment]
what are the best cards for this one

**Comment by phedz** [comment]
My alfa works fine as an AP, dunno what google you use to find your info sandman.

**Comment by phedz** [comment]
plus it uses the ralink chip not rtl

**Comment by Zaratros** [comment]
If your alfa awus036h got  a ralink chipset it's a fake one

**Comment by phedz** [comment]
oh, I was thinking of my NH not my H, my bad.

**Comment by phuongs3v3r** [comment]
i used tplink 722 and i config succeessfull. 

NOTE : Should [ service network-manager stop ]

then 
sudo python wifiphisher.py  -aI  wlan0 -jI wlan1 (I= i upper @@ )
*-jI  Choose the interface for jamming. By default script will find the most powerful interface and starts monitor mode on it.
*-al Choose the interface for the fake AP.  By default script will find the second most powerful interface and starts monitor mode on it

**Comment by blackHatMonkey** [comment]
The issue should be solved now. If you still experience any issues after upgrading to the latest version feel free to open a new issue.
