### ISSUE TITLE
The logic for a significant improvement!!!

### ISSUE THREAD

**Issue by erkexzcx** [sophron/wifiphisher#130]
When you start this program, you must run wifite on the same channel, so wifiphisher immediatelly changes the channel to the AP's one and immediatelly finds the jamming devices. The code related to channel set must be improved.

**Comment by sophron** [comment]
Hi, I don't understand the improvement you are proposing. I am also not aware of the "wifite" tool. Please try to explain this again.

If you are reporting a bug, you may want to follow our <a href="https://github.com/sophron/wifiphisher/wiki/Bug-reporting-guidelines">guidelines</a>.

**Comment by erkexzcx** [comment]
just, if the WiFi is at channel, for example, 7, the wifiphisher wouldn't find the clients as fast as after I type "iwconfig <jamming_interface> channel 7". Seems like this can be easily done by putting a simple command "iwconfig <mon_interface> channel <channel>" to this script after the AP is chosen by the user.

**Comment by erkexzcx** [comment]
it is fixed and can be closed
