### ISSUE TITLE
I can't connect to the fake AP with my iPhone neither my Mac

### ISSUE THREAD

**Issue by thisisALPINE** [sophron/wifiphisher#132]
I'm testing this beautiful software on my home Wlan. so I start wifi-phisher from the terminal and everything goes right, it creates the rogue AP and so. But when I try to connect to it, my Iphone doesn't join the network, neither my Mac. It stays all the time attempting to connect, but it never do. How can I fix it? Should I modify some line or what? Thank you all!

**Comment by sophron** [comment]
Hi @thisisALPINE,

Please follow our <a href="https://github.com/sophron/wifiphisher/wiki/Bug-reporting-guidelines">bug reporting guidelines</a> and report this bug again.

**Comment by Ezat** [comment]
What did you use for the fake AP ?(the type of the wifi adapter )
Because you can't make the alfa as (Access Point)

**Comment by thisisALPINE** [comment]
for the fake AP I use a TP-LINK WN722N, it's capable of injection and all, but it still doesnt't work. The other Adaptator is a D-LINK DWL-G122

**Comment by thisisALPINE** [comment]
I could report this again Mr sophron, but there's nothing more I can say. Because the fake AP just doesn't let me connect

**Comment by Ezat** [comment]
send me photo like this
![screenshot from 2015-08-13 20 21 53](https://cloud.githubusercontent.com/assets/12213390/9256648/42727996-41e0-11e5-969a-853ad42b907f.png)

**Comment by thisisALPINE** [comment]
![screenshot from 2015-08-13 21 36 03](https://cloud.githubusercontent.com/assets/12964909/9256957/20327ac6-41f3-11e5-9cee-1ef7f28d32b6.png)

**Comment by thisisALPINE** [comment]
that's the begin, and the it stays "forever" like the next photo

**Comment by thisisALPINE** [comment]
![screenshot from 2015-08-13 21 35 22](https://cloud.githubusercontent.com/assets/12964909/9256976/45a20218-41f3-11e5-9092-a5a8e2ddd542.png)

**Comment by Ezat** [comment]
Okay ,now try this cmd:
python wifiphisher.py -aI wlan2 -jI wlan1
![screenshot from 2015-08-13 20 55 52](https://cloud.githubusercontent.com/assets/12213390/9257405/e4e5279c-41e4-11e5-87d9-fc6154d59174.png)

go to your iphone and try to connect to the fake wifi
if it didn't work , try this insted:
python wifiphisher.py -aI wlan1 -jI wlan2
![screenshot from 2015-08-13 21 01 52](https://cloud.githubusercontent.com/assets/12213390/9257510/72019714-41e5-11e5-9cb7-2da302f60c7a.png)

**Comment by thisisALPINE** [comment]
This is one of the best days of my life. It works. Thank you much, much, much

**Comment by Ezat** [comment]
Glad to hear that !!
Hope you good hunting.

**Comment by thisisALPINE** [comment]
A last thing.. I'm testing it with a Android too, but when I connect to the fake AP, it doesn't load the fake page. It says "error 404, nothing matches the given URI". What is it?

**Comment by Ezat** [comment]
well, it's not your problem ,
Its from the tool, i have this too, but some website like facebook worked just fine.
Hope sophron fix it soon.

**Comment by thisisALPINE** [comment]
Thank you about that. How can I use this tool for sniffing the traffic on the fake AP? Like how can I perform a Evil Twin attack not only for the WPA password, but also for sniffing traffic like it was their AP. For example, to sniff a Facebook password, and all the traffic who pass on my fake AP, who has Internet, instead of the fakeAP used for the only WPA password.

**Comment by Ezat** [comment]
You can't ,this tool designed for jamming and password receiving from one specific page ,and even if the victim connected to us ,we need to analyze the traffic to get the password and the user name after he login to something ,because he will not type it again ,the browser already saved it ,so the browser will send encrypted information (which it has the password that we want) to the router ,and then the router will send it to the internet requesting confirmation to login.
Our job is to use a tool that can analyze the traffic (for example: Ettercap or Wireshark ) and get the password.
So after you make the victim connected to you by using evil twin ,now you can easily analyze his traffic.
See this tutorial: http://null-byte.wonderhowto.com/how-to/spy-web-traffic-for-any-computers-your-network-intro-arp-poisoning-0131785/

**Comment by thisisALPINE** [comment]
Okay, now i unederstand (: Thank you for all man

**Comment by sophron** [comment]
This has been reported a lot of times. It's probably an issue with `hostapd` and we're planning to push a patch soon.

**Comment by linooosan** [comment]
i also have this problem my devices wont connect to my fake ap, im using kali linux 2 2017 with fluxion, but it doesnt seem like i have wifiphisher, how do i get it?

**Comment by blackHatMonkey** [comment]
@linooosan If you have installed it you can simply run `wifiphisher` or run the `bin/wifiphisher` in the `wifiphisher` directory.
