### ISSUE TITLE
[-] Unable to start HTTP server! [-] Another process is running on port 8080. [!] Closing

### ISSUE THREAD

**Issue by jalelweb** [sophron/wifiphisher#133]
Hi, I have this problem too, in Kali And ubuntu 15, I changed the port in “wifiphisher.py” File from 8080 to other ports and it always says that Port (8282, 8585, 50000 …) is used by another process

**Comment by mohamed554** [comment]
[+] Choose the [num] of the AP you wish to copy: 1
[*] Starting the fake access point...
SIOCADDRT: Network is unreachable
[3;J







[*] ORANGE set up on channel 3 via wlan0 on False

[-] Unable to start HTTP server (socket errno 99)!
[-] Maybe another process is running on port 8080?
[!] Closing

**Comment by sophron** [comment]
There is already an issue opened about this.
