### ISSUE TITLE
Command '['ifconfig', 'False']' returned non-zero

### ISSUE THREAD

**Issue by pawnsmaster** [sophron/wifiphisher#135]
I'm using the new kali (sana) python version (2.7) connecting to the internet through ethernet and using my internal wifi adapter to create the FakeAP when i try to run the script without any options it works well until i choose the target AP then it gives me the following 

    [*] Starting the fake access point...
    False: error fetching interface information: Device not found
    Traceback (most recent call last):
    File "wifiphisher.py", line 952, in <module>
    if not dhcp(dhcpconf, ap_iface):
    File "wifiphisher.py", line 519, in dhcp
    proc = check_output(['ifconfig', str(mon_iface)])
    File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['ifconfig', 'False']' returned non-zero exit status 1

then i tried to use 

    sudo python wifiphisher.py -jI wlan0

but it gave me the same error
Finally this one worked well for me

    sudo python wifiphisher.py -aI wlan0

I used this on my own router also i had to take few steps away from the router so my iphone could connect to the new AP over the router because i didn't raise the txpower .
**Another notice** : surfing the web while being connected to the FakeAP safari prompted a new window asking if i want to continue anyway cause it's not sure about this site certificate, any idea to avoid this ??
Thank you for your great script

**Comment by sophron** [comment]
Hi @pawnsmaster,

Thanks for reporting this. I'll fix it during the next days.

There is no way to avoid safari's (or any other browser's) SSL certificate error. The certificate can't be anything else other than self-signed.

**Comment by ss32** [comment]
I'm running into the same issue.  Is there any workaround?

**Comment by hadezb** [comment]
Thanks @pawnsmaster :)

**Comment by vishal43** [comment]
I m using backtrack 5r3 iam getting following errors 
Traceback(most rcent call last ):
File"wifiphisher.py" !, in (module)
From subprocess import pipen.pipe .check.output
import error:canot import name check output

**Comment by vishal43** [comment]
Python wifiphiser.py

**Comment by blackHatMonkey** [comment]
@vishal43 
Please open a new issue and describe your problem in that thread. :smile:

**Comment by blackHatMonkey** [comment]
The issue should be solved now. If you still experience any issues after upgrading to the latest version feel free to open a new issue.
