### ISSUE TITLE
Changing the phishing scenario?

### ISSUE THREAD

**Issue by thisisALPINE** [sophron/wifiphisher#136]
How can I change the phishing scenario (the fake login page)? Better, I saw there are three scenarios, how can I set one of them?

**Comment by pawnsmaster** [comment]
Open wifiphisher.py by any txt editor search for 

    PHISING_PAGE =
You can choose from 3 phishing scenarios or create your own one .

    PHISING_PAGE = "phishing-scenarios/minimal"
    PHISING_PAGE = "phishing-scenarios/connection_reset"
    PHISING_PAGE = "phishing-scenarios/office365"

Choose one and save the file .. done .

**Comment by sophron** [comment]
What @pawnsmaster says is correct. I'm also planning to add an argument on this in the near future.
