### ISSUE TITLE
DHCP LEASE ! 

### ISSUE THREAD

**Issue by Motasembt** [sophron/wifiphisher#138]
hello there i have a problem please read my post untill the end
 i have awus036neh and i wanted to use wifi phisher so i read that it need 2 cards and support injection 
so i buy today TL-WN7200ND and i connect both cards and started 
the problem is i dont get the lease when i try to connect o the fake ap 
so i search all the posts in here reporting the same problem 
i found two guys first one @sandman6578 said ( Come on guys. Is google that complicated?? I don’t think so. Alfa AWUS036H does NOT support Access point mode. There is no possible solution to fix this…. ) 
and the other guy @mehranexpert said ( Who said AWUS036H Not work in AP Mode ? airbase-ng -e -c -P wlan0mon
also it work on Evil Twin Attack ) 
ok so use the command lsusb and here is the output 

Bus 005 Device 004: ID 148f:3070 Ralink Technology, Corp. RT2870/RT3070 Wireless Adapter
Bus 005 Device 008: ID 148f:3070 Ralink Technology, Corp. RT2870/RT3070 Wireless Adapter

i didnt know that they are the same chipset or maybe im wong ? the same driver i dont know 

so based on the issues and what @sophron said if you are using this chipset u will not get dhcp release ! because it not support AP mode . 

and in another post i saw a comment from @Ezat telling him to change the ap for injection here
https://github.com/sophron/wifiphisher/issues/132#issuecomment-130782196
then i have try this command but the same problem my android device not connecting 
-----
why i posted this post then ? ok i posted it because something else happen !!!  look 

Jamming devices: 
[*] 90:18:7c:3f:59:20 - 10:fe:ed:a7:1f:6f - 1  - MooT
[*] f0:27:65:fc:b4:f6 - 10:fe:ed:a7:1f:6f - 1  - MooT
[*] 10:fe:ed:a7:1f:6f - 1  - MooT

DHCP Leases: 
1439974203 f0:27:65:fc:b4:f6 10.42.0.45 android-782358e9b6b0e2bd 01:f0:27:65:fc:b4:f6

HTTP requests: 
----
even so it says DHCP Leases and i got a notification in my mobile says ( network need to sign in ) but i didnt catch that because i got disconnected from the fake ap !
that only happen 1 time 
---
airmon-ng 
Interface	Chipset		Driver
wlan0		Ralink RT2870/3070	rt2800usb - [phy1]
wlan4		Ralink RT2870/3070	rt2800usb - [phy3]
---
the command i used and the dhcp worked for some seconds is 
/root/Downloads/wifiphisher-master/wifiphisher.py'  -aI wlan4 -jI wlan0
----
just to note something 
wlan0 is alfa awus036neh
wlan4 tp link 7200nd
---------
so whats the problem ? and if both cards not supported why i got dhcp lease ? 
---
at the end when i press CTRL + c i got this error first time i see 
^CException in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/Downloads/wifiphisher-master/wifiphisher.py", line 609, in channel_hop2
    deauth(monchannel)
  File "/root/Downloads/wifiphisher-master/wifiphisher.py", line 665, in deauth
    send(p, inter=float(args.timeinterval), count=int(args.packets))
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 251, in send
    __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose, realtime=realtime)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 335, in __init__
    set_promisc(self.ins, i)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 138, in set_promisc
    mreq = struct.pack("IHH8s", get_if_index(iff), PACKET_MR_PROMISC, 0, "")
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 275, in get_if_index
    return int(struct.unpack("I",get_if(iff, SIOCGIFINDEX)[16:20])[0])
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 269, in get_if
    ifreq = ioctl(s, cmd, struct.pack("16s16x",iff))
IOError: [Errno 19] No such device

[!] Closing
Exception in thread Thread-5 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 505, in run
  File "/root/Downloads/wifiphisher-master/wifiphisher.py", line 833, in sniff_dot11
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 577, in sniff
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 485, in recv
<type 'exceptions.TypeError'>: an integer is required
---
help me @sophron

**Comment by sophron** [comment]
Hi @Motasembt,

I never said anything about chipsets that are not working. I bet there are issues with some cards but until I find the root of these issues I can't tell with certainty which are working and which are not. 

I'll look closer to your issue the next days. You can help me by reporting this again using our <a href="https://github.com/sophron/wifiphisher/wiki/Bug-reporting-guidelines">guidelines</a>.

**Comment by Motasembt** [comment]
ok i will be waiting a replay 
thanks in advance

**Comment by sophron** [comment]
Hello,

This is probably because hostapd fails to initialize the driver network card using nl80211 interface. Please upgrade to the latest revision and see if you are getting this error. The way to proceed is to specify a different wireless interface using the -aI option.

**Comment by blackHatMonkey** [comment]
The issue should be solved now. If you still experience any issues after upgrading to the latest version feel free to open a new issue.
