### ISSUE TITLE
no Fake AP no DHCP leases,  no jamming devices and no HTTP requests

### ISSUE THREAD

**Issue by pharsi** [sophron/wifiphisher#139]
I have two ALFA AWUS036NH wifi adapters, monitor mode is activated on one of the wifi adapters but I can't detect SSID from another device (my mobile phone) i-e it is not being detected, tried moving out of range and back in as well.
You can ask for more info, although I'm providing you what I think is necessary.
$lsmod | grep 8187
rtl8187                63559  0 
eeprom_93cx6           12625  1 rtl8187
mac80211              511777  5 ath9k,rtl8187,rt2x00lib,rt2x00usb,rt2800lib
cfg80211              425751  6 ath,ath9k_common,ath9k,mac80211,rtl8187,rt2x00lib
usbcore               199549  10 ath3k,btusb,uvcvideo,rtl8187,rt2x00usb,rt2800usb,ehci_hcd,ehci_pci,xhci_hcd,xhci_pc

Any help will be highly appreciated :)
Thanks for this awesome piece of work ;)

**Comment by sophron** [comment]
This has been reported a lot of times. It's probably an issue with `hostapd` and we're planning to push a patch soon.
