### ISSUE TITLE
Comprehensive unit testing

### ISSUE THREAD

**Issue by sophron** [sophron/wifiphisher#141]
We should write tests for all the individual parts and make sure they behave as expected. A test suite will help us find any problems early and it will simplify the integration of new modules.

The tests will also provide a sort of living documentation of the system, making it easier for new developers to understand the functionality of the project.

This is an easy task. Anyone with basic Python knowledge can write tests for various parts of wifiphisher.

**Comment by HassenPy** [comment]
Are you working on this? i would like to work on this one, if you have any preferences to libraries that should be used for unit tests and docs mention them.

**Comment by sophron** [comment]
Hi @HassenPy,

No I have not started working on this yet. The first thing we need to do is to split the project into several modules. After that we can start testing each one of them separately.

I believe the `unittest` module will be sufficient for this.

**Comment by sophron** [comment]
Our tests are currently failing.

@blackHatMonkey, can you work on this?

**Comment by blackHatMonkey** [comment]
Yes, I will take a look and fix them soon.

**Comment by sophron** [comment]
I'm closing this. We can open separate and more specific issues for each module missing unit testing if needed.
