### ISSUE TITLE
Cannot strat wifiphisher

### ISSUE THREAD

**Issue by darkr4y** [sophron/wifiphisher#142]
Error info:
>>> python wifiphisher.py                    
[+] Networks discovered by wlan0: 0
[+] Networks discovered by wlan1: 13
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "wifiphisher.py", line 933, in <module>
    sniffing(virtual_iface, targeting_cb)
  File "wifiphisher.py", line 429, in sniffing
    sniff(iface=interface, prn=cb, store=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 485, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
socket.error: [Errno 100] Network is down
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wifiphisher.py", line 407, in channel_hop
    stdout=DN, stderr=PIPE
TypeError: 'NoneType' object is not callable

Device info:
>>> lsusb
Bus 002 Device 003: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n
Bus 002 Device 002: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n

Kali 2.0 in VM Fusion 7.1.2 (2779224)
>>>uname -a
Linux Darkali 4.0.0-kali1-686-pae #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) i686 GNU/Linux

whats wrong ?

**Comment by darkr4y** [comment]
I test on my another pc
It can not work too

➜  wifiphisher git:(master) ✗ python wifiphisher.py
               _  __ _       _     _     _
              (_)/ _(_)     | |   (_)   | |
     __      ___| |_ _ _ __ | |__  _ ___| |__   ___ _ __
     \ \ /\ / / |  _| | '_ \| '_ \| / __| '_ \ / _ \ '__|
      \ V  V /| | | | | |_) | | | | \__ \ | | |  __/ |
       \_/\_/ |_|_| |_| .__/|_| |_|_|___/_| |_|\___|_|
                      | |
                      |_|

[+] Networks discovered by wlan0: 11
[+] Networks discovered by wlan1: 17
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "wifiphisher.py", line 933, in <module>
    sniffing(virtual_iface, targeting_cb)
  File "wifiphisher.py", line 429, in sniffing
    sniff(iface=interface, prn=cb, store=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 485, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
socket.error: [Errno 100] Network is down
➜  wifiphisher git:(master) ✗ lsusb
Bus 007 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 003: ID 0bda:8187 Realtek Semiconductor Corp. RTL8187 Wireless Adapter
Bus 001 Device 002: ID 0bda:8187 Realtek Semiconductor Corp. RTL8187 Wireless Adapter
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
➜  wifiphisher git:(master) ✗ uname -a
Linux WifiCrack 4.0.0-kali1-686-pae #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) i686 GNU/Linux
➜  wifiphisher git:(master) ✗

**Comment by darkr4y** [comment]
before run wifiphisher
just do this:
airmon-ng check kill

**Comment by Evanito** [comment]
Thanks, this solution helped me with my user's problem.
