### ISSUE TITLE
error while running on kali 2.0

### ISSUE THREAD

**Issue by Darkcast** [sophron/wifiphisher#144]
Hi, I get the following error when trying to run the software on kali linux 2.0
I have a TP-Link TL-WN722N and my laptops internal wifi card

Networks discovered by wlan0: 20
[+] Networks discovered by wlan1: 15
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "./wifiphisher.py", line 933, in <module>
    sniffing(virtual_iface, targeting_cb)
  File "./wifiphisher.py", line 429, in sniffing
    sniff(iface=interface, prn=cb, store=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 485, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
socket.error: [Errno 100] Network is down

**Comment by sophron** [comment]
Hi, I'm aware of the issue. I'll try to fix it the next days. Until then, you can use our <a href="https://github.com/sophron/wifiphisher/releases/tag/v1.1">stable release</a>.

**Comment by AdamMukhriz** [comment]
I have this problem too

**Comment by erkexzcx** [comment]
in my case, run this command first:
airmon-ng check kill

Then use as you used regually

**Comment by blackHatMonkey** [comment]
This bug should be fixed now. If you are still experiencing any issues after upgrading to the latest version, feel free to open a new issue.
