### ISSUE TITLE
Bugs On Single Interface Version 

### ISSUE THREAD

**Issue by mohamed554** [sophron/wifiphisher#145]
what I've done : 

1. I rebooted the device to avoid any errors
2. I entered command `sudo service network-manager stop` 
3. `sudo python wifiphisher.py `
4. script output :one: time : 
    - it doesn't Jam the victims or AP But it appears that it's jamming  "i tried Google and it work perfect" ![jam](http://s10.postimg.org/fktlp4oll/image.png) i.e : the jamming script doesn't work...i suggest running mdk3 for jamming
    - when i **manually** connect android device to fake AP : 
     ![1](http://s23.postimg.org/hqsaz1zyj/image.png)

    - I'm not really sure what is this : 
     ![2](http://s23.postimg.org/iewk499aj/image.png)
   - it closes like charm but it leftover the **jam0** on monitor mode 
 5. when i open the script for :two:  time without rebooting  "i.e: jam0 is on monitor mode" :
   * error when close the script : 
![3](http://s23.postimg.org/50o2lys0b/image.png)
* the script still **not Jamming** The AP or The Victims "i tried Google and it work perfect" but it appears that it's jamming  "like :one: time "

  * it take too long to connect to AP and it doesn't  load the Pushing page from fake AP : 
   ![here](http://s16.postimg.org/6p7ckbkut/20150829_004026.jpg)
  hope you fix it :smile:

**Comment by frafrichile** [comment]
How do I use the single interface version??
Thanks!

**Comment by mohamed554** [comment]
you don't have to if you have two interfaces just download v1.1 "two interfaces"
or if you want to try it download latest version and run the script

**Comment by sophron** [comment]
Hi, I reverted back to the two interfaces version. I'll focus on fixing some bugs before proceeding with this. Thanks for reporting.
