### ISSUE TITLE
Kali 2.0 bug w/ potentinal fix found

### ISSUE THREAD

**Issue by Codgedodger** [sophron/wifiphisher#150]
Having a bug in wifiphisher with Kali 2.0. Apt-Update && Upgrade has been ran to make sure I'm up to date on everything. 

Setup:

Dell Inspiron N5110 (Intel i5)

Wlan0 - Intel Centrino Wireless-N 1030 
Wlan1 - 'NoName' Realtek RTL8187L (Usb 2.0)

Running Wifiphisher will work perfectly in the DeAuths, but would fail to create DHCP with evil twin AP. 

After hours of trying to get it to work, I had some success and would like to see if I could get my solution added for others struggling with my issue. 

Problem was solved by running in this order:
service network-manager stop
airmon-ng check kill
python wifiphisher.py -aI wlan0 -jI wlan1

Wondering if it would be beneficial to adding these commands, if others are having this issue.

**Comment by blackHatMonkey** [comment]
The issue should be solved now. If you still experience any issues after upgrading to the latest version feel free to open a new issue.
