### ISSUE TITLE
Works like a charm…but the signal is to weak. Good for nearby only. Not really far.

### ISSUE THREAD

**Issue by norasyraf** [sophron/wifiphisher#151]
Ok guys. I just install wifiphisher few days ago. Its work like a charm. Im no expert to comment on this, but everything works.

Im running tplink wn722n (ar9271) on hp probook4440s ( qualcom atheros ar9485).

1) airmon-ng start wlan1mon
2)airmon-ng check kill
3) then i run wifiphisher.py

I even sees the duplicate ap. Everything works. But what i notice is, once i try to access the twin ap, its load toooooo long. If i sit very close to my laptop, its fast. ( i try to access from android).  But if its somebody at 1 house away, im not sure what is happening to the loading.

What are the solution? How to increase the signal? How bout using router? Can i switch wlan0 with stronger adapter?

**Comment by sami3d** [comment]
cant they create a kind of mobile app or something to use like a hotspot?? LOL ... just wondering .... :P silly thoughts ...

**Comment by chic01taliano** [comment]
Not silly at all sami3d. For instance look at Reaver Pro.

**Comment by sophron** [comment]
@norasyraf The attack depends on the strength of your wireless cards. Have a look <a href="https://github.com/sophron/wifiphisher/wiki/Frequently-Asked-Questions-(FAQ)#what-are-some-effective-wireless-adapters-for-using-wifiphisher-">here</a> for some effective cards you may consider using.

**Comment by dferrer92557** [comment]
Hello,

Just take a quick look at my favourite stuff, you're gonna love it! More here  <http://stewikachu.feeonlyadvisorboston.net/lnqnvkgk>

Warm regards, dferrer92557@yahoo.com

**Comment by dferrer92557** [comment]
Hi, You're not gonna believe what I've read yesterday, you've got to read it yourself at <http://cujavofu.npsoccer.com/lnyozv>

dferrer92557@yahoo.com
