### ISSUE TITLE
Fake AP was created successfully. Same name and channel, but it was an Open AP.(no key required to join)

### ISSUE THREAD

**Issue by fujs** [sophron/wifiphisher#152]
Hi,

as mentioned in the title, the fake ap was created successfully. but it doesn't require any key to join.
i tried it on myself. i had to reconnect to the fake ap(newly created rogue ap) manually, and it gave a warning saying that this network was previously wpa2 secured.

I'm using both TL-WN722N for this. Is this normal or a bug?

thank you. :)

**Comment by erkexzcx** [comment]
On what device you've noticed the message "previously was WPA2"?

**Comment by fujs** [comment]
i was testing it on the supposedly "victim" laptop(MAC OS). so what i did was manually connect to the rogue ap. and then it says "this network was previously WPA2 secured. it is an open network now. continue to join?"

**Comment by lost-echo** [comment]
I can confirm this. My Android Smartphone recognizes two different AP's with the same SSID, one WPA/WPA2 secured (the original one), the other one as open network. As soon as a attack is launched, it triggers a notification that a new open WiFi-Network is available; the user has to manually connect to the fake AP.

**Comment by lost-echo** [comment]
Update to my previous comment:

After looking over the source, I realized that the script doesn't even attempt to imitate the authentication behavior of the original AP. It only copies MAC, channel and ESSID.

After modifying the variable 'config' in the function 'start_ap' so that the generated hostapd configuration also contains the lines

'auth_algs=1'
'wpa=2'
'wpa_keymgmt=WPA-PSK'
'wpa_pairwise=TKIP CCMP'
'wpa_passphrase=<actual AP password>'
'rsn_pairwise=CCMP'

it works. Though, the value for 'wpa_passphrase' must be the correct password of the target AP (one doesn't always have this password). I've found no way to force hostapd to accept any password; if anyone has an idea, please let me know!

**Comment by fujs** [comment]
thanks for the reply @lost-echo! will try it once i get home.

**Comment by sophron** [comment]
Hi @fujs,

Yes, this is how the script works. The Evil Twin will be an open network. Depending on the victim's network manager, victim may or not automatically connect to the AP or not.

@lost-echo There is no way to accept any password. A feature that will allow the creation of a password-protected AP, in cases where the attacker does know the pre-shared key is on the plans.

**Comment by brunoaduarte** [comment]
@sophron, isn't possible to capture/sniff the wpa authentication attempt if i'm faking the host ap ?
maybe we could create a fake AP with same SSID and protected with any random WPA password (not open like usual), and when the victim tries to login in our fake AP, we would capture the passphrase he tried to enter (that is the correct one for this AP).

**Comment by sophron** [comment]
@brunoaduarte This is possible. You don't have to spawn a second Access Point. Just by kicking out the victim from its network you can listen for  handshakes when it tries to connect back to its legit network.

This conversation is off-topic though. I'm closing this thread. Feel free to open a new one if you want to discuss it more.

**Comment by dferrer92557** [comment]
Hello,

There is some helpful stuff I just found on the web, you may like it too, please read here <http://sajuchufe.hagglenation.com/lnzzxg>

Good wishes, dferrer92557@yahoo.com

**Comment by dferrer92557** [comment]
Hi,
Have you seen this stuff? I think it's great, lust take a look here <http://shenkupyza.halwebb.biz/lnhoox>

Rushing, dferrer92557@yahoo.com

**Comment by dferrer92557** [comment]
Hello,
Isn't it the information you were looking for? Read about it here <http://frawyslely.mrwinchell.com/lniayoy>

In haste, dferrer92557@yahoo.com

**Comment by dferrer92557** [comment]
Hi,

Here is some information on the new stuff that may seem helpful to you, read more here <http://cespijindi.qkerala.com/lnbkol>

Best Wishes, dferrer92557@yahoo.com
