### ISSUE TITLE
Networks discoverd is 0

### ISSUE THREAD

**Issue by soumia7** [sophron/wifiphisher#153]
after using this command : root@kali:~/Bureau/WifiPhisher/wifiphisher-master# sudo python wifiphisher.py
I got this :
[+] Networks discovered by wlan0: 0
[+] Networks discovered by wlan1: 0
[+] Starting monitor mode off wlan1
[*] Cleared leases, started DHCP, set up iptables
why there is no networks ?

**Comment by soumia7** [comment]
any solution please ??!!

**Comment by sophron** [comment]
@soumia7 The first check only happens to determine the strongest of your wireless cards. The real discovery of nearby networks happens afterwards.
