### ISSUE TITLE
Help me please, I got this error at starting.

### ISSUE THREAD

**Issue by hadezb** [sophron/wifiphisher#155]
Hello, I recently try to start this script in Kali Linux 2.0 but when I select my target I got this:

False: error fetching interface information: Device not found
Traceback (most recent call last):
  File "wifiphisher.py", line 952, in <module>
    if not dhcp(dhcpconf, ap_iface):
  File "wifiphisher.py", line 519, in dhcp
    proc = check_output(['ifconfig', str(mon_iface)])
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['ifconfig', 'False']' returned non-zero exit status 1

Please, someone who can help me

Regards

**Comment by ISeeWorld** [comment]
in my opinion ,your DHCP service is not ok.you can checkout it .

**Comment by sophron** [comment]
Duplicate (#135).
