### ISSUE TITLE
wifiphisher stable on kali 2.0 not working properly. 

### ISSUE THREAD

**Issue by ortholinux** [sophron/wifiphisher#157]
Hello im currently using kali sana installed on HDD and was testing wifiphisher but the one i installed from gitub was not working and showing alot of errors, so i searched a bit and found a stable version named as wifiphisher-1.1, and although its not showing any errors but its just showing this:

[3;J
Jamming devices: 

DHCP Leases: 

HTTP requests: 

[3;J
Jamming devices: 

DHCP Leases: 

HTTP requests: 

[3;J
Jamming devices: 

DHCP Leases: 

HTTP requests: 

and just keep showing this, i've also tried this on kali 1.1.0 live but there too showing same problem.
Help please.

**Comment by sophron** [comment]
This is no bug. That's what you are suppose to see.

I believe you have not understand the idea of Evil Twin. Have a look at the <a href="https://github.com/sophron/wifiphisher/wiki/Frequently-Asked-Questions-(FAQ)#i-have-no-success-using-the-tool--nobody-is-connecting-to-the-rogue-ap-what-am-i-doing-wrong-">FAQ</a> for the success factors of the tool.
