### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by richi69** [sophron/wifiphisher#158]
Hi,
I have this error after the network selection:

Starting HTTP server at port 8080
Traceback (most recent call last):
  File "/root/Téléchargements/wifiphisher-master/wifiphisher.py", line 981, in <module>
    httpd = SecureHTTPServer((NETWORK_GW_IP, SSL_PORT), Handler)
  File "/root/Téléchargements/wifiphisher-master/wifiphisher.py", line 151, in __init__
    certfile=PEM
  File "/usr/lib/python2.7/ssl.py", line 509, in __init__
    self._context.load_cert_chain(certfile, keyfile)
IOError: [Errno 2] No such file or directory

Can you help me?
Thanks

**Comment by mariohmol** [comment]
same thing here.. any ideas?

**Comment by sophron** [comment]
Can you supply more information please? Check our <a href="https://github.com/sophron/wifiphisher/wiki/Bug-reporting-guidelines">Bug Reporting Guidelines</a> on how to do so.

**Comment by blackHatMonkey** [comment]
The issue should be solved now. If you still experience any issues after upgrading to the latest version feel free to open a new issue.
