### ISSUE TITLE
wifiphisher error!

### ISSUE THREAD

**Issue by phamdinhnam3** [sophron/wifiphisher#159]
![wifiphisher](https://cloud.githubusercontent.com/assets/3419911/10474640/47d00e2c-7263-11e5-9246-e5162c2f8bfe.png)

Sorry i'm not good english, so i can't explain to you.
Please fix it. thanks

**Comment by HassenPy** [comment]
duplicate for #135

**Comment by lashze** [comment]
i am unable to clone                             
 git clone https://github/sophron/wifiphisher

**Comment by HassenPy** [comment]
try ``https://github.com/sophron/wifiphisher.git``

**Comment by sophron** [comment]
Duplicate (#135).
