### ISSUE TITLE
 Device not found

### ISSUE THREAD

**Issue by ISeeWorld** [sophron/wifiphisher#161]
I meet this problem:
==============================================
[+] Choose the [num] of the AP you wish to copy: 12
[*] Starting the fake access point...
False: error fetching interface information: Device not found
Traceback (most recent call last):
  File "wifiphisher.py", line 952, in <module>
    if not dhcp(dhcpconf, ap_iface):
  File "wifiphisher.py", line 519, in dhcp
    proc = check_output(['ifconfig', str(mon_iface)])
  File "/usr/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['ifconfig', 'False']' returned non-zero exit status 1
===================================================================
i don't know why ,how could i solve this problem ,thank you very much.

**Comment by sophron** [comment]
Duplicate (#135).
