### ISSUE TITLE
No FAKE AP appearing on the victim's wifi list

### ISSUE THREAD

**Issue by ZorWin** [sophron/wifiphisher#164]
I'm using Kali linux.
These are my Network controllers: Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter (rev 01).
  wifiphisher is working perfectly up until the part where it starts the fake access point. The injection part is working just fine as it seems to deauthenticate my android phone's(victim) wi-fi connection. The victim auto disconnects but unfortunately when I check the wifi list, the fake AP isn't appearing as I suppose it should. So what happens is it get stucked on the DHCP Leases with a blank and just continuously de-authenticating the victim's connection. Any solution will be much appreciated.

also when I quit I get this error:

![screenshot from 2015-10-21 02 08 58](https://cloud.githubusercontent.com/assets/15225567/10629260/4ff89dde-779b-11e5-9ef7-8fca7a4d080c.png)

#120 <--almost exactly the same with this issue

**Comment by sophron** [comment]
Please check the answer on #120 and if needed report back there.
