### ISSUE TITLE
Wifi phisher won't work

### ISSUE THREAD

**Issue by Kajpio** [sophron/wifiphisher#166]
Hi guys !
I really want to use this program and try to see how it's work *_*. So I'
m going to the directory of wifi pisher and I do "root@kali:~/Downloads/wifiphisher-1.1# python wifiphisher.py " and the outpu is "[*] Starting HTTP server at port 8080
[*] Starting HTTPS server at port 443
[+] Networks discovered by wlan0: 0
[+] Starting monitor mode off wlan0
SIOCSIFFLAGS: Operation not possible due to RF-kill
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "wifiphisher.py", line 994, in <module>
    sniffing(mon_iface, targeting_cb)
  File "wifiphisher.py", line 428, in sniffing
    sniff(iface=interface, prn=cb, store=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 577, in niff
    p = s.recv(MTU)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 485, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
socket.error: [Errno 100] Network is down"
So guys if you could help me that will be awesome !
Thanks
Kajpio

**Comment by sandman6578** [comment]
Try
ifconfig wlan0 up before start
which card you use?
Which chipset?

**Comment by Kajpio** [comment]
My wlan0 is already up :)
I use the card who is built in the XPS L321X (the model : Intel®Centrino®Advanced
N6230 ). The chipset : i don't know checked on the site, maybe you have a command, then i can give you an output :)

**Comment by Kajpio** [comment]
Shit sorry guys, I read that we need two interface.
