### ISSUE TITLE
Typo in phishingpage and interfaces modules

### ISSUE THREAD

**Issue by HassenPy** [sophron/wifiphisher#168]
There's these 2 lines that exist only for reference, would be better to comment them:
[line 376](https://github.com/sophron/wifiphisher/blob/master/wifiphisher.py#L376)
[line 367](https://github.com/sophron/wifiphisher/blob/master/wifiphisher.py#L367)

after taking another look, the whole else block starting line [line 369](https://github.com/sophron/wifiphisher/blob/master/wifiphisher.py#L369) is doing nothing.

just doing some cleanup before splitting the project into modules, i ll open an issue with details on how i ll do this.

**Comment by HassenPy** [comment]
oh, i think it's trying to pull the gateway for the wlan0 iface, but still incomplete, should i finish this or there is a better way to do it.

**Comment by blackHatMonkey** [comment]
@HassenPy ```Wifiphisher``` has gone through some major updates. Can you provide the line numbers on the new version?

**Comment by HassenPy** [comment]
@blackHatMonkey ok i ll see what notes i had when i worked on this.

**Comment by blackHatMonkey** [comment]
thanks :smile:

**Comment by HassenPy** [comment]
actually, the whole ``get_internet_interface()`` from old [wifiphiser.py line356](https://github.com/HassenPy/wifiphisher/blob/master/wifiphisher.py#L356) has been replaced by the new ``get_interfaces()`` at [interfaces.py line 524](https://github.com/sophron/wifiphisher/blob/cb534b081d8e9382cea6eb98e1960ae3e3505524/wifiphisher/interfaces.py#L524), so there's no need for them anymore.
gj btw

**Comment by blackHatMonkey** [comment]
Thank you.:smile:

**Comment by HassenPy** [comment]
i noticed a typo while reading some code, in ``phishingpage.py`` and ``interfaces.py``, replace ``fallowed`` by ``followed``.

**Comment by blackHatMonkey** [comment]
Thanks for taking the time to find these. I'll fix them soon. :+1:
