### ISSUE TITLE
wifiphisher doesn't check if dnsmasq is present on the system before using it, throws an error instead

### ISSUE THREAD

**Issue by strasharo** [sophron/wifiphisher#169]
I'm running wifiphisher on Archlinux and I'm receiving the following error after I choose a target network:
[*] Starting the fake access point...
Traceback (most recent call last):
  File "./wifiphisher.py", line 952, in <module>
    if not dhcp(dhcpconf, ap_iface):
  File "./wifiphisher.py", line 509, in dhcp
    dhcp = Popen(['dnsmasq', '-C', dhcpconf], stdout=PIPE, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[root@black wifiphisher]# which dnsmasq
which: no dnsmasq in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
[root@black wifiphisher]# 

I guess wifiphisher should check if dnsmasq is installed on the system as it does with hostapd currently.

**Comment by sophron** [comment]
`dnsmasq` is different than `hostapd` as it is included on Kali Linux and this script aims to primarily support this specific distro.

Eventually, if we want to support more distros we will put a `setup` script.
