### ISSUE TITLE
Fake AP's BSSID isn't the same as the original's

### ISSUE THREAD

**Issue by AhmedRoma** [sophron/wifiphisher#170]
the Fake AP's BSSID isn't the same as the original's. if the script could be edited to include that it would be great as devices will connect automatically to our fake AP

**Comment by sophron** [comment]
Hi @AhmedRoma,

We don't spoof our BSSID as we want to be able to distinguish our Access Point with the legit one when we do the jamming. 

Broadcasting the same BSSID will not necessarily make the devices connect automatically to the rogue Access Point. This is something that has to do with the implementation of the each network manager.

**Comment by AhmedRoma** [comment]
@sophron Hi, 

could you post another script that spoofs for special use or point me to the part of the code that 
could be edited to do that ( my python isn't that strong). i want to experiment with the tool.

thanks for help and great work btw

**Comment by AhmedRoma** [comment]
am just curious is it line ~480 . if i were to copy the same bssid how would it be done 
is it 
        'macaddr_acl=copy_ap(2)\n'
??

**Comment by sophron** [comment]
The BSSID is retrieved on <a href="https://github.com/sophron/wifiphisher/blob/master/wifiphisher.py#L951">line 951</a>. You will need to re-factor the start_ap method and pass the BSSID there.

Again, if you do this, the script won't behave properly as you will kick your own victims from your rogue Access Point.

**Comment by elprashant** [comment]
thank @sophron  for your reply, now i get it what's the problem in cloning BSSID
