### ISSUE TITLE
I can help Design - Web Dev/Designer - Scenarios

### ISSUE THREAD

**Issue by CodesForCookies** [sophron/wifiphisher#171]
Hi guys, I thought it would be really cool to maybe help out an open source project, but, since I'm not a python developer I wanted to see if I could make some themes. I have one idea for a template but I could design a site for any phishing scenario really, whatever works best, just like me know I'd love to help in any way... my idea was to have a website portray a site like xfinity or Comcast because they offer hotspots in public places all across the nation, like on the road, or around gas-stations or hotels. On top of that once you select the xfinity cable tab in your settings it opens up a site in your web browser that makes you select which ISP you use, which could potentially lead to a greater audience to be phished. I think I could develop this theme in one day, if not sooner. Just let me know! You can contact me at LeytonH.designs@gmail.com and I'll most likely respond within the hour if I'm not too busy. Thanks!

**Comment by CodesForCookies** [comment]
Also: I'm not sure if I should have posted this here but I couldn't find any other place so far, thanks and sorry!

**Comment by sophron** [comment]
Hi @CodesForCookies,

You are very welcome to design pages for wifiphisher! 

The `xfinity` and `comcast` templates would fit perfectly in our phishing scenarios. You can find more details on the idea <a href="https://github.com/sophron/wifiphisher/issues/4">here</a>. I also recommend you to check how we have implemented our current scenarios under the `phishing-scenarios` directory. Feel free to ask me any questions you may have.

**Comment by CodesForCookies** [comment]
Hi Sophron, I looked through the link you provided and it helped with some of my questions and I can definitely work with the requirements. The one question I had was that I'm pretty new to Git/Github so should I just email the files over when they're completed? Thanks for all the help and patience! I'll start working on the templates tomorrow, they'll be ready soon. Thanks -CodesForCookies

**Comment by CodesForCookies** [comment]
Oops, I hope I replied right, I also accidentally close this for a second. Such a github newb :(

**Comment by sophron** [comment]
@CodesForCookies, Sure, whatever works best for you.

**Comment by sophron** [comment]
Hi @CodesForCookies,

I'm closing this issue. If you are still around, you can of'course contact me via email or submit your patches via Pull Requests.

Cheers!
