### ISSUE TITLE
help finding 2 wireless network

### ISSUE THREAD

**Issue by noobjo** [sophron/wifiphisher#172]
can i use Alfa AWUS036NHA and Alfa AWUS036H and how to turn off my laptop wireless network

**Comment by frafrichile** [comment]
I have those two as well but I believe one of them does not support injection. if someone can let me know which one should I purchase. That would be great.

**Comment by blackHatMonkey** [comment]
@frafrichile @noobjo 

Two cards that I have confirmed working are ```AWUS036H``` and ```AWUS036NHA```.

**Comment by frafrichile** [comment]
@blackHatMonkey  I have those same exact two. Maybe I need to specify which one to use. Do you do that? if so which one do you specify to use.

Thanks!

**Comment by blackHatMonkey** [comment]
Please see #180 the workaround post.

**Comment by sophron** [comment]
There are some problems with some versions of Alfa at the moment. We believe it's something that has to do with `hostapd`. I'm closing this issue, since it has been reported multiple times.
