### ISSUE TITLE
False: error fetching interface information: Device not found

### ISSUE THREAD

**Issue by sidjad** [sophron/wifiphisher#173]
False: error fetching interface information: Device not found
Traceback (most recent call last):
  File "wifiphisher.py", line 952, in <module>
    if not dhcp(dhcpconf, ap_iface):
  File "wifiphisher.py", line 519, in dhcp
    proc = check_output(['ifconfig', str(mon_iface)])
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['ifconfig', 'False']' returned non-zero exit status 1

**Comment by Fryzel** [comment]
do you have two wireless adapters connected ?

**Comment by sidjad** [comment]
no , I have only one usb adapter

**Comment by blackHatMonkey** [comment]
Please read the [requirements](https://github.com/sophron/wifiphisher#requirements). You need two wireless adapters, one of which must be able to inject packets.

**Comment by sophron** [comment]
Duplicate (#135).
