### ISSUE TITLE
Request to modify template wording

### ISSUE THREAD

**Issue by mojojojojo** [sophron/wifiphisher#176]
There is a few things I would like to request to change with the template. Perhaps give us the option to change the words. I feel "web administration" is really fake looking. It also says "EU" at the top right. Instead of web administration, why not have the python script replace it with the router name. If they have netgear, the script puts netgear at the top. We can go without the EU completely or give us the option to put USA as well. If there is a way of doing this myself please let me know. I am not a coder, but I do know how to open up html files and look for words and replace them.

**Comment by mojojojojo** [comment]
I know this can be done manually. I am requesting it to be done where the script does it automatically by seeing the routers make. So it says "Netgear Firmware" or "Cisco Firmware".

**Comment by blackHatMonkey** [comment]
Doing what you describe is a lot harder than it sounds and requires a lot of modification. A better approach is to have multiple pages for common routers. For example have a page for cisco and other common router manufactures or for different countries and languages.

**Comment by sophron** [comment]
Hi @mojojojojo,

I think you are suggesting #5. This will be delivered soon enough.
