### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by wermaxta** [sophron/wifiphisher#177]
Hi how many wireless cards in need to start wifiphisher because when i type python wifiphisher.py
i got this message 
Only one wireless interface found. Closing...
My OS is Kali Linux 2 Sana 
Linux kali 4.0.0-kali1-686-pae #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) i686 GNU/Linux
Thank you .

**Comment by sophron** [comment]
Please read the <a href="https://github.com/sophron/wifiphisher#requirements">requirements</a>.

**Comment by wermaxta** [comment]
Thank you for quick answer. :)

**Comment by sachinrathore211** [comment]
Only one wireless interface found. Closing...
How to solve??

**Comment by blackHatMonkey** [comment]
Please read [requirements](https://github.com/sophron/wifiphisher#requirements). You need two wireless adapters.

**Comment by sachinrathore211** [comment]
OK, but when I start the adapter does not connect Who does my laptop wifi

**Comment by blackHatMonkey** [comment]
@sachinrathore211 

Not sure I understand your situation. Do you have 2 adapters or only one?

**Comment by sachinrathore211** [comment]
The first two have become one. Who does when I start on both my laptop wifi adapter offers no catches.
