### ISSUE TITLE
Not able to see fake AP in action

### ISSUE THREAD

**Issue by mojojojojo** [sophron/wifiphisher#178]
My adapters are AWUSO36H and AWUSO36NEH. I want to confirm that the problem is my adapter? IF it is what adapter should I get? I feel so unhappy because Ive spent a 50$ on these two just to try this and now Im reading on here they dont work well with this. 

I am able to see the "DHCP" lease and "http request" but when I check my phone or pc its able to access google. I dont know why I cant see the fake login?

**Comment by mehranexpert** [comment]
yes , unfortunately it not support it i dont know WHY , Evil-Twin work well with Alfa but this not .

**Comment by mojojojojo** [comment]
Which adapters do you have or would work? Can you give me the name of two?

**Comment by frafrichile** [comment]
I would like the name of two that I could use with this as well. 

Thanks !

**Comment by sophron** [comment]
We've discussed this in numerous threads. It's something that has to do with `hostapd`. We'll push a patch soon hopefully.
