### ISSUE TITLE
Doesn't work here. Does not deauthenticate clients nor creates fake AP

### ISSUE THREAD

**Issue by brunoaduarte** [sophron/wifiphisher#179]
Doesn't work here. Doesn't deauthenticate devices nor creates fake AP.

Kali v2.0

WLAN0: Broadcom Corporation BCM4311 802.11b/g WLAN (rev 01)
WLAN1: Ralink Technology, Corp. MT7601U Wireless Adapter

both supports injection

**Comment by blackHatMonkey** [comment]
Please fill a proper [bug report](https://github.com/sophron/wifiphisher/wiki/Bug-reporting-guidelines) and post the result.

**Comment by frafrichile** [comment]
which cards do you guys recommend?

**Comment by sophron** [comment]
Hi @brunoaduarte,

Please don't open a new thread if there's already a relevant open issue. This has been reported multiple times in the past.
