### ISSUE TITLE
change the text of updating.html 

### ISSUE THREAD

**Issue by Brok3** [sophron/wifiphisher#18]
would be better if the writing in the "updating.html" file was shorter and said "please wait while updating"

**Comment by alouanemed** [comment]
You mean "upgrading.html' file ;and it has already this message  : 
: <p>Please wait while we do the upgrade.</p>

**Comment by sophron** [comment]
Hi @Brok3,

I'm not sure i understand correctly what you mean. There's already a message in the page.

**Comment by sandman6578** [comment]
change it yourself ;] 
open the file in in leafpad or another editor search in the <body> </body>

**Comment by sandman6578** [comment]
body tag sry

**Comment by sophron** [comment]
Hi @Brok3,

What you propose makes actually no difference. Any user can still edit the template.
