### ISSUE TITLE
not working in ubuntu

### ISSUE THREAD

**Issue by shivamjaat** [sophron/wifiphisher#180]
Only one wireless interface found. Closing...

again and again help me

**Comment by blackHatMonkey** [comment]
Please fill a proper [bug report](https://github.com/sophron/wifiphisher/wiki/Bug-reporting-guidelines) and post the result.

**Comment by sophron** [comment]
Hi @shivamjaat,

You need two wireless network adapters for the tool to work.

**Comment by frafrichile** [comment]
Hi @sophron  could you please give me the names of two working cards? I have the alfa you mention in the FAQ but unsure about what should be my second one.
Thanks!

**Comment by sophron** [comment]
Hi @frafrichile,

As you can see, your question is completely irrelevant with this thread (as well as the other 10 threads that you posted the same question).

I'm aware that some people are experiencing problems with their network cards. I believe the problem lies somewhere in `hostapd` side. I will make a post as soon as i figure out exactly what's wrong. Try to be patient until then. :)

**Comment by frafrichile** [comment]
You are right @sophron  

Thanks for the answer. I will patiently wait !

**Comment by blackHatMonkey** [comment]
@sophron,

I think the problem lies in ```start_ap``` function. I'm going to test it to see if I can figure out the problem.

**Comment by blackHatMonkey** [comment]
@sophron 

After a quick test and inspecting the contents of ```hostapd.conf``` in ```/tmp``` it seems that ```wifiphisher``` choose the card that has no ```AP mode```.  Also running the fallowing command
```bash
$ hostapd hostapd.conf

Configuration file: hostapd.conf
nl80211: Could not configure driver mode
nl80211 driver initialization failed.
hostapd_free_hapd_data: Interface wlan0 wasn't started
```
results in a error that ```wifiphisher``` never reports.

**Comment by blackHatMonkey** [comment]
@sophron 

After further testing the problem, I found a workaround which involves manually setting the apinterface using the ```-aI``` flag.

**Comment by sophron** [comment]
@blackHatMonkey,

Yes, indeed the `nl80211 driver initialization failed` is the issue, that appears to be a problem with `hostapd`. We should catch this error and present a message back to the user. 

Setting manually the interface may or may not work depending on your other wireless card, but it is certainly a good recommendation.
