### ISSUE TITLE
Make Wifiphisher more modular

### ISSUE THREAD

**Issue by blackHatMonkey** [sophron/wifiphisher#182]
@sophron 

Here is what I propose:
![uml](https://cloud.githubusercontent.com/assets/15163267/11755842/21e3d142-a023-11e5-9c11-44462e8bb2f2.png)
To break down the project into smaller modules.

**Comment by HassenPy** [comment]
maybe another module for the server

**Comment by blackHatMonkey** [comment]
I was thinking to put the server in the ```phishingpage``` module since it's related to the ```phishingpage```.

**Comment by cutff** [comment]
Great Idea Thanks

**Comment by sophron** [comment]
I agree with your separation logic. I believe `phishingpage` can be a different module than the `minimalserver`. Specifically:

`phishingpage`: All the logic that has to do with getting the right phishing page, from the filesystem or the web, or determining the right page according to the router manufacturer (#5).

`minimalserver`: A minimal web server with all our needed features (redirect HTTPS to HTTP, show same page for different requests, accept shutdown signal, write credentials to log files etc).

`jamming`: Everything that has to do with jamming. Probably a copy of <a href="https://github.com/DanMcInerney/wifijammer">wifijammer</a>.

`interfaces`: A wrapper for the Linux utilities that we are using (`ifconfig`, `route`, `iptables` etc). 

What do you think?

**Comment by blackHatMonkey** [comment]
I agree that putting all the server related operations in it's own module would clean up the code a lot. Also I was thinking of putting all the modules in a single package for easier importing.

**Comment by blackHatMonkey** [comment]
Here is a more complete UML and I'm sure there is a complete of mistakes in there since I'm not familiar with every function.

![untitled diagram](https://cloud.githubusercontent.com/assets/15163267/11799696/6a8d3a7c-a2a4-11e5-9291-13a6328f7dcd.png)

Let me know what you think of it.

**Comment by blackHatMonkey** [comment]
And I made a simple flow chart: 

![flowchart](https://cloud.githubusercontent.com/assets/15163267/11881495/2313f130-a4d5-11e5-9f0a-a4593d8850ce.png)

**Comment by frafrichile** [comment]
I just wanted throw a suggestions. I noticed it is not mobile compatible. Maybe add that in the future.

**Comment by blackHatMonkey** [comment]
What do mean by mobile compatible?

**Comment by frafrichile** [comment]
When I connect to the open access point created by wifiphiser the page that ask for user to enter the password is really small. Cant read it on the smartphone but if we make the pages all mobile compatible. It detects when browser is smartphone and it adjust the screen size so user can read better and doesnt have to pinch the screen

**Comment by blackHatMonkey** [comment]
Yes I wrote a new page for ```linksys``` with ```bootstrap``` that will adjust to all screen sizes.

**Comment by sophron** [comment]
@blackHatMonkey Nice, they look good. I don't currently have the time to check how accurate these diagrams are but I imagine new developers may find them helpful. I propose adding these to our <a href="https://github.com/sophron/wifiphisher/wiki">wiki</a>. You can create a new page for documenting the whole project.

@frafrichile, While our `minimal` template doesn't support mobile resolutions, the rest of our templates do. But please don't go off-topic on this thread.

**Comment by blackHatMonkey** [comment]
@sophron checkout the wiki on my fork and let me know if you like the style. I already wrote a page for ```phisihingpage``` module.

**Comment by sophron** [comment]
Looks good. Feel free to make changes directly in main repo's wiki. I believe you have rights to do it.

**Comment by jamalala** [comment]
Mr sophron: canyou tell me please why i do not see the page of the "update of the router". When i create an fake ap of my ap, and i connect to it, nothing happen it does nothing it also not showing the page of the upgrade!!?? please tell me what to do, thanx

**Comment by blackHatMonkey** [comment]
@jamalala 
Please make a new issue as your problem is not related to this thread.

**Comment by sophron** [comment]
We definitely have progress here. After we introduce the `jamming` module, I will consider this issue closed.

**Comment by sophron** [comment]
I'm closing this since it's too generic. We are in a good state now but definitely there's room for improvement. We can open separate issues for each specific module though.
