### ISSUE TITLE
help me!!python error (ubuntu 14.04)

### ISSUE THREAD

**Issue by songdongcheol** [sophron/wifiphisher#183]
^CException in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wifiphisher.py", line 832, in sniff_dot11
    sniff(iface=mon_iface, store=0, prn=cb)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 485, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
error: [Errno 100] Network is down

**Comment by blackHatMonkey** [comment]
I believe that One of your network adapters are turned off. Please run the fallowing commands:
```bash
$ sudo ifconfig -a
```
get the name of the two adapters
```bash
$ sudo ifconfig wlanx up
$ sudo ifconfig wlanx up
```
and replace ```x``` with the numbers you got.

**Comment by caixiawang** [comment]
Dear@blackHatMonkey  Help me, I run wifiphisher fail, execute the command again, the following error!
I post questions, I do not know why the administrator was deleted, wrong place, please forgive me!
root@kali:~/wifiphisher# sudo python wifiphisher.py -aI wlan1 -jI wlan0
[-] Unable to start HTTP server!
[-] Another process is running on port 8080.
[!] Closing

**Comment by blackHatMonkey** [comment]
The issue should be solved now. If you still experience any issues after upgrading to the latest version feel free to open a new issue.
