### ISSUE TITLE
Add support for network adapter compatibility check

### ISSUE THREAD

**Issue by FallenArchangel** [sophron/wifiphisher#185]
Whenever I try to run this on Kali 2.0

It will detect my devices, scan for networks, then ask me which network to target.
Everything runs just fine until it tries to start the AP.  As soon as it does, my entire system will freeze, only fixable by powering off the device.

If I run airmon-ng check kill, it will sometimes take a few seconds longer to kill.  Using another device, I can see that it is creating an AP with the name of linksys_wlan. (Which is not the name of my target network)

I am using my built in laptops wifi card (Monitor mode, don't remember what else.) as well as a AWUS036NEH (Monitor mode, injection, master(ap), pretty much everything.)

----------------------------------------------------------------------------------------------------------------------------------

Update: It appears to be using the wrong card to start the AP.  My laptops built in wifi doesn't support monitor mode, so I have to add the -aI wlan1 parameter.

Perhaps add a way for the program to check before trying?

**Comment by blackHatMonkey** [comment]
Yes indeed there are problems with the card detection. However it is currently being worked on. see #182.

**Comment by sophron** [comment]
We should be good with that now. Please update to the latest revision and let us know if any problems.
