### ISSUE TITLE
wifiphisher not deauthenticating

### ISSUE THREAD

**Issue by subscriber360** [sophron/wifiphisher#188]
This script cannot deauth client from AP, i thought maybe my USB adaptor is not good enough, 
So i tested Aireplay-ng which works perfectly but i don't know why it can't deauth ?

I have ALFA AWUS036H , it easily deauth clients.So i am sure that there is nothing wrong with it.

I am using HP Notebook DV6...

I also tried -jI [my usb adaptor] still can't Jam/Deauth client from Original AP...

Any one can please help me ?

**Comment by blackHatMonkey** [comment]
We are are aware of problems in both creating and jamming in ```wifiphisher```. These problems are currently being worked on and hopefully should be fixed by the next version of the software. In the mean while you may want to try running the ```-aI``` command instead of ```-jI``` and see if fixes the problem.

**Comment by subscriber360** [comment]
@blackHatMonkey 
already did it, Hope it get fix soon.

**Comment by geegee456** [comment]
Same here its not jamming anything

**Comment by blackHatMonkey** [comment]
@subscriber360 @geegee456 Try using the latest version and report back if you have any problems.
