### ISSUE TITLE
package hostapd has no installation candidate

### ISSUE THREAD

**Issue by 1974darrenh** [sophron/wifiphisher#190]
I'm trying to install Wifiphisher but when the screen comes up "hostapd not found in usr/sbin/hostapd" I try to install it but I get an error. 

![ubuntu 64-bit 2 -2015-12-26-18-03-20](https://cloud.githubusercontent.com/assets/16202123/12007427/10d06a5c-abfc-11e5-98e8-db944fe4c48c.png)

What do I do?

Thanks.

**Comment by blackHatMonkey** [comment]
Can you please show us the contents of ```/etc/apt/sources.list``` file.

**Comment by 1974darrenh** [comment]
# Regular repositories
deb http://http.kali.org/kali sana main non-free contrib
deb http://security.kali.org/kali-security sana/updates main contrib non-free

# Source repositories
deb-src http://http.kali.org/kali sana main non-free contrib
deb-src http://security.kali.org/kali-security sana/updates main contrib non-free

**Comment by blackHatMonkey** [comment]
Edit the files to match the fallowing:
```
deb http://http.kali.org/kali sana main non-free contrib
deb http://security.kali.org/kali-security sana/updates main contrib non-free

deb-src http://http.kali.org/kali sana main non-free contrib
deb-src http://security.kali.org/kali-security sana/updates main contrib non-free
```
And then do:
```bash
sudo apt-get update
```
Fallowed by:
```bash
sudo apt-get dist-upgrade
```
And then try to re-run ```wifiphisher```. Let me know if you have any more questions.

**Comment by 1974darrenh** [comment]
ok thanks :)

**Comment by 1974darrenh** [comment]
Changed it and now I get this -

![ubuntu 64-bit 2 -2015-12-26-19-16-17](https://cloud.githubusercontent.com/assets/16202123/12007652/ab9ea96e-ac05-11e5-8221-d20a0783fc1a.png)

**Comment by blackHatMonkey** [comment]
Run these commands:
```bash
sudo rm /etc/apt/sources.list
sudo wget http://filebin.ca/2RJK8V0Z5AXY/sources.list -P /etc/apt/
```
This is a copy of my ```sources.list```. Let me know if you have any more questions.

**Comment by 1974darrenh** [comment]
Still not working

![ubuntu 64-bit 2 -2015-12-26-19-38-03](https://cloud.githubusercontent.com/assets/16202123/12007699/4630e346-ac08-11e5-8eb1-6e41e0d7acb9.png)

**Comment by blackHatMonkey** [comment]
Are you able to connect to the internet?

**Comment by 1974darrenh** [comment]
It had disconnected for some reason. Connected again and this is what I have this time.

![ubuntu 64-bit 2 -2015-12-26-19-55-58](https://cloud.githubusercontent.com/assets/16202123/12007746/cd769182-ac0a-11e5-8a6b-c838ad93297b.png)

**Comment by blackHatMonkey** [comment]
Can you inspect ```/etc/apt``` to see if it has downloaded the file and open to make sure the content matches 
```
# 

# deb cdrom:[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot i386 LIVE/INSTALL Binary 20150808-07:40]/ sana contrib main non-free

#deb cdrom:[Debian GNU/Linux 2.0 _Sana_ - Official Snapshot i386 LIVE/INSTALL Binary 20150808-07:40]/ sana contrib main non-free

deb http://http.kali.org/kali sana main non-free contrib
deb-src http://http.kali.org/kali sana main non-free contrib

deb http://security.kali.org/kali-security/ sana/updates main contrib non-free
deb-src http://security.kali.org/kali-security/ sana/updates main contrib non-free
```

**Comment by 1974darrenh** [comment]
![ubuntu 64-bit 2 -2015-12-26-20-15-20](https://cloud.githubusercontent.com/assets/16202123/12007810/8b88fe4c-ac0d-11e5-8e2d-797ab149ccdc.png)

**Comment by blackHatMonkey** [comment]
Can you post a screen shot of ```/etc/apt``` folder?

**Comment by 1974darrenh** [comment]
![ubuntu 64-bit 2 -2015-12-26-20-26-41](https://cloud.githubusercontent.com/assets/16202123/12007838/0706d0de-ac0f-11e5-98ee-04b36ac66390.png)

**Comment by 1974darrenh** [comment]
Should I just reinstall Kali from scratch?

**Comment by blackHatMonkey** [comment]
You are missing ```sources.list``` file. Copy and paste this command:
```bash
sudo wget http://filebin.ca/2RJK8V0Z5AXY/sources.list -P /etc/apt/
```
And after you should be able to see a ```sources.list``` file.

**Comment by 1974darrenh** [comment]
Ok done than. I have noticed there are 2 sources.list folders


![ubuntu 64-bit 2 -2015-12-26-20-48-15](https://cloud.githubusercontent.com/assets/16202123/12007892/22b8d55e-ac12-11e5-86f2-58a260fd29b8.png)

![ubuntu 64-bit 2 -2015-12-26-20-51-40](https://cloud.githubusercontent.com/assets/16202123/12007899/855f7316-ac12-11e5-9b5c-3ae6ae04d8b7.png)

**Comment by blackHatMonkey** [comment]
You can remove the one that is in ```/home/YOURUSERNAME/```

**Comment by blackHatMonkey** [comment]
@1974darrenh If your problem is solved please close this issue. :)

**Comment by 1974darrenh** [comment]
I reinstalled Kali and then Wifiphisher, and it is working now.


Thank you for your help. much appreciated :)

**Comment by ghost95** [comment]
I have been using kali with a live usb, but then i installed it on my hard drive now i can not get hostapd to download i have tried all of the above, please help!

**Comment by astra22** [comment]
same problem here can anyone help me out?

**Comment by miladmusavi** [comment]
hostapd not found in /usr/sbin/hostapd
