### ISSUE TITLE
Slow  http page  serving

### ISSUE THREAD

**Issue by sjeps** [sophron/wifiphisher#192]
I'm using two T link t772 on an installed and updated kali 2.0.
Jamming works, ap creation works.
Ip address (dhcp) USUALLY works (not always).
What is not working really good is page serving. Doing a simple query for a bookmark may take 30 second or more to display the pishing page. Also often the page doesn't show up at all.

The same goes with the response POST.. very slow (but this is less an issue)

**Comment by tonynumero10** [comment]
Me too!!! Why??

**Comment by blackHatMonkey** [comment]
Try using the ```1.1``` version of ```wifiphisher``` and see if anything changes.

**Comment by sjeps** [comment]
1.1 look like the samefor me.. Slow serving.

Also i noticed direct bookmarks like www.amazon.com work while sites with sub pages like www.amazon.com/account do not work and respond 404.

On which version of kali linux is the project being developed?

**Comment by tonynumero10** [comment]
I tried with the latest version. I tried with different versions of airmon - ng. I tried with different wifi usb adapters. I tried several different browers phones and PC. He works for me only www.google.it and only slowly. Help me please.

**Comment by blackHatMonkey** [comment]
@sjeps 
The project is being developed on ```kali 2.0```.

@sjeps @tonynumero10 
I would guess that serving the page slowly would be rather a hardware problem. As for the redirecting problem it seems to be the redirect function in the ```HTTPServer```.

Can you try opening ```10.0.0.0:8000``` and see if the page loads.

Another thing that I would like you guys to run is:
```bash
wget -O - http://10.0.0.0:8000
```
and 
```bash
wget -O - http://google.com
```
Please post the output of those commands while connected to the fake network created by ```wifiphisher```.

**Comment by sjeps** [comment]
I don't have a spare linux to try that commands. Anyway the 404 issue seems software related.. Messing with your script do_GET function etc.. seemed to modify the behaviour in my case.

Slow page serving come in bursts. The first page loading on a device is usually slow , then sometime it is very fast (caching?), sometime slow

**Comment by blackHatMonkey** [comment]
Can you tell us what you changed in the ```do_GET``` function.

**Comment by sjeps** [comment]
I don't understand the whole code so i was just messing around. For example changing
If self.page == "/":
and changing it to
if True

Made the pages be served even for subpages like www.amazon.com/account

**Comment by sophron** [comment]
Hi @sjeps,

I'm aware of the issue. Expect a fix soon enough.

**Comment by tonynumero10** [comment]
Hi, in this thread I learned that i'm hardware problem. I think it's very true.
I have 5 wifi cards, in order from the most powerful: ALFA AWUS036NHA (ATHEROS), TP-LINK TL-WN822N (REALTEK), DLINK DWL-G122 (REALTEK), PCI ATHEROS AR9485, ASUS WL-167G (RALINK). All of five work with aircrack suite and support injection. More network I find in monitor mode with a wifi card, less wifiphisher works. If I use the two worst cards, ASUS WL-167G 54Mbps and the PCI ATHEROS, wifiphisher works very ultra maxi good! In a second open the fake page and in a second stolen the wpa password, in the 100% of the cases. Any other combination doesn't work good. Why? With the two worst cards I see network only very very near. Can I do?

**Comment by blackHatMonkey** [comment]
@tonynumero10 
There are two aspects to ```wifiphisher```. First being the de authentication and second being the access point hosting. The slow page loading is rather the access point hosting problem and I think it should work on all cards that support it. For instance I have the ```ALFA AWUS036NHA``` and ```ALFA AWUS036H``` and it works fine as long as I specify which card to use for monitor mode. So I always run this command
```bash
sudo python2 wifiphisher.py -jI (ALFA AWUS036H)
```
Let me know if that helps.

**Comment by tonynumero10** [comment]
I'll try! I use python and not python2. Is it a problem?

**Comment by blackHatMonkey** [comment]
It shouldn't be a problem but just to be safe.

**Comment by sophron** [comment]
@sjeps, @tonynumero10, @blackHatMonkey I just pushed a commit that makes the web server react much faster. Let me know how it works for you.

**Comment by tonynumero10** [comment]
Great! Now works very wonderfull! It's fast and the redirect works for all page. Only not deauthenticate the clients (i tried with android phone), i must use another usb wifi with aireplay, but i'snt a problem for me. Thanks very thanks.
