### ISSUE TITLE
The fake ap is not same as the real

### ISSUE THREAD

**Issue by iidiir** [sophron/wifiphisher#195]
Hello,

I want to use this tool to test my wifi's security, with kali linux installed in vmware,
My two cards are compatible, but the fake ap which is created is always open (no password) is this normal ?
when the opperation start, i have client in jamming but it's not asking the client for the pass (i think because my fake ap is open)

so i wish that you'll help me

Thank you

**Comment by blackHatMonkey** [comment]
Duplicate of #152.

**Comment by sophron** [comment]
Hi @iidiir,

Yes, this is how the tool works. Please check #152 for a more complete answer.

**Comment by iidiir** [comment]
thank you =D
