### ISSUE TITLE
wifiphisher does not show ESSID

### ISSUE THREAD

**Issue by SuicSoft** [sophron/wifiphisher#196]
If I use other tools such as aircrack or wifite I can see the ```ESSID``` but if I use ```wifiphisher``` it does not show the ```ESSID``` and does not work. I am using Elementary OS freya 64-bit on a HP Pavilion g7 2030ca

**Comment by blackHatMonkey** [comment]
I came upon this bug as well. After the ```Cleared leases, started DHCP, set up iptables``` you won't get any output correct?
Also If when you press ```Ctrl + c```did you get this message ```Choose the [num] of the AP you wish to copy:```.
If the above matches your situation then it's because of ```wifiphisher``` choosing the wrong card for you. 
Try setting the card using ```-aI``` and ```-jI``` commands.

**Comment by SuicSoft** [comment]
@blackHatMonkey When I press ```CTRL + C``` I do get the message.When I use ```sudo ./wifiphisher.py -aI mon0``` (after ```sudo airmon-ng start wlan0```)  I still do not get the ESSID. But when I use ```sudo ./wifiphisher.py -jI mon0``` I get :
```
[*] Starting HTTP server at port 8080
[*] Starting HTTPS server at port 443
[+] Starting monitor mode off mon0
mon0: ERROR while getting interface flags: No such device
Error for wireless request "Set Mode" (8B06) :
    SET failed on device mon0 ; No such device.
mon0: ERROR while getting interface flags: No such device
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "./wifiphisher.py", line 994, in <module>
    sniffing(mon_iface, targeting_cb)
  File "./wifiphisher.py", line 428, in sniffing
    sniff(iface=interface, prn=cb, store=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 561, in sniff
    s = L2socket(type=ETH_P_ALL, *arg, **karg)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 455, in __init__
    self.ins.bind((iface, type))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 19] No such device
```

**Comment by blackHatMonkey** [comment]
You don't need to run ```airmon-ng``` before starting ```wifiphisher```. Try running
```bash
sudo ./wifiphisher.py -jI wlan1
```

**Comment by SuicSoft** [comment]
@blackHatMonkey ```wifiphisher``` still doesn't show the ESSID. Also I'm using the internal laptop wifi card

**Comment by blackHatMonkey** [comment]
Which one of your cards support ```AP``` mode?

**Comment by SuicSoft** [comment]
I can create APs using my operating system and can use aircrack with my
internet Wifi card

On Sun, Jan 10, 2016, 8:07 PM Brian <notifications@github.com> wrote:

> Which one of your cards support AP mode?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sophron/wifiphisher/issues/196#issuecomment-170353911>
> .
>
-- 
The Studio/Software Dog,
Suici Doga

Sent from Inbox by Gmail

**Comment by SuicSoft** [comment]
In the previous comment internet is internel

**Comment by blackHatMonkey** [comment]
You need to start ```wifiphisher``` with the ```-jI``` argument on the card with ```monitor``` mode. For instance if the ```wlan0``` card supports ```monitor```mode then
```bash
sudo python2 wifiphisher.py -jI wlan0
```

**Comment by SuicSoft** [comment]
@blackHatMonkey Also I have only one WiFI card

**Comment by sandman6578** [comment]
You need two cards. This is a must!

**Comment by SuicSoft** [comment]
@sandman6578 I have some old Wireless-G cards WiFi cards lying around. Is there any way I could use them through USB.

Or better use another computer since I have another computer with a Wireless-N card which supports monitor mode.

**Comment by sandman6578** [comment]
Buy yourself an USB wifi card. I recommend TPLink tlwn722n or the alfa awus036h(does not support AP mode but in opinion the best for jamming the shit out of your vics :) )

**Comment by SuicSoft** [comment]
@sandman6578 Can I use another computer

**Comment by blackHatMonkey** [comment]
@SuicSoft The new version of ```Wifiphisher``` has a network adapter compatibility check. So if you upgrade to the latest version you can easily check if your adapters are compatible or not.
