### ISSUE TITLE
No devices in jamming devices displayed

### ISSUE THREAD

**Issue by miquel09** [sophron/wifiphisher#197]
If I start wifiphisher it works but afte I selected an AP it just says:

```
Jamming devices:



DHCP Leases:



HTTP requests:



```

is there any way to fix this?

**Comment by blackHatMonkey** [comment]
Was the fake access point created?

**Comment by miquel09** [comment]
It did say "x set up on channel x via wlanx using wlanx"

**Comment by blackHatMonkey** [comment]
Can you check to see if the access point was created using a phone or another computer?

**Comment by miquel09** [comment]
I can find the network with my phone

**Comment by blackHatMonkey** [comment]
And does the output change when you connect to it or not?

**Comment by WarHawk1** [comment]
Do you have 2 wireless adapters?

**Comment by miquel09** [comment]
I do have 2 addapters and if I connect to my AP it tells me that there is a connection but it doesnt show a new dhcp lease

**Comment by WarHawk1** [comment]
Take a look at #192

**Comment by Vigilence** [comment]
I found that if the wifiphisher shows no ap or devices to jam, connecting the monitor card to the targets channel in airodump-ng resolves the issue.  However, I can't confirm if they are being jammed or not.

So far, no success using this program.

**Comment by caixiawang** [comment]
I have encountered this problem

**Comment by blackHatMonkey** [comment]
Please try using the latest version of ```wifiphihser``` and see if it solves the problem. If you then still experience any issues, feel free to open a new issue.
