### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by wermaxta** [sophron/wifiphisher#2]
Hi. I test the script on Kali Linux and i got error message 
root@kali:~/wifiphisher# python wifiphisher.py
[*] Starting HTTP server at port 8081
[*] Starting HTTPS server at port 444
[+] Networks discovered by wlan0: 2
[+] Starting monitor mode off wlan0
[*] Cleared leases, started DHCP, set up iptables
[+] Ctrl-C at any time to copy an access point from below
num  ch   ESSID
---------------
1  - 3  - TALKTALK-E9C860
2  - 13 - Service
3  - 11 - BTWifi-X
4  - 11 - BTWifi-with-FON
5  - 7  - TALKTALK036C9E
6  - 6  - BTHub5-JQ2S
^C
[+] Choose the [num] of the AP you wish to copy: 3
[*] Starting the fake access point...
Traceback (most recent call last):
  File "wifiphisher.py", line 775, in <module>
    + W + ' on ' + T + ap_iface + W
TypeError: cannot concatenate 'str' and 'bool' objects

/wifiphisher# python2 --version
Python 2.7.3

Thank you.

**Comment by strasharo** [comment]
I think that the issue above is already resolved by this commit:
https://github.com/sophron/wifiphisher/commit/09cf393cda7b79f28017b3b2eb081399beaf3217
I guess this ticket can be closed.

**Comment by muleyl** [comment]
Please help me with this error. 
Once I select the AP number, the following pops up..

Traceback (most recent call last):
  File "wifiphisher.py", line 743, in <module>
    dhcp(dhcpconf, ap_iface)
  File "wifiphisher.py", line 407, in dhcp
    Popen(['ifconfig', mon_iface, 'mtu', '1400'], stdout=DN, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

**Comment by strasharo** [comment]
As I already said in numerous tickets, https://github.com/sophron/wifiphisher/pull/8 will fix the issue, however it's still not merged.

**Comment by verdug0** [comment]
strasharo: but, leylmordor seems to be using python2.7

**Comment by strasharo** [comment]
The error looks exactly the same to me, including the line numbers.

**Comment by FurqanHanif** [comment]
#8 Not Work For me Too (Linux Mint 17)... :(

**Comment by sophron** [comment]
@FurqanHanif Please open a new ticket with the error you are getting.
