### ISSUE TITLE
Check that all necessary tools and libraries are in place

### ISSUE THREAD

**Issue by sophron** [sophron/wifiphisher#200]
Apparently, more and more people are running the tool out of Kali. We should perform a check that all necessary components are in place. We currently have only one check for `hostapd`. A `setup` script (from `setuptools`) could also come in handy.

**Comment by WarHawk1** [comment]
Are you talking about libraries as well as hardware setup?

**Comment by WarHawk1** [comment]
In case of only requirements how about adding requirements.txt?

**Comment by phr34k0** [comment]
Yep.. What are the requirements?? I have to airmon-ng check kill every freaking time and thus make hostapd work but unable to browser when connected.

**Comment by WarHawk1** [comment]
I had a similar problem with Kali Linux 2.0 sana. It's monitor mode is wlan0mon so I switched to Kali 1

**Comment by phr34k0** [comment]
Tool is old. Prolly needs an updated python script. I am not downgrading due to a deprecated issue just to get this working. Currently on Kali rolling. Still yet to get this working on Kali Nethunter on Mobile.

**Comment by WarHawk1** [comment]
Do you have problem like #135?

**Comment by WarHawk1** [comment]
You can use live boot of Kali 1..!!

**Comment by phr34k0** [comment]
Still a no.. Sorry.. Deprecated tools. Tho still prefer the new matured Airmon-zc with WPS support, I usually do alot of multitasking on this pc so booting right off a cd ( which is slow ) while i need to use other programs is not an option. I have seen scripts utilizing that wlan0mon. Not sure why this wasn't updated here.

**Comment by phr34k0** [comment]
Nope.. more of this error https://github.com/sophron/wifiphisher/issues/121

Tested the released tar.gz , Jamming works but not Hostapd.
Tested the latest git cloned, Jamming works but not Hostapd

Hostapd will work on both releases if "airmon-ng check kill && dhclient eth0", which eth0 is used for internet and wlan0/wlan1 is used for this script. Downside, git cloned version doesn't open port 8080 nor 443 for Phish website.

The script itself doesn't throw an error and 'exit 0' nicely like >> /dev/null

**Comment by WarHawk1** [comment]
Can you post error message or screenshot??

**Comment by WarHawk1** [comment]
And which adapters you are using??

**Comment by WarHawk1** [comment]
Take a look at #192

**Comment by phr34k0** [comment]
Check here.. https://github.com/sophron/wifiphisher/issues/184#issuecomment-174522097

**Comment by WarHawk1** [comment]
I think its a version conflict of airmon

**Comment by blackHatMonkey** [comment]
@WarHawk1 @phr34k0 
Please use #184 for discussion regarding the problem.

**Comment by sophron** [comment]
We now have a setup.py file.
