### ISSUE TITLE
Wifiphisher error

### ISSUE THREAD

**Issue by vishal43** [sophron/wifiphisher#204]
Traceback(most rcent call last ):
File"wifiphisher.py" line17, in (module)
From subprocess import pipen.pipe .check.output
import error:canot import name check output

**Comment by blackHatMonkey** [comment]
Thank you. Can you post the result of this command:
```bash
python --version
```

**Comment by vishal43** [comment]
Python 2.6.5

**Comment by blackHatMonkey** [comment]
Please update to ```python 2.7``` and try again.

**Comment by vishal43** [comment]
[+] Choose the [num] of the AP you wish to copy: 1
[*] Starting the fake access point...
Traceback (most recent call last):
  File "wifiphisher.py", line 952, in <module>
    if not dhcp(dhcpconf, ap_iface):
  File "wifiphisher.py", line 509, in dhcp
    dhcp = Popen(['dnsmasq', '-C', dhcpconf], stdout=PIPE, stderr=DN)
  File "/usr/local/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by vishal43** [comment]
my wifi cards are tp link tl wn722n
and d link  dwa 525

**Comment by blackHatMonkey** [comment]
Please take a look at #194. You need to install ```dnsmasq``` and the instructions can be found in #194.

**Comment by sophron** [comment]
As @blackHatMonkey said, you need to install `dnsmasq` to proceed.
