### ISSUE TITLE
Wifiphisher not starting

### ISSUE THREAD

**Issue by forid786** [sophron/wifiphisher#205]
Hey there,

after the latest update I am unable to start wifiphisher. I'm getting this error below.

 File "wifiphisher.py", line 840
    else if os.path.isfile('/usr/bin/yum'):
          ^
SyntaxError: invalid syntax

**Comment by sophron** [comment]
Thanks for reporting, please try again now.

**Comment by forid786** [comment]
That worked, the script starts, however it looks for dnsmasq in /usr/bin/dnsmasq. My dnsmasq is in /usr/sbin/dnsmasq and it is unable to detect it. I managed to fix the problem by making this simple change on line 847.

`if not os.path.isfile('/usr/bin/dnsmasq'):` changed to : `if not os.path.isfile('/usr/sbin/dnsmasq'):`. Maybe you can have a look at this too and fix it? 

Thanks for the fast reply. :)

**Comment by sophron** [comment]
I just pushed a commit. Thanks.

**Comment by forid786** [comment]
All working perfectly now. Thanks for pushing out the commit, I'll close this. :)

**Comment by chengb0** [comment]
@forid786  hi.i have some problems the same as yours.iwant to konw how did you delt it .thank you very much.

**Comment by forid786** [comment]
@chengb0 All the fixes are pushed out already. Delete your WifiPhisher folder then run another git clone, it should download the fixed version. Be sure to update python too.

**Comment by chengb0** [comment]
i use kali2.0 in workstation12.two Rt8187L wireless adpter.and my curent version is wifiphisher-1.1

**Comment by forid786** [comment]
@chengb0 Download the latest release with the latest fixes.

**Comment by chengb0** [comment]
@chengb0  It is said that the wifiPhisher-1.1 doesn't work successfully in kali2.0 and kali16.1,i kown you have get success .what kali-version are you using?

**Comment by chengb0** [comment]
@forid786 It is said that the wifiPhisher-1.1 doesn't work successfully in kali2.0 and kali16.1,i kown you have get success .what kali-version are you using?

**Comment by sophron** [comment]
@forid786 It is unlikely that you got the same error using the `1.1` release. You are probably dealing with a different issue.

**Comment by forid786** [comment]
@sophron I don't think he's having the same issue either. Because it has been fixed, and was only there from the previous merge right?

@chengb0 I haven't really done anything special to my Kali machine in order to make it work, except update everything. I'm not aware of it not working on Kali 2.0, I know a lot of people use it with Kali 2.0, I think even @sophron is using Kali 2.0. Can you provide us with a screenshot of the error you are experiencing so we can have a look at it and perhaps assist further?

Thanks
