### ISSUE TITLE
Network is down error after shutdown

### ISSUE THREAD

**Issue by vishal43** [sophron/wifiphisher#207]
Jamming devices: 
[*] c4:12:f5:00:2b:c6 - 74:04:2b:df:f2:f5 - 1[*] c4:12:f5:00:2b:c6 - 80:6a:b0:5b:1d:31 - 1

DHCP Leases: 

HTTP requests: 

^C
[!] Closing
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wifiphisher.py", line 641, in channel_hop2
    deauth(monchannel)
TypeError: 'NoneType' object is not callable
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wifiphisher.py", line 865, in sniff_dot11
    sniff(iface=mon_iface, store=0, prn=cb)
  File "/usr/local/lib/python2.7/site-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/local/lib/python2.7/site-packages/scapy/arch/linux.py", line 493, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
error: [Errno 100] Network is down

**Comment by blackHatMonkey** [comment]
Hi vishal43,

This error happens due to ```wifiphisher``` not being able to turn the card on. What I suggest doing is to disconnect the card and re-insert the card after a short period. Let me know if you have any more problems.

**Comment by vishal43** [comment]
I have d link dwa 525 pci card I think I have problem in installing it can you help

**Comment by vishal43** [comment]
And 2nd one is to link which working fine

**Comment by vishal43** [comment]
Tp  link

**Comment by blackHatMonkey** [comment]
Connect both cards and then run the fallowing command:
```bash
ifconfig -a
```
And post the results please.

**Comment by vishal43** [comment]
root@bt:~# ifconfig -a
eth0      Link encap:Ethernet  HWaddr 00:1c:c0:56:1e:c4  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:43 Base address:0x6000 

hwsim0    Link encap:UNSPEC  HWaddr 12-00-00-00-00-00-00-60-00-00-00-00-00-00-00-00  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:263 errors:0 dropped:0 overruns:0 frame:0
          TX packets:263 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:35157 (35.1 KB)  TX bytes:35157 (35.1 KB)

wlan0     Link encap:Ethernet  HWaddr c4:e9:84:dc:0a:fc  
          inet addr:192.168.0.7  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::c6e9:84ff:fedc:afc/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1098 errors:0 dropped:0 overruns:0 frame:0
          TX packets:13 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:356470 (356.4 KB)  TX bytes:2457 (2.4 KB)

wlan1     Link encap:Ethernet  HWaddr 02:00:00:00:00:00  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wlan2     Link encap:Ethernet  HWaddr 02:00:00:00:01:00  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

**Comment by vishal43** [comment]
root@bt:~# ifconfig -a
eth0      Link encap:Ethernet  HWaddr 00:1c:c0:56:1e:c4  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:43 Base address:0x6000 

hwsim0    Link encap:UNSPEC  HWaddr 12-00-00-00-00-00-00-60-00-00-00-00-00-00-00-00  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:494 errors:0 dropped:0 overruns:0 frame:0
          TX packets:494 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:63197 (63.1 KB)  TX bytes:63197 (63.1 KB)

wlan0     Link encap:Ethernet  HWaddr c4:e9:84:dc:0a:fc  
          inet addr:10.0.0.1  Bcast:10.0.0.255  Mask:255.255.255.0
          inet6 addr: fe80::c6e9:84ff:fedc:afc/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1400  Metric:1
          RX packets:841 errors:0 dropped:0 overruns:0 frame:0
          TX packets:15 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:176711 (176.7 KB)  TX bytes:1728 (1.7 KB)

wlan1     Link encap:Ethernet  HWaddr 02:00:00:00:00:00  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wlan2     Link encap:Ethernet  HWaddr 02:00:00:00:01:00  
          inet addr:10.0.0.1  Bcast:10.0.0.255  Mask:255.255.255.0
          inet6 addr: fe80::ff:fe00:100/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1400  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:42 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:4104 (4.1 KB)

**Comment by blackHatMonkey** [comment]
So it seems that your system recognizes both cards. Do you still get the same error?

**Comment by vishal43** [comment]
Yes

**Comment by vishal43** [comment]
But when I connect only dlink it hasn't show any ap in it

**Comment by blackHatMonkey** [comment]
Please run ```wifiphisher``` with the ```-aI``` argument as fallows:
```bash
sudo python wifiphisher -aI wlan#
```
Where # is your wireless interface number.

**Comment by vishal43** [comment]
Ok

**Comment by caixiawang** [comment]
Dear@blackHatMonkey Help me, I run wifiphisher fail, execute the command again, the following error!
I post questions, I do not know why the administrator was deleted, wrong place, please forgive me!
root@kali:~/wifiphisher# sudo python wifiphisher.py -aI wlan1 -jI wlan0
[-] Unable to start HTTP server!
[-] Another process is running on port 8080.
[!] Closing

**Comment by blackHatMonkey** [comment]
Please have a look at #3. The last few comments should solve your problem.
