### ISSUE TITLE
'Unable to install hostapd file'

### ISSUE THREAD

**Issue by MrLowkey1818** [sophron/wifiphisher#209]
When I clone wifiphisher over from github onto kali I get the message 'Unable to install hostapd file', I have tried airmon-ng check kill and attempted to load the kali repositories to see what was up and still nothing. It's a bit ironic I'm using more data than ever before to try get free wifi in this rip off country.
  I'm wondering what the solution is to this?

 Extra:
* Latest version of kali
* I have a reliable internet connection.
* I have an external wireless card

**Comment by blackHatMonkey** [comment]
Hi @MrLowkey1818 
Can you execute the fallowing command
```bash
hostapd
```
in the terminal and post the result.

**Comment by geegee456** [comment]
I have the same problem.

**Comment by sophron** [comment]
Hi @MrLowkey1818 and @geegee456 (I assume you are also on Kali),

Can you, please, check if `/usr/sbin/hostapd` is there? If not, can you download it with `apt-get install hostapd`.

**Comment by geegee456** [comment]
Hello thank you for your help,

i checked the folder and there is not such folder. There are only files but no folder which is called hostapd. 

I tried apt-get install hostapd. And it is not working. 

See attached image:

www.pic-upload.de/view-29735560/1455415565959-2055377805.jpg.html

**Comment by geegee456** [comment]
I figured out that the live version (when i boot from usb) works fine. But the kali linux version which have been installed on my computer acts strange in many ways. I can't even install new updates with.

apt-get update and apt-get upgrade :(

It would be very happy if someone can help me out via teamviewer or something

**Comment by sophron** [comment]
@geegee456,

My guess is that your sources on /etc/apt/sources.list are not responding. Try changing them. 

If you need any further help, I recommend asking in the <a href="https://forums.kali.org/">Kali Linux forums</a>.

**Comment by geegee456** [comment]
Ok what i have to change when i open the sources.list file?

**Comment by blackHatMonkey** [comment]
This [page](http://docs.kali.org/general-use/kali-linux-sources-list-repositories) explains what should the ```sources.list``` file look like.

**Comment by geegee456** [comment]
THANK YOU BLACK HAT MONKEY :DD I LOVE YOU 

I changed the sources.list file  as described in

And now i am able to make the updates,upgrades etc.  

After the updates etc i could use wifiphisher but only in live mode. Now the version on my hdd also works.  

Thank you again. I am noob noob in linux and stuff. Unbelievable i wasted hours and now you solved my problem thank you again to you all.

**Comment by geegee456** [comment]
I also can use my wifi adapter AWUS036NEH. If someone has the same problems update that shitty file and then apt-get update and apt-get upgrade and everything works :DD

**Comment by MrLowkey1818** [comment]
Thanks for your replies,  I got a little further with wifiphisher, the hostapd problem solved itself as soon as I gave up strangely. I am experiencing another problem with wifiphiser, I believe it is selecting a the worst wireless card out of the two. Here is what it returns to me:

[*] Starting the fake access point.  . .
[+] Driver initialization failed! (hostapd error)
[+] Try a different wireless interface using aI option.

I'm looking as we speak for a solution, my external wireless card also being used is a TL-WN823N.

 Thanks for your patience.

**Comment by MrLowkey1818** [comment]
Also both of my wireless cards get picked up by kali. Unless I'm supposed to disconnect from the internet before I attempt to create the fake access point I don't know what.

**Comment by blackHatMonkey** [comment]
Have you tried starting ```wifiphisher``` like fallowing:
```bash
sudo python wifiphisher.py -aI wlan0
```
You can choose whichever wireless card you think is the strongest.

**Comment by MrLowkey1818** [comment]
Extra: I reinstalled hostapd to make sure that was in order, reran the script and got the same output error message. Sorry for the excessive messages.

**Comment by MrLowkey1818** [comment]
Thank you I will try this, your message didn't load until I sent my last.

**Comment by n1kkilou** [comment]
i have the same problem please help
(https://user-images.githubusercontent.com/25098133/36071594-5831576c-0f4b-11e8-8d13-97ba45a351c7.png)

**Comment by usama7628674** [comment]
@n1kkilou Your GPG key is expired so to add it type these following commands 
wget -q -O - https://archive.kali.org/archive-key.asc | apt-key add
apt-get update
apt-get install hostpad
verify by typing hostapd in the terminal.

**Comment by n1kkilou** [comment]
@usama7628674 thanks a lot bro,

**Comment by n1kkilou** [comment]
after i install hostapd still the problem of wifiphisher remains
(https://user-images.githubusercontent.com/25098133/36072931-0cd046b2-0f63-11e8-8201-568916f000d4.png)

**Comment by usama7628674** [comment]
Your adapter doesn't support AP mode which is necessary to create access point.You can check it by typing
`iw phy phy0 info`

**Comment by landaranii** [comment]
i tried everything and i cant get rid of this error: 

`wifiphisher
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 27, in <module>
    import wifiphisher.common.accesspoint as accesspoint
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/accesspoint.py", line 7, in <module>
    from roguehostapd import hostapd_controller
ImportError: cannot import name hostapd_controller
`



by the way i am using Ubuntu 17.4

**Comment by anakin1028** [comment]
Hey please remove the wifiphisher, and git clone the one on the github. And build wifiphisher by `python setup.py install`

**Comment by landaranii** [comment]
wifiphisher
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 27, in <module>
    import wifiphisher.common.accesspoint as accesspoint
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/accesspoint.py", line 7, in <module>
    from roguehostapd import hostapd_controller
ImportError: cannot import name hostapd_controller

**Comment by landaranii** [comment]
i cant manage to uninstall wifiphisher when i try this command 
sudo apt remove wifiphisher
