### ISSUE TITLE
wifiphisher closes!

### ISSUE THREAD

**Issue by sinitchi00** [sophron/wifiphisher#21]
After scanning for wireless APs, I select the number that I would like to copy, but when I hit enter, it closes. How to solve this?? and second, why do we need 2 wireless interface?? I have an Alfa AWUS360H here.

**Comment by FurqanHanif** [comment]
#8 it's a Bug , i'm sure it will be fixed in a day or two.. 
it says two Wireless interfaces (Not Two Wireless Adapters ) So, i think two Wireless interfaces mean mon0 and mon1 ...

**Comment by sinitchi00** [comment]
okay, is there any video tutorial on how to use this tool yet??

**Comment by sophron** [comment]
Hi @sinitchi00,

You need 2 wireless cards for the script to work, one for jamming and one for the AP. If you are using two network cards and still running into an error, please open a new descriptive ticket.
