### ISSUE TITLE
Router update page

### ISSUE THREAD

**Issue by jamalala** [sophron/wifiphisher#211]
Hello, i have an problem. When i make a fake AP of my own AP and i connect to the fake AP it does not show the page where u must sign in with you wifipassword to get the "upgrade of the router", and when i got connected it saying Limited acces. So what did i do wrong, i use 2 wireless cards, the TPlink 722N and the Alfa AWUSO36NH. I know in the past it did work but i have installed it again and wanted to test again, but i do not get the page!!! pls help

**Comment by sophron** [comment]
Hello @jamalala,

I assume you are aware that in order for this to work the victim needs to open its browser and type a URL in the address bar. Then wifiphisher will redirect all requests to localhost and present the fake portal.

Can you please provide some more details? Which OS & browser are you using?  The <a href="https://github.com/sophron/wifiphisher/wiki/Bug-reporting-guidelines">Bug Reporting Guidelines</a> may help you.

**Comment by jamalala** [comment]
Yes, i know that you have to open a browser. When i open a browser it showing blank and keeps "thinking" after a while its showing "page cannot been found" the same as when you have no internet connexion. I use kali linux 2.0 with the wifiphisher on my pc. Then i go to my laptop that has windows 7 on it, with the laptop a make the connexion to the fake AP and use google chrome as the browser.

**Comment by blackHatMonkey** [comment]
Is there a specific website you are trying to open or this happens to all websites?
Also can you tell us which version of the ```wifiphisher``` you are using?

**Comment by jamalala** [comment]
no not specific website i i try to open google and marktplaats.nl just normal websites. this version of wifiphisher i use: wifiphisher-1.1

**Comment by sophron** [comment]
Try the latest revision. Download from <a href="https://github.com/sophron/wifiphisher/archive/master.zip">here</a>.

**Comment by jamalala** [comment]
i downloaded it and it works!!!!!!!!!!!!!!!! thank you very much for your help
