### ISSUE TITLE
Could not set IP address error

### ISSUE THREAD

**Issue by naflan121** [sophron/wifiphisher#215]
I am on Kali 2.0 and using two adapters (both can inject),when i run the script after selecting interface following error occurs 
[+] Choose the [num] of the scenario you wish to use: 1
[+] Selecting Browser Connection Reset template
[*] Starting the fake access point...
[+] Could not set IP address on wlan0!

[!] Closing

Any solution ?

**Comment by blackHatMonkey** [comment]
Hi @naflan121 
Can you check if you have ```dnsmasq``` installed. You can check by running:
```bash
dpkg -s dnsmasq
```
in the terminal and take a look at ```Status``` line. 

If it is not installed then you can install it by running:
```bash
sudo apt-get install dnsmasq
```
Let me know if you have any more problems.

**Comment by naflan121** [comment]
Thanks @blackHatMonkey 
 it help me to start the script but i cannot see the fake AP, from my mobile, Wifi phisher suppose to create a fake ap and jam the original right?

**Comment by blackHatMonkey** [comment]
You may want to try starting ```wifiphisher``` with the ```-aI``` argument:
```bash
sudo python wifiphisher.py -aI wlanx
```
where ```wlanx``` is the name of the adapter with ```AP``` mode available.

**Comment by naflan121** [comment]
this didnt help me im using 2 alfa AWUS036H any tips to start the fake ap?

**Comment by blackHatMonkey** [comment]
Unfortunately the ```AWUS036H``` doesn't support ```AP``` mode. That is the reason it can't create the access point. For ```wifiphisher``` to work you need to have at least one card with ```AP``` mode available. I personally use ```AWUS036H``` and ```AWUS036NHA```.

**Comment by sophron** [comment]
Hi @naflan121,

 This error is shown when the script fails to set an IP address on the specified interface. You can try manually setting an IP address and see why it's complaining. You can do so by running `ifconfig <ap_iface> up 10.0.0.1 netmask 255.255.255.0`, where <ap_iface> the access point interface that you specify with `-aI`.

**Comment by sophron** [comment]
Hi @naflan121,

Can you paste here the output of `/tmp/wifiphisher-hostapd.log` while running the script? You can do so by typing `cat /tmp/wifiphisher-hostapd.log`.

**Comment by naflan121** [comment]
@sophron I think it was my linux and now its fixed the only this i cannot do is cannot start fake ap im using 2 AWUS036H if this device don't support what are the compatible device can i have a list or any suggestions

**Comment by blackHatMonkey** [comment]
@naflan121 You can check our [FAQ](https://github.com/sophron/wifiphisher/wiki/Frequently-Asked-Questions-%28FAQ%29#what-are-some-effective-wireless-adapters-for-using-wifiphisher-) for some compatible network adapters.
