### ISSUE TITLE
Can not create false AP

### ISSUE THREAD

**Issue by caixiawang** [sophron/wifiphisher#217]
I want to get help

**Comment by caixiawang** [comment]
[+] Ctrl-C at any time to copy an access point from below
num  ch   ESSID
---------------
1  - 1  - CMCC-WEB
2  - 1  - and-Business
3  - 6  - jy111
4  - 6  - FAST_CA942C
^C
[+] Choose the [num] of the AP you wish to copy: 3
[*] Starting the fake access point...
[3;J













[*] jy111 set up on channel 6 via wlan0 on wlan1
[*] Monitor mode: wlan0 - 00:e0:6c:81:e5:80
[3;J





















Jamming devices: 









DHCP Leases: 








HTTP requests:

**Comment by caixiawang** [comment]
root@kali:~/wifiphisher-1.1# sudo python2 wifiphisher.py -jI wlan0
[*] Starting HTTP server at port 8080
[*] Starting HTTPS server at port 443
[+] Starting monitor mode off wlan0
[*] Cleared leases, started DHCP, set up iptables
[3;J
[+] Ctrl-C at any time to copy an access point from below
num  ch   ESSID
I inserted two wireless cards

**Comment by caixiawang** [comment]
root@kali:~# airmon-ng

PHY	Interface	Driver		Chipset

phy3	wlan0		rtl8187		Realtek Semiconductor Corp. RTL8187
phy2	wlan1		rt2800usb	Ralink Technology, Corp. RT2870/RT3070

This is my two NIC models do not know where there are problems

**Comment by sophron** [comment]
Sorry, I don't understand the issue you are describing. Consider following our <a href="https://github.com/sophron/wifiphisher/wiki/Bug-reporting-guidelines">bug reporting guidelines</a>.

**Comment by caixiawang** [comment]
I need to know two wireless adapters, look not to support wifiphisher-1.1
