### ISSUE TITLE
Router login pages based on vendor MAC

### ISSUE THREAD

**Issue by terrorbyte** [sophron/wifiphisher#22]
One thing that could improve effectiveness is to match the MAC address (BSSID) to the [IEEE OUI database](http://www.ieee.org/netstorage/standards/oui.txt) and build a couple of common router config pages that match common vendor styles. This way the victim (even if more tech savvy) may still be tricked by the fact that the router page looks similar to what it should.

**Comment by lokifer** [comment]
Already been suggested :) #5

**Comment by sophron** [comment]
Hi @terrorbyte,

As @lokifer stated, this has already been suggested. Thanks for contributing.
