### ISSUE TITLE
No such file or directory error after ESSID selection

### ISSUE THREAD

**Issue by SLiX-KAOS** [sophron/wifiphisher#220]
Hi all,

Used this tool before and it was great to use for testing, since my last use I upgraded to Kali 2016.1 woohoo! however I now receive the following error when trying to use the tool not sure where to start I am new to this and was wondering if anyone else knows how to rectify this.

![screenshot from 2016-03-09 21-23-26](https://cloud.githubusercontent.com/assets/10120471/13651062/89ac062c-e63d-11e5-86d4-b105c2991353.png)

and before any one asks the folders have templates in them so not sure where the issue is or if I have to edit the code to get it to correctly source the files.

Any help is appreciated.

**Comment by blackHatMonkey** [comment]
Hi @SLiX-KAOS 
Can you download a fresh copy from github and see if the problem still persist?

**Comment by SLiX-KAOS** [comment]
Hi blackhatMonkey,

I have tried a number of times and still get the same error.

I've also tried to download directly from source, same error occurs.

**Comment by blackHatMonkey** [comment]
Can you post a screenshot of the ```wifiphisher``` directory.

**Comment by SLiX-KAOS** [comment]
As requested

![screenshot from 2016-03-10 21-40-40](https://cloud.githubusercontent.com/assets/10120471/13685542/d7d5c7c2-e708-11e5-8394-34c210181315.png)

**Comment by sophron** [comment]
Hi @SLiX-KAOS,

Try changing your directory to the `wifiphisher` one and running the script as `python wifiphisher.py`.

**Comment by blackHatMonkey** [comment]
Since there were no response from OP, I'm going to close this issue. If you still have the same problem after upgrading to the latest version please feel free to open a new issue.
