### ISSUE TITLE
AP + Jam but no one go on my AP

### ISSUE THREAD

**Issue by majik2016** [sophron/wifiphisher#223]
Hello,

I need help i dont know what i can do

I jam many stationand i test by my own the phishing work but other station dont go on my wifi ap do i do something wrong or how to force them to connect to my AP...

Thanks

Let mr know

**Comment by majik2016** [comment]
![img_20160309_220601](https://cloud.githubusercontent.com/assets/17736083/13704088/19e21a26-e768-11e5-94ac-39198a5c4a08.jpg)

**Comment by sophron** [comment]
Read the <a href="https://github.com/sophron/wifiphisher/wiki/Frequently-Asked-Questions-%28FAQ%29#i-have-no-success-using-the-tool--nobody-is-connecting-to-the-rogue-ap-what-am-i-doing-wrong-">FAQ</a>.
