### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by nemanjampek** [sophron/wifiphisher#224]
I'm trying to install Wifiphisher but i get this error:
![screenshot from 2016-03-11 20-31-53](https://cloud.githubusercontent.com/assets/17790030/13715840/b0299a76-e7d7-11e5-9824-33ddf39047f7.png)
I don't know what to try.Some help,please.
Thanks

**Comment by blackHatMonkey** [comment]
Can you download the latest version and try again. Also it might be helpful to start the ```wifiphisher``` like fallowing:
```bash
sudo python wifiphisher.py
```

**Comment by djdisikd** [comment]
It is still not working

**Comment by djdisikd** [comment]
I have the same problem too.

**Comment by blackHatMonkey** [comment]
Are you running the latest version of ```wifiphisher```?
