### ISSUE TITLE
Driver initialization failed! (hostapd error)

### ISSUE THREAD

**Issue by caixiawang** [sophron/wifiphisher#226]
[+] Choose the [num] of the scenario you wish to use: 3
[+] Selecting Firmware Upgrade Page template
[*] Starting the fake access point...
[+] Driver initialization failed! (hostapd error)
[+] Try a different wireless interface using -aI option.

[!] Closing

**Comment by blackHatMonkey** [comment]
It would be better to continue the discussion in #221.
