### ISSUE TITLE
New Airmon-ng version.

### ISSUE THREAD

**Issue by xXRedHackingXx** [sophron/wifiphisher#227]
Now the monitor interface name is wlanXmon.
OLD: monX
New: wlanXmon

Wifiphisher is not working with new Aircrack version... please fix it as soon as possible...

With airmon start wlan0:
Old version, the monitor interface was mon0
With the new, is wlan0mon

**Comment by strasharo** [comment]
Or you can use this airmon in order to have the old behavior:
https://raw.githubusercontent.com/kernel-64/linset/master/airmon

**Comment by blackHatMonkey** [comment]
@xXRedHackingXx 
```wifiphisher``` only uses ```airmon check kill``` to stop any processes that might be problematic. Can you describe your problem in more details?

**Comment by sophron** [comment]
I'm also not seeing how this is affecting the script. @xXRedHackingXx, can you please explain in more detail?

**Comment by xXRedHackingXx** [comment]
I'm sorry, it was just a problem related to my computer, but i fixed it using old behavior (strasharo comment) Thanks to everyone :+1:
