### ISSUE TITLE
Wifiphisher problem

### ISSUE THREAD

**Issue by Pavlex4** [sophron/wifiphisher#228]
Driver initialization failed! (hostapd error)Try a different wireless interface using -aI option.
I am using  TP-Link TL-WN722N USB Wifi card and internal Atheros wireless card.How to fix this?????

**Comment by blackHatMonkey** [comment]
Hi @Pavlex4. Have a look at #221. All you have to do is to specify the ```-aI``` option like so:
```bash
sudo python wifiphisher.py -aI wlan0
```
You have to replace ```wlan0``` with the ```TP-Link TL-WN722N``` interface.
