### ISSUE TITLE
Network Unreachable error

### ISSUE THREAD

**Issue by shady-S** [sophron/wifiphisher#23]
I am not able to jam any ssid and when victim connects to that ssid, there is no phishing page whatsoever. Is there any step left? 
Following is the last scenario I can observe:

"[+] Choose the [num] of the AP you wish to copy: 11
SIOCADDRT: Network is unreachable
[*] Starting the fake access point... 

Jamming devices: 
[*] cc:c3:ea:3e:72:9d - dc:f1:10:7d:af:0b - 6  - XT1033 6820
[*] cc:c3:ea:3e:72:9d - 6  - XT1033 6820

DHCP Leases: 

HTTP requests: 

"

**Comment by FurqanHanif** [comment]
Network is Unreachable , Looks Like You'r Too Far From The AP..

**Comment by shady-S** [comment]
That's not the case since I am getting the error for my own router on which I am testing as well as every other in the range.

**Comment by denartha** [comment]
Are you definitely using two network interfaces? I got that error when i was trying to use just one.

**Comment by FurqanHanif** [comment]
Two Network Interface ??? Means i Need Two Network Adapters , Say one is Atheros Wifi Card and second is Tp-Link Wifi Card ???

**Comment by denartha** [comment]
Yes you need 2 network adapters. One of them needs to support injection, so probably the Atheros one.

**Comment by FurqanHanif** [comment]
And What other one do???

**Comment by denartha** [comment]
One is the jamming interface and one is the AP interface.

**Comment by FurqanHanif** [comment]
So it's Not possible to Do this With One Wifi Card Only??

**Comment by denartha** [comment]
Not that Im aware of.

**Comment by koluke** [comment]
See the [README](https://github.com/sophron/wifiphisher#requirements).  You need two network cards.

**Comment by sophron** [comment]
Hi @FurqanHanif,

Yes, you need two network cards for the script to work.

**Comment by shady-S** [comment]
Thanks everyone for the help now I got the point.

**Comment by faizlo** [comment]
are there laptops equipped with two wlan adapters!!!?

**Comment by denartha** [comment]
Custom builds probably. A regular one will need an additional one. I
recommend the Alfa awus360nh
