### ISSUE TITLE
Hostapd Problem

### ISSUE THREAD

**Issue by roko123** [sophron/wifiphisher#230]
i have problem whit hostapd and i hope some one Help me

![captureddd](https://cloud.githubusercontent.com/assets/18088428/14061038/9897083e-f36d-11e5-81e2-eac1b380931b.JPG)

**Comment by sophron** [comment]
The error message is self-explanatory. What exactly is your question?

**Comment by roko123** [comment]
hostapd dosnt install

**Comment by sophron** [comment]
The script outputs some suggestions for your problem. Have you tried that? 

If you still encounter issues, you should reach <a href="https://forums.kali.org/">Kali Linux forums</a>.
