### ISSUE TITLE
Cannot install hostapd on my kali linux 2.0

### ISSUE THREAD

**Issue by jaganibrijesh** [sophron/wifiphisher#234]
root@hacker:~# apt-get install hostapd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package hostapd is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'hostapd' has no installation candidate

**Comment by sophron** [comment]
You should ask <a href="https://forums.kali.org/">here</a>.
