### ISSUE TITLE
UnboundLocalError at startup

### ISSUE THREAD

**Issue by naflan121** [sophron/wifiphisher#235]
**Version:**
cb534b081d8e9382cea6eb98e1960ae3e3505524

**Distribution:**
Kali Linux

**Summary:**
```wifiphihser``` fails to start and throws an error

**Description:**
This bug is related to the ```interfaces``` module where ```wifiphisher``` fails to check for interface compatibility. Also the cards used are TL-WN722N and Alfa AWUS036H.

**Steps to Reproduce:**
Running 
```bash
python bin/wifiphisher
```
**Expected VS actual behavior:**
```wifiphisher``` starting without any errors and correctly chooses the correct interfaces for jamming and AP creation

**Script output:**
![wifiphisher2](https://cloud.githubusercontent.com/assets/11876070/14430492/5fa80900-0034-11e6-966e-8a1542ab2f30.PNG)

EDIT: edited by @blackHatmonkey to add all the necessary information.

**Comment by naflan121** [comment]
@blackHatMonkey @sophron any help me out?

**Comment by blackHatMonkey** [comment]
@naflan121 would you be able to connect to our IRC channel to discuss this bug?
IRC channel #wifiphisher (irc.freenode.net)

**Comment by blackHatMonkey** [comment]
After a lot of debugging, thanks to, @naflan121, the problem is related to ```ifconfig``` version. This problem applies to all the machines who have a higher version of ```1.6```(```ifconfig > 1.6```).

**Comment by blackHatMonkey** [comment]
This must be fixed before ```v2```. An alternative must be found that does not rely on ```net-tools``` to find the interfaces.

**Comment by sophron** [comment]
@blackHatMonkey Can you explain in more detail what exactly is the problem? What about `ip a`?

**Comment by blackHatMonkey** [comment]
The problem was that we were unable to get the correct interface name. i.e. ```wlan0``` in ```v1.6``` would get ```wlan0:``` in ```v2.1``` which is due to change in the way ```ifconfig``` displays items. The software runs correctly after changing ```ifconfig``` version to ```1.6```.

**Comment by sophron** [comment]
The script can determine the version of `ifconfig` and retrieve the interfaces accordingly <a href="https://github.com/sophron/wifiphisher/blob/master/wifiphisher/interfaces.py#L520">when needed</a>. 

Also, note that the proper way to extract the interfaces from the `ifconfig` output (or from any text output) is by using regular expressions.

**Comment by blackHatMonkey** [comment]
Instead of using ```ifconfig``` at all I was thinking of using ```socket``` module like this [example](https://code.activestate.com/recipes/439093-get-names-of-all-up-network-interfaces-linux-only/).

**Comment by vincentmoglia** [comment]
Same error for me. I have the last version of Kali Linux.

**Comment by blackHatMonkey** [comment]
@vincentmoglia A new patch will shortly be pushed the repository that will fix this issue.

**Comment by vincentmoglia** [comment]
@blackHatMonkey Thanks a lot !

**Comment by blackHatMonkey** [comment]
The issue should be solved now.

**Comment by vincentmoglia** [comment]
It works fine for me now ! Thanks a lot !

**Comment by jsl303** [comment]
I just cloned the git, but I get this same error. Latest Kali.

**Comment by blackHatMonkey** [comment]
Can you replace ```interfaces.py``` with [this](http://pastebin.com/qMvfwqPy) version. Then run
```bash
python bin/wifiphisher
```
And post the output please.
