### ISSUE TITLE
DHCP Leases

### ISSUE THREAD

**Issue by michaelvs** [sophron/wifiphisher#24]
After running the following command <code>python wifiphisher.py -a XX:XX:XX:XX -c X -jI wlan0 -aI wlan0 </code>

DHCP Leases dont "load" and they loop infinite.

(It is mentioned in other issues but not as the main issue,so i want to gather all possible solutions about this specific problem here)

-Running Kali Linux

**Comment by ctrc00** [comment]
I think what is wrong is "-jI wlan0 -aI wlan0" 
You cannot have both jamminginterface and apinterface on the same interface "wlan0".

See https://github.com/sophron/wifiphisher/issues/31

**Comment by sandman6578** [comment]
Yes thats right you need TWO #ADAPTERS# not interfaces and the same interface for both attacks will not work at all

**Comment by michaelvs** [comment]
Ok thanks for your replies! 
I thought i should have 2 interfaces.
