### ISSUE TITLE
Add test cases for interfaces module

### ISSUE THREAD

**Issue by blackHatMonkey** [sophron/wifiphisher#245]
Add proper test cases for interfaces module.

**Comment by wraith-wireless** [comment]
Please take a look at my project at https://github.com/wraith-wireless/pyric. I wrote it for another program I'm working - I was having the same problems you are. From Python command line or programmatically you can bring a card up/down, channel set/get, get chipset/driver, list interfaces and wireless interfaces, get/set hw address, get device info, add/delete interfaces and enumerate supported modes of a card without have to rely on subprocess.Popen, reg. expressions and/or str.find. ATT, there's no setup.py, but as long as you put it on your Python path, setup is easy as It's self-reliant with no third party components needed, only Python builitins.

**Comment by sophron** [comment]
@wraith-wireless Thanks for suggesting this. I will have a closer look shortly but from a quick glance it looks to be exactly what we need. In which project are you currently using it?

**Comment by wraith-wireless** [comment]
I putting in my Wraith project, it's a scanner - have to go and update it now. Prior to that I was using Popen to put cards in monitor and change the channels.

**Comment by sophron** [comment]
Continue of the discussion about `PyRIC` in #254.
