### ISSUE TITLE
wifiphisher not creating fake AP

### ISSUE THREAD

**Issue by jemsbond** [sophron/wifiphisher#246]
I am using 2 wireless adapter and Wifiphisher-1.1. in external adapter i m using TP-WIN822N(is it ok for external adapter?).
i can jam any AP But it is not creating Fake AP. 
how to solve this problem??
![screenshot from 2016-04-17 21 23 10](https://cloud.githubusercontent.com/assets/15816485/14588285/01e04dce-04e3-11e6-9e1f-f70af5b4b329.png)

**Comment by blackHatMonkey** [comment]
Have you tried using the latest version?

**Comment by jemsbond** [comment]
ya i m using wifiphisher 1.1

**Comment by blackHatMonkey** [comment]
Can you try using [this](https://github.com/sophron/wifiphisher/archive/master.zip) version and see if the problem is still exists.

**Comment by jemsbond** [comment]
thanks bro it's working but in andriod mobile it's not showing phishing page. can u solve this problem

**Comment by blackHatMonkey** [comment]
You need to connect from a different device than the one you are running ```wifiphisher``` from.

**Comment by jemsbond** [comment]
Hey bro in this version sometimes wifiphisher not jamming single and its not working in mobile device u have to improved that thing

**Comment by jemsbond** [comment]
![gg](https://cloud.githubusercontent.com/assets/15816485/14641314/3fe7c24c-0663-11e6-8d5e-45c883d685ed.png)

**Comment by blackHatMonkey** [comment]
The tool is still in progress and will get much better in the future.
