### ISSUE TITLE
Web page not accessible from client browser

### ISSUE THREAD

**Issue by naflan121** [sophron/wifiphisher#247]
Hi @blackHatMonkey @sophron 

The tool working perfectly without any operation errors, when the evil ap is started. If the victim join via a Iphone the captive portal popup and show the fake pages accordingly , if the victim is on android or a PC the ap allow them to connect while browsing captive portal doesn't start. "ERR_CONNECTION_FAILD". 
_PS: I hacked into 1 connection and the client was using iphone_

**Comment by jemsbond** [comment]
Can u check in andriod it's lodding phishing page??

**Comment by naflan121** [comment]
nop that what i mean to when ever user request a webpage from browser it gives "ERR_CONNECTION_FAILD".

**Comment by sophron** [comment]
@naflan121 From some googling I did, I realize that "ERR_CONNECTION_FAILD" is an issue with other software installed on the machine messing with the network stack. This doesn't look like a problem on the tool's side.

**Comment by naflan121** [comment]
@sophron so how this will be the same for all the mobile devices i have tried... and working on I devices and android and PC don't.. The machine you are referring to the hosted or victim?

**Comment by blackHatMonkey** [comment]
@naflan121 
The only time that I ever got ```ERR_CONNECTION_FAILD``` was when Kali froze. So I was still connected but no page would load. Also what I think @sophron  is refereeing to is the hosted machine (```Kali Linux```).

**Comment by naflan121** [comment]
@blackHatMonkey

no event though the kali is stable still other devices can connect to the fake ap but the phishing page wont show up on popup or while browsing, but if the device is an iphone once the user try to connect the phishing page will popup

**Comment by blackHatMonkey** [comment]
Let's continue the discussion  in #266.
