### ISSUE TITLE
Duplicate of #234

### ISSUE THREAD

**Issue by hamzamohammad1997** [sophron/wifiphisher#249]
when i open the file nothing happen so is there anyone has a solution for this ???
![screenshot from 2016-04-23 21-28-02](https://cloud.githubusercontent.com/assets/18633909/14763306/2b4e4a38-0981-11e6-913c-0a19ec4924ca.png)

**Comment by blackHatMonkey** [comment]
You need to go up one directory so in you case it would be
```bash
/home/fuckenroot/Desktop/wifiphisher
```
and then run
```bash
python bin/wifiphisher
```

**Comment by hamzamohammad1997** [comment]
what about this "  can't find the packege "

![screenshot from 2016-04-24 17-41-32](https://cloud.githubusercontent.com/assets/18633909/14769226/04563bde-0a44-11e6-90cc-42f9e7551c6d.png)

**Comment by blackHatMonkey** [comment]
Instructions are pretty clear. You need to install ```hostapd``` package and all you have to do is follow the instructions given in the error message.

**Comment by hamzamohammad1997** [comment]
I can't find the package so if u can give me the other source coz it can't find it in the normal source

**Comment by blackHatMonkey** [comment]
Read the Kali Rolling repository section [here](http://docs.kali.org/general-use/kali-linux-sources-list-repositories).
