### ISSUE TITLE
Driver initialization failed

### ISSUE THREAD

**Issue by whitecjohn** [sophron/wifiphisher#251]
**interfaces:**
```bash
root@kali:~# airmon-ng

PHY	Interface	Driver		Chipset

phy0	wlan0		rtl8187		Realtek Semiconductor Corp. RTL8187
phy1	wlan1		iwlwifi		Intel Corporation Centrino Ultimate-N 6300 (rev 3e)
```
I used an ```ALPHA AWUS036H```

**Script output:**
```bash
root@kali:~/wifiphisher# sudo python bin/wifiphisher
               _  __ _       _     _     _               
              (_)/ _(_)     | |   (_)   | |              
     __      ___| |_ _ _ __ | |__  _ ___| |__   ___ _ __ 
     \ \ /\ / / |  _| | '_ \| '_ \| / __| '_ \ / _ \ '__|
      \ V  V /| | | | | |_) | | | | \__ \ | | |  __/ |   
       \_/\_/ |_|_| |_| .__/|_| |_|_|___/_| |_|\___|_|   
                      | |                                
                      |_|                                
                                                         
[*] hostapd not found in /usr/sbin/hostapd, install now? [y/n] y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  hostapd
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 589 kB of archives.
After this operation, 1,564 kB of additional disk space will be used.
Get:1 http://ftp.halifax.rwth-aachen.de/kali kali-rolling/main i386 hostapd i386 1:2.3-2.3 [589 kB]
Fetched 589 kB in 1s (369 kB/s)  
Selecting previously unselected package hostapd.
(Reading database ... 299134 files and directories currently installed.)
Preparing to unpack .../hostapd_1%3a2.3-2.3_i386.deb ...
Unpacking hostapd (1:2.3-2.3) ...
Processing triggers for systemd (228-4) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up hostapd (1:2.3-2.3) ...
update-rc.d: We have no instructions for the hostapd init script.
update-rc.d: It looks like a network service, we disable it.
insserv: warning: current start runlevel(s) (empty) of script `hostapd' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `hostapd' overrides LSB defaults (0 1 6).
Processing triggers for systemd (228-4) ...
[!] We have failed to find a wireless interface which supports AP mode. Please make sure that all the wireless adapters are connected and they are compatible.

[!] Closing
```

What am i doing wrong?

EDITED: @blackhatmonkey for clarity

**Comment by whitecjohn** [comment]
+] Choose the [num] of the scenario you wish to use: 3
[+] Selecting Firmware Upgrade Page template
[*] Starting the fake access point...
[+] Driver initialization failed! (hostapd error)
[+] Try a different wireless interface using -aI option.

Update 

please let me know how to fix hostapd error

**Comment by whitecjohn** [comment]
i use alpha awus 036H chipset RTL8187

**Comment by blackHatMonkey** [comment]
Does your other card support ```AP``` mode?

**Comment by whitecjohn** [comment]
i try with them and without them.....i dont know why show me that error with AP mode not supported...

i olso download the second version from 010010001/wifiphisher and the other version let me run the program and when try to broadcast it show me :

+] Choose the [num] of the scenario you wish to use: 3
[+] Selecting Firmware Upgrade Page template
[*] Starting the fake access point...
[+] Driver initialization failed! (hostapd error)
[+] Try a different wireless interface using -aI option.

Update

**Comment by blackHatMonkey** [comment]
You can try this to debug the problem:

1.  In the terminal navigate to ```/tmp``` folder
2.  After that in a separate terminal window run ```wifiphisher``` (newest version)
3.  As soon as you see ```[*] Starting the fake access point...```, in first terminal run
```bash
cat hostapd.conf
```
And post the output of that here.

**Comment by whitecjohn** [comment]
root@kali:~# airmon-ng

PHY	Interface	Driver		Chipset

phy0	wlan0		rtl8187		Realtek Semiconductor Corp. RTL8187
phy1	wlan1		rtl8187		Realtek Semiconductor Corp. RTL8187
phy2	wlan2		iwlwifi		Intel Corporation Centrino Ultimate-N 6300 (rev 3e)


root@kali:~# cd /tmp
root@kali:/tmp# cat hostapd.conf
interface=wlan2
driver=nl80211
ssid=WLAN-1A9E01
hw_mode=g
channel=1
macaddr_acl=0
ignore_broadcast_ssid=0

i attached the second alfa awus036h  and the same error


[+] Choose the [num] of the scenario you wish to use: 3
[+] Selecting Firmware Upgrade Page template
[*] Starting the fake access point...
[+] Driver initialization failed! (hostapd error)
[+] Try a different wireless interface using -aI option.

**Comment by blackHatMonkey** [comment]
My apologizes can you try the same but check ```wifiphisher-hostapd.log``` file.

**Comment by whitecjohn** [comment]
root@kali:~# cat wifiphisher-hostapd.log
cat: wifiphisher-hostapd.log: No such file or directory

**Comment by sophron** [comment]
I think @blackHatMonkey meant to say `/tmp/wifiphisher-hostapd.log`.

**Comment by whitecjohn** [comment]
`root@kali:~# cat /tmp/wifiphisher-hostapd.log`
`Configuration file: /tmp/hostapd.conf`
`nl80211: Could not configure driver mode`
`nl80211 driver initialization failed.`
`hostapd_free_hapd_data: Interface wlan1 wasn't started`

**Comment by whitecjohn** [comment]
i have to install hostapd manually or what?

thanx for youre interest

**Comment by Ezat** [comment]
Hello!
Try this: (step-by-step)
1-Unplug all the devices from your PC 
2-Fire up Kali
3-Replug all devices(Attention: Don't attach)
4-In the terminal:
`service network-manager stop` (multiple times)
5-Now attach them to Kali
6-Again in the terminal:
`service network-manager stop` (multiple times)
7-Now for the last step run:
`python wifiphisher -aI wlan1 -jI wlan0`

**Comment by whitecjohn** [comment]
thanx Ezat but still the same error,but i think the problem is in hostapd  so i try to see  if my card support hostapd with next commands and it show this:

`root@kali:~# lspci -k | grep -A 3 -i "network"
00:19.0 Ethernet controller: Intel Corporation 82579LM Gigabit Network Connection (rev 04)
	Subsystem: Hewlett-Packard Company 82579LM Gigabit Network Connection
	Kernel driver in use: e1000e
	Kernel modules: e1000e
00:1a.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2 (rev 04)
--
24:00.0 Network controller: Intel Corporation Centrino Ultimate-N 6300 (rev 3e)
	DeviceName: WLAN
	Subsystem: Intel Corporation Centrino Ultimate-N 6300 3x3 AGN
	Kernel driver in use: iwlwifi
root@kali:~# modinfo iwlwifi | grep 'depend'
depends:        cfg80211
`
i don't know how to disable the built in wifi card and enable the 2 alpha awus036h

**Comment by blackHatMonkey** [comment]
A new update has been pushed so please download the latest version and try again.

**Comment by whitecjohn** [comment]
you mean wifiphisher?couse i try 20 min ago the one from sophron and the one from 01001001

**Comment by whitecjohn** [comment]
or hostapd?

**Comment by whitecjohn** [comment]
Still the same error

**Comment by blackHatMonkey** [comment]
@whitecjohn 
You can try testing your cards with `hostapd` before running `wifiphisher`. You can achieve this by creating a configuration file with the following content
```
interface=PUT YOUR WIRELESS INTERFACE HERE (ex. wlan0)
driver=nl80211
ssid=WLAN-1A9E01
hw_mode=g
channel=1
macaddr_acl=0
ignore_broadcast_ssid=0
```
which you can save as `test.conf`. Remember to change `interface` before copying.:smile:

Then you can run 
```bash
sudo hostapd test.conf -d
```
And then check the result.

**Comment by blackHatMonkey** [comment]
Since this problem is not related to `wifiphisher` I'm going to close this thread.
