### ISSUE TITLE
Duplicate of #243

### ISSUE THREAD

**Issue by nebula1999** [sophron/wifiphisher#253]
**Version:**
aa86d61f564c740ac18da18b8c84951b8990dce1

**Distribution:**
kali 2016.1

**Description:**
Encountered the error after forcefully stopping the program and re-running it again.

**Steps to Reproduce:**
1. git clone https://github.com/sophron/wifiphisher
2. no hostapd. install y
3. target bssid
4. nothing. error flashes across screen.
5. ctl+c spits out error

**Expected VS actual behavior:**
The tool is supposed to ask for an AP to attack

**Script output:**
```
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wlan1 interface for creating the rogue access point
[!] We're sorry. An error has been detected after executing _ifconfig_cmd method. 
If this is the first time you have encountered this error you can try again. 
Otherwise please report this error so we can fix it.
SIOCSIFFLAGS: Operation not possible due to RF-kill
```

**Comment by blackHatMonkey** [comment]
@nebula1999 
Please update your original post with information in each section and plese post the full error message that you got.

**Comment by nebula1999** [comment]
commit aa86d61f564c740ac18da18b8c84951b8990dce1
kali 2016.1
1. git clone https://github.com/sophron/wifiphisher
2. no hostapd.  install y
3. target bssid
4.nothing.  error flashes across screen.
5. ctl+c spits out error
When try to run again this message:
+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wlan1 interface for creating the rogue access point
[!] We're sorry. An error has been detected after executing _ifconfig_cmd method. If this is the first time you have encountered this error you can try again. Otherwise please report this error so we can fix it.
SIOCSIFFLAGS: Operation not possible due to RF-kill

**Comment by blackHatMonkey** [comment]
Please take a look at #243 specifically this [comment](https://github.com/sophron/wifiphisher/issues/243#issuecomment-210811450). That should solve the problem you are experiencing.
