### ISSUE TITLE
Implement PyRIC in interfaces module

### ISSUE THREAD

**Issue by sophron** [sophron/wifiphisher#254]
We should consider leveraging <a href="https://github.com/wraith-wireless/pyric">PyRIC</a>. If we see that it's suitable for our needs, we will have to change methods such as `_ifconfig_cmd`, `set_interface_mode`, `_iw_cmd` (in our `interfaces.py`) that are currently retrieving information using regex or find, and replace them with the methods defined in <a href="https://github.com/wraith-wireless/pyric/blob/master/pyw.py">pyw.py</a> file of PyRIC.

**Comment by blackHatMonkey** [comment]
@sophron 
After a bit of testing ```PyRIC``` project is unusable at it's current sate. I filled an issue and will try again after a fix has been pushed.

**Comment by blackHatMonkey** [comment]
This has been implemented in #262.
