### ISSUE TITLE
NETWORK IS DOWN

### ISSUE THREAD

**Issue by TheDjazairi** [sophron/wifiphisher#259]
Hi Team ! 

I'm using kali Linux on my machine. 

i have an issue with using wifiphisher. 

On the second screenshot it seems to make a loop or something like that .. 

I'm not understanding why .. i'm not sure that it's from my fault . 

When i press ctrl + c i have the error message on the third screenshot 

If you need more informations please ask me 

thank's a lot team !! :)

 
**Script output**: Paste the output of the tool, including any stack traces.
![capture d ecran de 2016-05-11 20-17-33](https://cloud.githubusercontent.com/assets/19312240/15191844/d2b483d0-17b6-11e6-98a1-ccd95906c9dc.png)
![capture d ecran de 2016-05-11 20-17-42](https://cloud.githubusercontent.com/assets/19312240/15191850/d719bd0a-17b6-11e6-94dd-420dde35d465.png)
![capture d ecran de 2016-05-11 20-20-25](https://cloud.githubusercontent.com/assets/19312240/15191851/d8d64dde-17b6-11e6-82f9-5e98cda7175f.png)

**Comment by TheDjazairi** [comment]
here my airmon-ng :

phy0	wlan0		iwlwifi		Intel Corporation Centrino Advanced-N 6205 [Taylor Peak] (rev 96)
phy1	wlan1		rtl8187		Realtek Semiconductor Corp. RTL8187

**Comment by TheDjazairi** [comment]
Ffor your information, 

I have tested that on a machine using windows XP where it was not working .. 

I have tested on an iphone i have the password now but i still have the error message just after

**Comment by blackHatMonkey** [comment]
Hi @TheDjazairi 
From what I can see the tool is working properly except the last screen shot were the bug is already reported (#242).

Regarding the problem with `Windows XP` we need more information.
1. Were you able to connect to the rouge AP?
2. Did the web page load?

**Comment by TheDjazairi** [comment]
Yes your'e right i have already seen this error message (#242) ..

With the test laptop using XP, something strange happened .. when the "attack " was launched from my computer i seen that the target was disconnected to the WIFI .. and maybe 2 minuts later the laptop alternated between connected and disconnected . 

The webpage did not load ..

**Comment by blackHatMonkey** [comment]
What you have to keep in mind is that `wifiphisher` doesn't force target to connect to it. What it means that the choice to connect to the `rouge AP` is always made by the user and unless the user specifically connects to the `rouge AP` it's not going to show them the page.

**Comment by TheDjazairi** [comment]
Okkk got it ! :)

Hm i will try at home .. But if the network is already registered on the target's computer i think that he will connect directly to the right network and not mine right ? 

Envoyé de mon iPhone

**Comment by blackHatMonkey** [comment]
If the `original AP` and `rouge AP` are both registered then it depends on the network manger but if it is only `rouge AP` then it should connect to it automatically.

**Comment by TheDjazairi** [comment]
![capture d ecran de 2016-05-13 01-01-34](https://cloud.githubusercontent.com/assets/19312240/15233125/55b02100-18a6-11e6-8799-ff766cdb35b2.png)

Hm something strange ........ i have this error message now :(

**Comment by blackHatMonkey** [comment]
Please note that you are not using the latest version of `wifiphisher`. You can download the latest version from [here](https://github.com/sophron/wifiphisher/archive/master.zip). Try again with the latest version and see if it fixes the issue.
