### ISSUE TITLE
Add an Authors file

### ISSUE THREAD

**Issue by yasoob** [sophron/wifiphisher#26]
Add an Authors/Contributors file listing the names of all the contributors. This would encourage more people to contribute to this software. I know that from experience. What do you guys say?

**Comment by sandman6578** [comment]
yes thats god idea

**Comment by sophron** [comment]
Hi guys,

This is indeed a nice to way to attract contributors. Although, we need to have a more stable community to include a file like this. 

For now, anyone can check the contributors <a href="https://github.com/sophron/wifiphisher/graphs/contributors">here</a>.

**Comment by sophron** [comment]
I'm closing this for now. We can consider adding an AUTHORS file at a later point.
