### ISSUE TITLE
Template that mimics network managers' behaviour

### ISSUE THREAD

**Issue by sophron** [sophron/wifiphisher#263]
Our most popular template so far is `firmware-upgrade` that is able to grab the PSK of a WPA/WPA2 network from unsuspected users.

We can take this one step further with a new template that imitates the behavior of the operating system. Specifically, this new template will:

1) Show the "Connection Failed" page. This is the default page a browser displays when there is no Internet connectivity. We can customize this accordingly based on the `User-Agent` header (we do something similar in the `connection-reset` scenario).  The purpose is to convince the victim that he is not really connected to a network. For example what we should display for a Chrome user:

<img src="http://wind8apps.com/wp-content/uploads/2014/10/DNS-PROBE-FINISHED-NO-INTERNET-issue-on-Windows-8-and-Windows-10.png">

2) Display a network manager window through our page. Again, we can make an accurate guess of the victim's network manager, based on the `User-Agent` header. This should be very realistic so that the victim can be confident enough that this box is actually displayed by his OS. We can also fill the box with the nearby networks (we are getting those by the beacon frames in the AP selection phase). For example, if the user is using Windows 10, we should display something like this:

<img src="https://www.ucl.ac.uk/isd/how-to/wifi-networks/images/win10-2-connect-eduroam-.png">

The victim will assume that he has no Internet connectivity due to (1), and will try to connect to his network but most likely will use our "fake network manager window" (2). Wifiphisher will then grab the PSK and shutdown as usual.

Anyone with good HTML, CSS, JS and web design skills can work on this one. The challenge here is to display the network manager window as realistic as possible.

This idea was proposed by Stergios Kolios.

**Comment by blackHatMonkey** [comment]
This is an interesting idea however I don't think it will work out nicely and that is because of the network manager. The user will expect it to open above the toolbar however it is going to open in the browser and I think this will be really noticeable especially if the browser is not full screen.

**Comment by sophron** [comment]
If the browser is on full-screen, we are able to display the fake network manager above the toolbar, right? We can possibly enforce the browser to be full-screen with Javascript.

Furthermore, I think you are thinking of Windows only. Linux or Mac OS network managers (that are usually using popup box at this point) can also be replicated.

**Comment by blackHatMonkey** [comment]
This is being worked on #273.

**Comment by sophron** [comment]
I continued the work of @dionyziz and merged the code for the new template a few days ago. The page is making a guess of the victim's network manager, based on the received User-Agent header and displays either the Windows or MAC OS network manager. Using our template language, the web-based network manager will prompt for the pre-shared key of the target network. Furthermore, the Windows network manager will display the nearby ESSIDs as well. 

 I consider this issue closed. However, there is of course much room for improvement for anyone willing to make this template more effective:

1) We should integrate more web based network managers (e.g. for Android or iOS).

2) Currently, we always display Chrome's "Connection Failed" page. We should display the page from other major browsers based on the User-Agent header.
