### ISSUE TITLE
Issue On Lunching captive portal 

### ISSUE THREAD

**Issue by naflan121** [sophron/wifiphisher#266]
Hi @sophron @blackHatMonkey 

When ever the attack started and fake ap is created. 
If the client is a iphone user the captive portal will pop up once he connect to the fake ap and ask to enter the wifi key 
But if the user on android or Windows, the fake ap connects and no popup is appeared, even though user try to browse on the device it keep on telling "internet connection is required"

i have tested on all the device but only ios does the job 
Any possible solutions?

**Comment by naflan121** [comment]
#255

**Comment by sophron** [comment]
I think the problem lies somewhere in the `dnsmasq` configuration. I'm not sure if it's resolving everything to localhost as it should be. I'll do some tests soon enough.

**Comment by naflan121** [comment]
ok

**Comment by blackHatMonkey** [comment]
@sophron 
While I was doing some testing in `phishinghttp` module I also encountered an interesting bug. It seems that the server stops receiving the requests and therefore browser hangs and you get the `ERR_CONNECTION_FAILD` error. This seems to be triggered by connecting two devices or refreshing the browser multiple times right after each other.

Here is the log of hostapd:
```
Configuration file: /tmp/hostapd.conf
Using interface wlan0 with hwaddr 00:c0:ca:6d:a2:a4 and ssid "Home"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED 
wlan0: STA 34:23:ba:f4:9e:c2 IEEE 802.11: authenticated
wlan0: STA 34:23:ba:f4:9e:c2 IEEE 802.11: associated (aid 1)
wlan0: AP-STA-CONNECTED 34:23:ba:f4:9e:c2
wlan0: STA 34:23:ba:f4:9e:c2 RADIUS: starting accounting session 573F5AA3-00000000
wlan0: STA 10:bf:48:f3:92:37 IEEE 802.11: authenticated
wlan0: STA 10:bf:48:f3:92:37 IEEE 802.11: associated (aid 2)
wlan0: AP-STA-CONNECTED 10:bf:48:f3:92:37
wlan0: STA 10:bf:48:f3:92:37 RADIUS: starting accounting session 573F5AA3-00000001
wlan0: AP-STA-DISCONNECTED 34:23:ba:f4:9e:c2
wlan0: STA 34:23:ba:f4:9e:c2 IEEE 802.11: disassociated
wlan0: STA 34:23:ba:f4:9e:c2 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
```
As of now I'm not sure it is the `hostapd` or the `web server` that is causing this issue. I will do more testing and report back.

**Comment by NasirJAKI** [comment]
@sophron 
yes bro its the same stuation , Is there any cure for this problem؟

**Comment by NasirJAKI** [comment]
@sophron 
if you still working on the solution, please give me another way for hacking wpa/wpa2 psk

**Comment by sophron** [comment]
Guys, we pushed a commit that may fix this. Let us know how it works for you.

**Comment by NasirJAKI** [comment]
@sophron
Where is the solution? Bro
You make me Enthusiastic

**Comment by sophron** [comment]
@naflan121 Is this working for you now?

**Comment by Crossik9** [comment]
Update?
