### ISSUE TITLE
UNFONCTIONNAL AGAINST A COMPUTER

### ISSUE THREAD

**Issue by TheDjazairi** [sophron/wifiphisher#267]
Hi team,

I'm experiencing something strange with wifiphisher .. it seems to work with an iphone connected to my proper network, but nothing appears when i try to use wifiphisher against my test computer connected to the same network. 

Using my iphone i can see the network disconnected etc .. but on the computer nothing appears .. 

I'm not sure to be clear, if you have more question send me an e-mail 

For information, i'm using wifiphisher with kali linux . 

thank's a lot

**Comment by naflan121** [comment]
same issue i am facing off.. Cannot predict what the problem exactly hope @sophron or @blackHatMonkey will help out to solve this

**Comment by TheDjazairi** [comment]
Yes it's very strange ..

**Comment by jezda** [comment]
Solution?

**Comment by sophron** [comment]
I suppose you are referring to de-authenticating stations from the target AP. Let's continue this at #302
