### ISSUE TITLE
Template configuration

### ISSUE THREAD

**Issue by sophron** [sophron/wifiphisher#269]
We need a mechanism that will allow the user to configure the running template. For example, for the OAuth template (#268) the user should be able to set the social networks that he wishes to target.  

The same mechanism will also bridge any information from the wireless spectrum to the template. For example, now that we are getting the router vendor of the target AP, we can fill the firmware upgrade template with valid information.

The implementation should be based on a new module (called templateconfig maybe?). The user should be able to configure the templates easily by modifying a plain config file. We will have to leverage a <a href="https://wiki.python.org/moin/Templating#Templating_Engines">template engine</a> for filling the template with information on the runtime.

**Comment by blackHatMonkey** [comment]
This has been implemented in #285.
