### ISSUE TITLE
Correct details about tool, deauth doesn't work

### ISSUE THREAD

**Issue by oscalation** [sophron/wifiphisher#27]
Correct me if I'm wrong, but the major OS's don't just switch you over to similarly named wireless hotspots. You might be able to deauth the legitimate AP, but the user has to manually go into their wireless settings and choose the new evil twin. The amount of users I've found that fall for this is low.

**Comment by michaelvs** [comment]
No.This tool doesn't automatically connect to the other network.You steal the password and then you are able to login to this.

**Comment by oscalation** [comment]
No, I'm saying the docs lead someone to believe the tool connects the victim automatic to the evil twin. It doesn't, and won't. The victim has to change their wireless settings and click on the new ap, right?

**Comment by oscalation** [comment]
You can't steel the password if the user doesn't change their wireless settings

**Comment by michaelvs** [comment]
I haven't yet successfully ran the script but from what i read i undesrtood that it jams the wifi's in range so the victim has no other option but to chose "our" ap

**Comment by oscalation** [comment]
That isn't the case, and never will be because of how major os's manage wireless connections

**Comment by michaelvs** [comment]
I don't know that for sure so if someone else can answer this

**Comment by justforyouNL** [comment]
The whole point is that u Deauthenticate the legitimate users. So they can't connect to there own wifi and will choose for the similar one from there local wifi neigberhood.

One thing i did notice is it's a open network also. It doesn't take the same encryption. (wpa/wpa2/wep)

**Comment by shady-S** [comment]
The deauth doesnt work properly as the victim connected to an AP dont get disconnected. If victim manually choose to select the fake AP also then the AP cannot be connected and no fake page is obtained.

**Comment by SamoBazz** [comment]
Hi ... How i can select wich interface to injection .. ?! and how i can knew if my wireliss support it !

**Comment by justforyouNL** [comment]
Python wifiphisher.py -jI wlan1

u need to check the kali supported wireless list, look at here for some.

http://www.wirelesshack.org/backtrack-compatible-adapters

**Comment by sophron** [comment]
Hi @oscalation,

Which exact part in the README do you find wrong?

**Comment by oscalation** [comment]
"Victim joins a rogue access point. Wifiphisher sniffs the area and copies the target access point's settings. It then creates a rogue wireless access point that is modeled on the target. It also sets up a NAT/DHCP server and forwards the right ports. Consequently, because of the jamming, clients will start connecting to the rogue access point. After this phase, the victim is MiTMed."

Lets clarify - The only thing that can be duplicated with regards to wpa/wpa2 is the SSID. The password is unknown.  The user has to manually go into their wireless settings and opt to connect to the evil twin. Doing this, you are bombarded with warnings (insecure connection, etc). 

Clients dont, wont, never will connect automatically to the rogue access point.

**Comment by oscalation** [comment]
sophron are you on IRC? I have some ideas for improvments and would like to talk

**Comment by yasoob** [comment]
And guys it is clearly mentioned in the readme that it is a social engineering attack.

**Comment by justforyouNL** [comment]
Wifiphisher sniffs the area and copies the target access point's settings. It then creates a rogue wireless access point that is modeled on the target.

Can anyone confirm this is working? as it does not for me, it's a open network, everything else works as expected.

**Comment by oscalation** [comment]
It cannot copy the encryption type, it doesn't know the password. It creating an open access point is as designed

**Comment by shady-S** [comment]
The tool is designed( as far as i know,) to create a rogue AP(without encryption or password) so that the victim connects to it unknowingly.

**Comment by oscalation** [comment]
It's pretty hard to connect to it unknowingly because you get like three warnings

**Comment by sophron** [comment]
Hi @oscalation,

"It then creates a rogue wireless access point that is modeled on the target." I think it's clear from this sentence that the rogue AP is *modeled* on the target AP. We don't say anywhere that we duplicate the target AP.

**Comment by sophron** [comment]
I'm closing this.

Feel free to re-open or send me an email if you wish to discuss more.

**Comment by vv7v7** [comment]
Dear Developer, 
So why you don't want to create a rogue ap with the same bssid ( mac address ) i.e. the whole mac or just one byte changed. Btw why you don't want to execute some scripts which will disconnect victim from his own wifi ap(mdk3, aireplay-ng etc.) ? (I.e. Linset)

Best regards,
V7

**Comment by sophron** [comment]
Hi @vv7v7,

> So why you don't want to create a rogue ap with the same bssid ( mac address ) i.e. the whole mac or just one byte changed (now it's creating some like 00:00:00:xx:xx:xx). Some device might connect to it automatically cause bssid is the same so.

If we do change to the same BSSID, we will deauthenticate our AP as well.

> Some device might connect to it automatically cause bssid is the same so.

As far as I know, this won't happen.

> Btw why you don't want to execute some scripts which will disconnect victim from his own wifi ap(mdk3, aireplay-ng etc.) while rogue ap is working ? (I.e. Linset)

We are doing deauthentication to disconnect the victims with our own custom methods.
