### ISSUE TITLE
1st Hackathon

### ISSUE THREAD

**Issue by sophron** [sophron/wifiphisher#271]
I believe it's time to have our first <a href="https://en.wikipedia.org/wiki/Hackathon">hackathon</a>. The idea is to spend the whole day trying to push (to `master` branch) as much new code as possible. This is also a good opportunity for new developers to join our crew.

During the hackathon, we will be online on <a href="http://webchat.freenode.net/?channels=wifiphisher">#wifiphisher on Freenode</a>, brainstorming, sharing ideas and dealing together with any issues during development. Contributors will be able to contact one of the developers with commit access (currently me or @blackHatMonkey) and have their Pull Requests merged as soon as possible.

There's a <a href="https://github.com/sophron/wifiphisher/milestones/Release%20v1.2">number of issues</a> that we want to have ready for the upcoming 1.2 release and there are <a href="https://github.com/sophron/wifiphisher/milestones/Future">plenty more</a> with no specific deadline. 

This is an open invitation for:
* Python developers that are interested in implementing features or tackle bugs.
* Web designers that wish to help us add more phishing templates to our collection.
* Anyone interested in Wi-Fi hacking or open-source development.

Active participants will earn a Wifiphisher t-shirt! :)

The date for the hackathon is: <b>Saturday, 18 June 2016</b>.

**Comment by sophron** [comment]
This is happening tomorrow. I'll be available around 9am to 9pm UTC and @blackHatMonkey around 12pm to 6pm UTC.

If you want to join us, come in our IRC channel, introduce yourself and let us know what do you want to work on (or you can ask for ideas)!

Happy hacking everyone!

**Comment by sophron** [comment]
Happening now! Feel free to <a href="http://webchat.freenode.net/?channels=wifiphisher">join us</a>!

**Comment by blackHatMonkey** [comment]
This was a great event. Thanks @sophron for organizing it.

**Comment by sophron** [comment]
Thank you everyone for joining. I believe we did great. I'll ship the t-shirts soon enough.
