### ISSUE TITLE
DNS redirect

### ISSUE THREAD

**Issue by x11tete11x** [sophron/wifiphisher#274]
Hi, i was looking a bit the source code and have an idea, just a brainstorm (i dont know if i see right but in fake ap dhcp do not provide the dns server) after test this tool, i think what if with DCHP on fakeAP you set a DNS that redirects all to the template page?, or perhaps combining with ettercap see my point?, to force the victim to enter to the template test

**Comment by sophron** [comment]
Hi @x11tete11x,

The script does employ a DNS server along with the DHCP. It is <a href="https://github.com/sophron/wifiphisher/blob/master/wifiphisher/pywifiphisher.py#L388">this line</a> that makes `dnsmasq` respond with the local address for every DNS query.

However, we are aware that some people are experiencing issues claiming that in some OS they won't redirect. This is something that we are investigating. We are considering switching from `dnsmasq` to a Python DHCP/DNS library.

**Comment by x11tete11x** [comment]
Thx! my mistake by not seen that :D
