### ISSUE TITLE
wifiphisher.py

### ISSUE THREAD

**Issue by NasirJAKI** [sophron/wifiphisher#278]
hi guys , i have problem , when i download the wifiphisher form the link i do unzip in kali lenux but the is no wifiphisher.py in the wifiphisher-master folder?

**Comment by sophron** [comment]
Use `python bin/wifiphisher`.

**Comment by AhmedMeso** [comment]
i have the same problem i can't use wifiphisher because it doesn't have wifiphisher.py, i tried what you said but it didn't work either, can you tell me what to do?
Now I'm gonna attacha picture of the error that i get when i type both commands!
![python error](https://cloud.githubusercontent.com/assets/20683008/17178567/4986761c-5416-11e6-964b-c7198d5b9f47.png)

i hope you reply to this soon!

**Comment by sophron** [comment]
Have you read the 'README' file? You need to `python setup.py install` first.

**Comment by AhmedMeso** [comment]
i did and i got this error!
![mesooo 1-2016-07-27-16-49-25](https://cloud.githubusercontent.com/assets/20683008/17179683/5daba9ec-541a-11e6-97ec-bd8bc1490b9e.png)

**Comment by wraith-wireless** [comment]
You need to install setuptools to use pip and setup.py. Type this in your console:

    sudo apt-get install python-setuptools

If you get any errors about " Unable to locate package" you'll need to updates your sources file /etc/apt/sources.list. Unfortunately, I don't know what sources Kali uses so you'll have to do some googleing

**Comment by AhmedMeso** [comment]
Thank you Buddie I'm gonna try it out and i will let you know soon :)

**Comment by AhmedMeso** [comment]
Thank you so much bro, it's now installing and almost gonna make it work.
but i have a question, i have a TP-LINK TL-WN722N wireless adapter and my wifi card but it doesn't support monitoring but it's a very good wireless card Can i run Python?

**Comment by AhmedMeso** [comment]
I just installed wifiphisher but when i type wifiphisher i get this error?
![mesooo 1-2016-07-27-18-36-50](https://cloud.githubusercontent.com/assets/20683008/17183740/2aea2362-5429-11e6-8ce7-4dcf7ad14c0e.png)

**Comment by pungvit** [comment]
Kali linux ?

**Comment by AhmedMeso** [comment]
Yes.

**Comment by AhmedMeso** [comment]
@wraith-wireless @sophron, Guys?

**Comment by AhmedMeso** [comment]
i solved the tcpdump error by installing tcpdump "sudo apt-get install tcpdump",
but now i get this error

![mesooo 1-2016-07-27-20-48-38](https://cloud.githubusercontent.com/assets/20683008/17188226/73ff56a4-543c-11e6-8ec2-7fe6e0492d02.png)
Can anyone help me?

**Comment by dhirajy** [comment]
root@kali:~# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-06-08 22:46
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Sending SIGKILL to wpa_supplicant
[+] Sending SIGKILL to dhclient
[+] Sending SIGKILL to NetworkManager
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:39:fd:f9
[+] Changing wlan1 MAC addr to 00:00:00:f1:cc:45
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting Network Manager Connect template
[*] Starting the fake access point...
Segmentation fault
