### ISSUE TITLE
Duplicate of #266

### ISSUE THREAD

**Issue by NasirJAKI** [sophron/wifiphisher#286]
hi guys,
when i start phishing with the wifiphisher it ask me to chose on of this 3 : 
![p](https://cloud.githubusercontent.com/assets/19974741/16171551/40520832-357a-11e6-90da-993ef1c67390.jpeg)
 so i chose the num 1 (note : i did the phishing on my router ) but the fake page not comeing in my mobile or laptop is just stopping the access of the network >>> is there any step i did wrong?

by the way i did it on my router for testing .

**Comment by sophron** [comment]
You need to try to access a page on the Internet first. Are you getting any HTTP requests?

**Comment by NasirJAKI** [comment]
@sophron 
yes i did on my laptop and my mobile too. but nothing coming just freeze the internet access

**Comment by sophron** [comment]
Sounds like #266. Let's keep the discussion there.
