### ISSUE TITLE
NO Connection to the Fake AP

### ISSUE THREAD

**Issue by shady-S** [sophron/wifiphisher#29]
Hey there, I am getting issues when connecting to fake AP. The fake AP is not able to establish connection with any victim. Also, when I close the process, it throws an exception-
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./wifiphisher.py", line 484, in channel_hop2
    deauth(monchannel)
  File "./wifiphisher.py", line 528, in deauth
    send(p, inter=float(args.timeinterval), count=int(args.packets))
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 251, in send
    __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose, realtime=realtime)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 335, in __init__
    set_promisc(self.ins, i)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 143, in set_promisc
    s.setsockopt(SOL_PACKET, cmd, mreq)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 19] No such device

// I am using kali with ALFA AWUS036H and KASENS G9000

**Comment by sandman6578** [comment]
which chipset has your kasens g9000 ralink rt3070 or rtl8187l? the g9000 is delivered with two different chipsets? 
which one did yours have??

**Comment by shady-S** [comment]
RTL8187

**Comment by sandman6578** [comment]
ok with the rtl8187 there are issues known that this chipset not compatible with hotapd buy an authors and you`ll be good

**Comment by ctrc00** [comment]
I have the exact same problem... I am using the ALFA with rtl8187.
Thanks for the info

**Comment by sandman6578** [comment]
atheros chipset most compatiple with linux i would recommend http://www.amazon.com/Docooler-Adapter-150Mbps-Atheros-Antenna/dp/B00IZ5GNSA/ref=sr_1_6?s=electronics&ie=UTF8&qid=1420704863&sr=1-6&keywords=atheros 

i have not the same card mine is built in but the same chipset

**Comment by sandman6578** [comment]
or this one TP-LINK TL-WN722N

**Comment by sandman6578** [comment]
another thing with what commands you are starting wifiphisher??

**Comment by ctrc00** [comment]
I launch a Terminal in the /home/wifiphisher folder and I do : 
python wifiphisher.py  -m 5 -t .00001 -p 1 -jI wlan1 -aI wlan2 -a 00:00:......
(btw, I choose -a accesspoint, but why it still shows me the list of access points and asks me to choose one...?)

I also tried just doing : python wifiphisher.py (same problem)

**Comment by sandman6578** [comment]
do an airmon-ng and send the output here

**Comment by shady-S** [comment]
What other chipsets are compatible?

**Comment by sandman6578** [comment]
for me i would only recommend the atheros chipsets other excluding the rtl8187 make many problem 
authors is plug and play

**Comment by shady-S** [comment]
So, can I buy any chipset model in atheros or is it specific because the one you mentioned is not available at my place.

**Comment by sandman6578** [comment]
nope buy this chipset Atheros AR9271

**Comment by shady-S** [comment]
Thanks a lot!

**Comment by sandman6578** [comment]
don't forget to close the issue

**Comment by ctrc00** [comment]
![screenshot from 2015-01-08 04 52 06](https://cloud.githubusercontent.com/assets/10434852/5660826/87826f12-96f2-11e4-9b51-04c8cae75802.png)

**Comment by ctrc00** [comment]
Wlan0=the one from my really old mini notebook
wlan1=alfa
wlan2=alfa

**Comment by ctrc00** [comment]
i found an old TP-LINK with rt73usb. Same problem, I am not able to connect to the fake AP.
![screenshot from 2015-01-08 05 15 54](https://cloud.githubusercontent.com/assets/10434852/5661083/79d07398-96f5-11e4-9bae-d9b297e3135b.png)

**Comment by sandman6578** [comment]
give me output of this hwinfo --usb

**Comment by ctrc00** [comment]
http://s3.postimg.org/oesa6ez9e/anbqybrv_Ghostbin_2015_01_08_22_30_24.jpg

**Comment by sandman6578** [comment]
ok try type in terminal modprobe rt73usb and then ifconfig wlan3 up and ifconfig wlan2 up and then try again

**Comment by sandman6578** [comment]
if not works send me output of ifconfig

**Comment by ctrc00** [comment]
It does not work better with those 3 commands.
![wlan2](https://cloud.githubusercontent.com/assets/10434852/5690711/e1126edc-98f1-11e4-82ac-614979fd7191.jpg)

**Comment by sandman6578** [comment]
you have the same ip adress for both cards change it and it will work ifconfig wlanX IPADRESS

**Comment by ctrc00** [comment]
Okay thanks for the obvious info :)
just to be sure, I have a D-Link usb wifi interface and the Alfa.
D-Link = wlan3
Alfa = wlan2

I cannot use wlan2/Alfa as the fake AP (because it is not hostapd compatible).

So, is the correct command : 
 python wifiphisher.py -m 5 -t .00001 -p 1 -jI wlan2 -aI wlan3

And I am not using the -a XX:XX:XX;XX;XX command, should I ?
The script is showing me all the available APs anyway (even if I put it on the -a command)

**Comment by ctrc00** [comment]
python wifiphisher.py -m 5 -t .00001 -p 1 -jI wlan2 -aI wlan3

When I do this, a fake AP is created. I can see it from my android. I also see the activity light blinking on the D-Link USB wifi key (wlan3). However, I don't see any lights on the ALFA (wlan2) and I am still able to use my original wifi AP without any problem. Just like if the DoS was not happening. That said, I am also not able to connect to the fake AP.

**Comment by sandman6578** [comment]
try ifconfig wlan2 up before you do the attack

**Comment by ctrc00** [comment]
I see the light going ON when i do wlan2 up.
But as soon as I start the "attack" it goes off.
 python wifiphisher.py -m 5 -t .00001 -p 1 -jI wlan2 -aI wlan3

And again, I am not able to connect to the fake AP with any device. It is here. But it takes for ever to  connect and ultimately never connects.

**Comment by ctrc00** [comment]
^CException in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wifiphisher.py", line 665, in sniff_dot11
    sniff(iface=mon_iface, store=0, prn=cb)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 485, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
error: [Errno 100] Network is down


this is what it shows when stop the attack

**Comment by pirance** [comment]
Sent from Samsung Mobileتبلمگتتنمyjkr3r394Mobileتبلمگتتنمyjkr394 ffts. Ффч 

-------- Original message --------

**Comment by shady-S** [comment]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./wifiphisher.py", line 484, in channel_hop2
    deauth(monchannel)
  File "./wifiphisher.py", line 528, in deauth
    send(p, inter=float(args.timeinterval), count=int(args.packets))
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 251, in send
    __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose, realtime=realtime)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 335, in __init__
    set_promisc(self.ins, i)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 138, in set_promisc
    mreq = struct.pack("IHH8s", get_if_index(iff), PACKET_MR_PROMISC, 0, "")
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 275, in get_if_index
    return int(struct.unpack("I",get_if(iff, SIOCGIFINDEX)[16:20])[0])
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 269, in get_if
    ifreq = ioctl(s, cmd, struct.pack("16s16x",iff))
IOError: [Errno 19] No such device


[!] Closing
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./wifiphisher.py", line 665, in sniff_dot11
    sniff(iface=mon_iface, store=0, prn=cb)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 586, in sniff
    r = prn(p)
  File "./wifiphisher.py", line 563, in cb
    if args.maximum:
AttributeError: 'NoneType' object has no attribute 'maximum'
// I am getting error while using TPLink TL_WN722N Atheros AR9271 and kasens g9000 RTL8187. Kali OS. Cannot connect to fake AP.

**Comment by pirance** [comment]
Sent from Samsung Mobile

**Comment by yassinios** [comment]
http://www.mysteryptc.com/ptp.php?ref=yassinios

**Comment by yassinios** [comment]
http://adf.ly/xhx0f

**Comment by osabosabl** [comment]
Check this out :
https://www.youtube.com/watch?v=GAGmsvpOE_Q
This one is Ralink 3070 chipset
This will fit perfect right?

**Comment by starfighter73** [comment]
hi,
I get this error when i try to connect the fake AP, anyone can help me?:
SIOCADDRT: La rete non è raggiungibile
[*] Starting the fake access point...
Traceback (most recent call last):
  File "wifiphisher.py", line 960, in <module>
    start_ap(ap_iface, channel, essid, args)
  File "wifiphisher.py", line 494, in start_ap
    Popen(['hostapd', '/tmp/hostapd.conf'], stdout=DN, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by HassenPy** [comment]
@starfighter73 , 
You are using the latest version of the script?

**Comment by starfighter73** [comment]
I solved the problem after installing 'hostapd' . I also downloaded the latest version of the script and now it works fine!
But now I have another problem: after submitting WPA Pwd i can't see it on the attacker PC.
I tried both of the wifiphisher.py versions that I downloaded.
Where's the problem?






----Messaggio originale----

Da: notifications@github.com

Data: 17/03/2015 21.52

A: "sophron/wifiphisher"<wifiphisher@noreply.github.com>

Cc: "starfighter73"<starfighter73@libero.it>

Ogg: Re: [wifiphisher] NO Connection to the Fake AP (#29)




@starfighter73 , 

You are using the latest version of the script?

**Comment by HassenPy** [comment]
does it say 'index.html' not found?

**Comment by casperass** [comment]
Yeah

2015-03-18 9:37 GMT+00:00 Hassen ben tanfous <notifications@github.com>:

**Comment by starfighter73** [comment]
Yes. It say 'index.html'.

**Comment by sandman6578** [comment]
You have to give read and write rights for the index file and any others.

**Comment by starfighter73** [comment]
Ok, thank you!

**Comment by sandman6578** [comment]
Works??

**Comment by sophron** [comment]
Hi all,

I just pushed a commit that hopefully fixes this issue. 

I believe the problem was that the script allowed the usage of an Internet-connected interface for the Access Point. A managed-mode interface that is Internet-connected or looks for an Internet connection will reset any IP addressing we want for our Access Point, hence clients won't be able to connect to it. 

Please update to the latest revision and let me know if you encounter any issues.

**Comment by starfighter73** [comment]
Hi everybody,
I tried the changes suggested by sandman6578 and it didn't works.
So I downloaded the new version poster by sophron and now the sw works properly.
Thank you!

**Comment by Jx1** [comment]
@ Sophron...Hello,

I have the same issue DHCP is not working, fake AP is created and clients get de-authenticated from the original network
Just want to make myself clear, after installing the new script of wifiphisher.All other chipset should work fine?  Apart from Realtek chipset or there is specific chipset I need to buy. 

Appreciate your response

**Comment by saintdrug** [comment]
ela refile, apo kipro, exo thema me to dhcp kai diskolevoume

**Comment by yassinios** [comment]
#outlook a {

padding: 0;
}
.ReadMsgBody {

width: 100%;
}
.ExternalClass {

width: 100%;
}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
.appleFooter a {

color: #999999;

text-decoration: none;
}
.faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
.mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

Dayami Pardon has been expecting you to confirm your relationship:

Confirm &#9658;

This is their final reminder.
Not sure you recognize Dayami Pardon?

View their photos to see if you recognize them, or simply ignore this email

*This offer has been sent by uyou336@gmail.com. By accepting this offer to try the new empowr, I stipulate that I'm 18 or older and am signing up having agreed with the product, terms and privacy policies, including the manner in which "$" and the word "earnings" are used throughout the empowr website, mobile apps and all empowr communications including this email, as defined in the product policy. This promotional email was sent to reply@reply.github.com and may contain special notices or offers. It is for illustrative purposes only and is in no way a guarantee. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA.
