### ISSUE TITLE
interface error

### ISSUE THREAD

**Issue by Anonymous0Libya** [sophron/wifiphisher#298]
Hi there, i have problem with wifiphisher.py and interface.py ... when i try to run wifiphisher an error show up .... 
```
[*] Starting Wifiphisher 1.1GIT at 2016-06-23 23:29
Traceback (most recent call last):
  File "wifiphisher", line 12, in <module>
    
  File "/root/wifiphisher-master/wifiphisher/pywifiphisher.py", line 855, in run
    args.apinterface)
  File "/root/wifiphisher-master/wifiphisher/interfaces.py", line 225, in __init__
    for interface in wireless_interfaces:
NameError: global name 'wireless_interfaces' is not defined
```
please help me ...Thank you

**Comment by blackHatMonkey** [comment]
Hi @Anonymous0Libya 
Are you using the latest version?

**Comment by Anonymous0Libya** [comment]
Hi...yes

**Comment by Anonymous0Libya** [comment]
I solved that problem....but does the victim automatic connect to my rouge
ap or they must do it manually.. thank you for your help

**Comment by blackHatMonkey** [comment]
The victim has to manually connect to the rouge AP.
