### ISSUE TITLE
Failed to find enough wireless interfaces

### ISSUE THREAD

**Issue by chycoz21** [sophron/wifiphisher#299]
```
root@kali:~/Downloads/wifiphisher/bin# ./wifiphisher
               _  __ _       _     _     _               
              (_)/ _(_)     | |   (_)   | |              
     __      ___| |_ _ _ __ | |__  _ ___| |__   ___ _ __ 
     \ \ /\ / / |  _| | '_ \| '_ \| / __| '_ \ / _ \ '__|
      \ V  V /| | | | | |_) | | | | \__ \ | | |  __/ |   
       \_/\_/ |_|_| |_| .__/|_| |_|_|___/_| |_|\___|_|   
                      | |                                
                      |_|                                
                                                         
[*] hostapd not found in /usr/sbin/hostapd, install now? [y/n] y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  hostapd
0 upgraded, 1 newly installed, 0 to remove and 220 not upgraded.
Need to get 587 kB of archives.
After this operation, 1,530 kB of additional disk space will be used.
Get:1 http://security.kali.org/kali-security/ sana/updates/main hostapd i386 1:2.3-1+deb8u3 [587 kB]
Fetched 587 kB in 9s (60.3 kB/s)                                               
Selecting previously unselected package hostapd.
(Reading database ... 323492 files and directories currently installed.)
Preparing to unpack .../hostapd_1%3a2.3-1+deb8u3_i386.deb ...
Unpacking hostapd (1:2.3-1+deb8u3) ...
Processing triggers for systemd (215-17+deb8u1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up hostapd (1:2.3-1+deb8u3) ...
update-rc.d: We have no instructions for the hostapd init script.
update-rc.d: It looks like a network service, we disable it.
insserv: warning: current start runlevel(s) (empty) of script `hostapd' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `hostapd' overrides LSB defaults (0 1 6).
Processing triggers for systemd (215-17+deb8u1) ...
[!] We have failed to find enough wireless interfaces for the program to run. Please ensure that you have two wireless adapters connected to your device and they are compatible.In order to be compatible at least one of them must supports AP mode and at least one must support monitor mode.

[!] Closing
root@kali:~/Downloads/wifiphisher/bin# 
```

**Comment by chycoz21** [comment]
root@kali:~/Downloads/wifiphisher/bin# ./wifiphisher
               _  __ _       _     _     _               
              (_)/ _(_)     | |   (_)   | |              
     __      ___| |_ _ _ __ | |__  _ ___| |__   ___ _ __ 
     \ \ /\ / / |  _| | '_ \| '_ \| / __| '_ \ / _ \ '__|
      \ V  V /| | | | | |_) | | | | \__ \ | | |  __/ |   
       \_/\_/ |_|_| |_| .__/|_| |_|_|___/_| |_|\___|_|   
                      | |                                
                      |_|                                
                                                         
[*] hostapd not found in /usr/sbin/hostapd, install now? [y/n] y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  hostapd
0 upgraded, 1 newly installed, 0 to remove and 220 not upgraded.
Need to get 587 kB of archives.
After this operation, 1,530 kB of additional disk space will be used.
Get:1 http://security.kali.org/kali-security/ sana/updates/main hostapd i386 1:2.3-1+deb8u3 [587 kB]
Fetched 587 kB in 9s (60.3 kB/s)                                               
Selecting previously unselected package hostapd.
(Reading database ... 323492 files and directories currently installed.)
Preparing to unpack .../hostapd_1%3a2.3-1+deb8u3_i386.deb ...
Unpacking hostapd (1:2.3-1+deb8u3) ...
Processing triggers for systemd (215-17+deb8u1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up hostapd (1:2.3-1+deb8u3) ...
update-rc.d: We have no instructions for the hostapd init script.
update-rc.d: It looks like a network service, we disable it.
insserv: warning: current start runlevel(s) (empty) of script `hostapd' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `hostapd' overrides LSB defaults (0 1 6).
Processing triggers for systemd (215-17+deb8u1) ...
[!] We have failed to find enough wireless interfaces for the program to run. Please ensure that you have two wireless adapters connected to your device and they are compatible.In order to be compatible at least one of them must supports AP mode and at least one must support monitor mode.

[!] Closing
root@kali:~/Downloads/wifiphisher/bin#

**Comment by blackHatMonkey** [comment]
Hi @chycoz21 
Please take a look at [Readme](https://github.com/sophron/wifiphisher/blob/master/README.md) especially this [section](https://github.com/sophron/wifiphisher#requirements). You need two wireless adapters one of which must have `AP` mode and the other must have `monitor` mode.

**Comment by sukhijashubham** [comment]
same problem here my laptop uses broadcom43142(it doesn't support moniter mode and injection) and my other network card is tplink w722n(its supports moniter mode and injection).

**Comment by blackHatMonkey** [comment]
@sukhijashubham `wifiphisher` needs an interface with monitor mode for jamming and an interface with `AP` mode for rouge AP. From what you described your internal adapter can't be used because it supports neither `AP` nor `monitor` mode and hence it can't be used.

**Comment by sukhijashubham** [comment]
@blackHatMonkey but my external adapter supports ap and moniter mode

**Comment by sukhijashubham** [comment]
@blackHatMonkey as per my knowledge wifiphisher is used on nexus device via kali nethunter with external adapter because internal doesn't support mm n ap...same case is with my laptop internal doesn't support..please correct me if i'm wrong.

**Comment by blackHatMonkey** [comment]
I'm not aware if `wifiphisher` works on the `nethunter` or not but you can't set both `AP` and `monitor` mode at the same time on one interface. We are working on ways to make it work with just one interface but as it stands you need two adapters to make it work.

**Comment by sukhijashubham** [comment]
@blackHatMonkey  according to this tutorial https://www.youtube.com/watch?v=R6I0GeEh22c
i'm able to made rogue ap but the problem is that rogue ap is not assigning ip address..any diffrence between creating rogue ap manaually and by wifiphisher?

**Comment by chycoz21** [comment]
but I do not understand how to make inteface half and did run wifiphisher must have a wireless usb , and whether it is currently running the application will automatically make its AP

**Comment by chycoz21** [comment]
whether its AP will automatically live alone like linset

**Comment by chycoz21** [comment]
how you can make 2 interface whether to use wireless card wireless card if you do not use what happened ?

**Comment by blackHatMonkey** [comment]
@sukhijashubham In the tutorial they used `airbase-ng` from `aircrack suite` to create the rouge AP while `wifiphisher` uses `hostapd` to do the same task. I'm not sure about your problem with IP assignment. If both of your adapters are compatible can you please post the result of running 
```bash
ifconfig -a
```
while both adapters are connected.

**Comment by blackHatMonkey** [comment]
@chycoz21 I can't understand you fully. Can you explain it better?

**Comment by chycoz21** [comment]
sorry I do not speak English please understand

**Comment by chycoz21** [comment]
how to make the du wireless interface for AP and one for monitors , please

**Comment by sukhijashubham** [comment]
@blackHatMonkey  ifconfig -a results are this
eth0      Link encap:Ethernet  HWaddr ac:9e:17:e3:ef:e4  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:285 errors:0 dropped:0 overruns:0 frame:0
          TX packets:285 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:25618 (25.6 KB)  TX bytes:25618 (25.6 KB)

wlan0     Link encap:Ethernet  HWaddr 5c:93:a2:ab:c3:99  
          inet addr:192.168.0.102  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::5e93:a2ff:feab:c399/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1443 errors:0 dropped:0 overruns:0 frame:1086
          TX packets:1383 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1455019 (1.4 MB)  TX bytes:190528 (190.5 KB)
          Interrupt:19 

wlan1     Link encap:Ethernet  HWaddr 60:e3:27:13:0d:b7  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

**Comment by chycoz21** [comment]
@sukhijashubham 
how to create a wireless interface into AP and become moitor,please help me

**Comment by blackHatMonkey** [comment]
@chycoz21 
All you have to do is to connect your wireless adapters.

**Comment by chycoz21** [comment]
@blackHatMonkey 
so one interface should connect to wifi and only create a rogue AP

**Comment by chycoz21** [comment]
@blackHatMonkey 
sorry I mean connect it to where?
for external wireless adapters I use I use the TP - LINK TL - WN821N 300 Mbps Wireless USB Lancard

**Comment by chycoz21** [comment]
i am  using wifiphisher-1.1 @blackHatMonkey

**Comment by chycoz21** [comment]
@blackHatMonkey 
The sudo command python wifiphisher.py -ji wlan0 ai wlan1 its functions For what ?

**Comment by sukhijashubham** [comment]
@blackhatmonkey please clear my one doubt that em having right now in my mind i.e
If my laptop's internal adapter is not compatible than can i use 2 compaitable external usb adapters to lanuch this tool properly??

**Comment by blackHatMonkey** [comment]
@chycoz21 
How many wireless adapters do you have?

@sukhijashubham 
Yes if you have connect two compatible external USB adapters it should work.

**Comment by sukhijashubham** [comment]
@blackhatmonkey thankyousomuch this works

One problem faced that it doesn't not show any device  under jamming area

**Comment by Sultan1998** [comment]
Preparing to unpack Le and rectories current Ly instal Unpacking hostapd.../hostapd 123a2,3-1 debau1 1386 deb(1:2.3-1 debaui)  Processing triggers for systemd(215-17 deb8u1)  Processing triggers for man-db(2.7.0.2-5)  Setting up host apd(1:2.3-1 deb8u1)  update-rc.d:  We have no instructions for the hostapd init script update-rc.d:  It looks like a network service,  we disable it.  insserv:  warning:  current start runlevel(s) (empty)  of script hostal s LSB defaults(2 3 4 5)  insserv:  warning:  current stop runnevel(s) (0 1 2 3 4 5 6)  of script verrides LSB defaults(0 1 6).  Processing triggers for systemd(215-17 deb8u1)                                  Что я сделаю неправильно?
