### ISSUE TITLE
Error message !!!

### ISSUE THREAD

**Issue by wermaxta** [sophron/wifiphisher#3]
Hi. I have problem with wifiphisher my OS is Kali LInux.
/wifiphisher# python2 --version
Python 2.7.3

Thank you.

[+] Ctrl-C at any time to copy an access point from below
num  ch   ESSID
---------------
1  - 1  - TALKTALK-E9C860
2  - 1  - TALKTALK-B62AF0
3  - 2  - TALKTALK-937A03
4  - 4  - TALKTALK036C9E
5  - 6  - SKY6ABBC
^C
[+] Choose the [num] of the AP you wish to copy: 1
Traceback (most recent call last):
  File "wifiphisher.py", line 768, in <module>
    Popen(['ifconfig', ap_iface, 'down'], stdout=DN, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
root@kali:~/wifiphisher#

**Comment by strasharo** [comment]
The issue above was resolved for me with the following patch:
https://github.com/sophron/wifiphisher/pull/8

**Comment by oozewall** [comment]
how do i apply the patch??anyone please explain step by step...

**Comment by escugs** [comment]
Open the file and number 2 next to python. 
from this:
#!/usr/bin/env python

to this:
#!/usr/bin/env python2

**Comment by FurqanHanif** [comment]
@escugs i did this , but still getting the same error ... (See The Image Please).. 
[img]http://i.imgur.com/Wv95q4r.png[/img]

**Comment by escugs** [comment]
try this.
use manual commands to start iJ and iA 
example : 
-a MAC -c CHANAL  -jI INTERFACE -aI INTERFACE

**Comment by FurqanHanif** [comment]
Same Issue/Error.. :/
[img]http://i.imgur.com/q3wE8Wh.png[/img]

**Comment by escugs** [comment]
no is not the same error you now get error no device found. try wlan0 to put 2 times. if this continue try using mon0 and wlan0 but remove rester_interface() from code.

**Comment by italy2010** [comment]
hello i got this error, how to solve it?

[+] Choose the [num] of the AP you wish to copy: 5
Traceback (most recent call last):
  File "wifiphisher.py", line 743, in <module>
    dhcp(dhcpconf, ap_iface)
  File "wifiphisher.py", line 407, in dhcp
    Popen(['ifconfig', mon_iface, 'mtu', '1400'], stdout=DN, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

**Comment by FurqanHanif** [comment]
Not Working , Now Getting This Error @escugs ...
Machine wifiphisher-master # ./wifiphisher.py -a BC:98:89:57:C9:4F -c 6 -jI wlan0 -aI wlan0
  File "./wifiphisher.py", line 256
    def
      ^
SyntaxError: invalid syntax

**Comment by AllanDenis** [comment]
Same [error](https://github.com/sophron/wifiphisher/issues/3#issuecomment-68740418) here. It seems to be a simple argument number error. I'm digging in it. :P

**Comment by FurqanHanif** [comment]
Now Having Some Other Issue... 
See This ...

[*] HAJI CHANDA set up on channel 6 via wlan0 on wlan0
[*] Monitor mode: wlan0 - c0:18:85:2b:XX:XX






















Jamming devices: 









DHCP Leases: 








HTTP requests: 











Jamming devices: 









DHCP Leases: 








HTTP requests: 











Jamming devices: 









DHCP Leases: 








HTTP requests: 











Jamming devices: 









DHCP Leases: 








HTTP requests: 











Jamming devices: 









DHCP Leases: 








HTTP requests: 











Jamming devices: 









DHCP Leases: 








HTTP requests: 











Jamming devices: 









DHCP Leases: 








HTTP requests: 











Jamming devices: 









DHCP Leases: 








HTTP requests: 











Jamming devices: 









DHCP Leases: 








HTTP requests: 











Jamming devices: 









DHCP Leases: 








HTTP requests: 











Jamming devices: 









DHCP Leases: 








HTTP requests: 










^C
[!] Closing

**Comment by italy2010** [comment]
and also i got this error

[*] Aida-m set up on channel 6 via wlan0 on wlan0
[*] Monitor mode: wlan0 - 00:c0:ca:7e:d0:8c
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wifiphisher.py", line 664, in sniff_dot11
    sniff(iface=mon_iface, store=0, prn=cb)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 485, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
error: [Errno 100] Network is down















Jamming devices: 









DHCP Leases: 








HTTP requests: 











Jamming devices: 









DHCP Leases: 








HTTP requests: 











Jamming devices: 









DHCP Leases: 








HTTP requests: 











Jamming devices: 









DHCP Leases: 








HTTP requests: 











Jamming devices: 









DHCP Leases: 








HTTP requests: 











Jamming devices:

**Comment by sophron** [comment]
The string concatenation errors have been solved by #20. If not, or if you are having a different error, please feel free to re-open.

**Comment by hkm23** [comment]
Hello ,
once i type python wifiphisher.py i got this display :

[*] Starting HTTP server at port 8080
Traceback (most recent call last):
  File "wifiphisher.py", line 893, in <module>
    httpd = SecureHTTPServer(("", SSL_PORT), Handler)
  File "wifiphisher.py", line 148, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use


Any solution please ?

**Comment by HassenPy** [comment]
@hkm23 run this then run wifipshisher:
    sudo fuser -k 8080/tcp

**Comment by hkm23** [comment]
thank you for he response sir Hassen ,
i've done it and after running wifiphisher i've got the same display too, i am running kali in my computer hard drive , so i thought that it would run pretty good than vmware , finally on vmware works and on hard drive won't work ,

**Comment by HassenPy** [comment]
weird, try to list the process that is using that port with this command: 
```
sudo fuser 8080/tcp
```
then when you find it's id, kill it:
```
sudo kill pid
```
this is in case going on a VM will take longer time.

**Comment by OmEeboi** [comment]
when i install wifiphisher in kali nethunter by git clone and open by typing wifiphisher 
it shows pyric error invalid aruguement plz help me
