### ISSUE TITLE
Jamming devices not populated

### ISSUE THREAD

**Issue by naflan121** [sophron/wifiphisher#302]
After Running the script, the victim is not authenticated
python setup.py install
wifiphisher

![image](https://cloud.githubusercontent.com/assets/11876070/16477459/3de0bb9a-3ec4-11e6-88ad-87221096ed00.png)

**Comment by blackHatMonkey** [comment]
@naflan121 Can you explain what you mean by not authenticating?

**Comment by naflan121** [comment]
@blackHatMonkey what i mean is devices on victim AP is not jamming

**Comment by sophron** [comment]
The effectiveness of jamming depends on the power of the wireless card and the distance to the victim. What card are you using? Have you tried moving closer to the target AP?

**Comment by naflan121** [comment]
Iam using two TL-WN722N, before the latest version released it was ok but now it doesnt show or jam devices

**Comment by crazyboogs** [comment]
I am also experiencing this behavior with an ALFA AWUS036H and an ASUS WL-167g.
I am running version 1.1

**Comment by sophron** [comment]
From what I see, the jamming is indeed happening, however it's not showing on the screen. 

Will fix soon.

**Comment by sophron** [comment]
This should be fixed now. Please update to the latest revision and let me know.

**Comment by crazyboogs** [comment]
I have updated and verified that jamming devices are now displaying. Thank you.

**Comment by sophron** [comment]
Thanks for reporting.
