### ISSUE TITLE
Wifiphisher not creating fake AP

### ISSUE THREAD

**Issue by moneydream07** [sophron/wifiphisher#305]
**Version**: Use `git show | grep commit` command and paste here the output.

**Distribution**: On which GNU/Linux distribution are you using the tool? (e.g. Kali Linux, Gentoo, Debian)

**Description**: Give a more analytical description here. If the bug you are about to report has to do with the WiFi jamming module, please specify the network cards you are using. If the bug has to do with the rogue Access Point (eg NAT or IP addressing issues), also post the output of the `ifconfig -a` and `iwconfig` commands. Finally, if the bug is about the phishing pages or our HTTP minimal server, please specify the browser you are using to connect to it.

**Steps to Reproduce**: The minimal set of steps necessary to trigger the bug.

**Expected VS actual behavior**: How were you expecting the tool to behave and what actually happened?

**Script output**: Paste the output of the tool, including any stack traces.

I tried wifiphisher on my own router and checked all devices connected to my router but there was no fake AP created in any of the devices????????

**Comment by moneydream07** [comment]
Please somone help me

**Comment by blackHatMonkey** [comment]
@moneydream07 Please update your original post ([above](https://github.com/sophron/wifiphisher/issues/305#issue-164260079)) in order to find the problem.

**Comment by moneydream07** [comment]
@blackHatMonkey I tried wifiphisher on my own router and checked all the devices connected to router.but fake AP is not created in any of devices

**Comment by moneydream07** [comment]
Please suggest me how can I solve this problem.

**Comment by moneydream07** [comment]
Please suggest me how can I solve this problem.

**Comment by sophron** [comment]
@moneydream07 Which version are you running?

**Comment by moneydream07** [comment]
@sophron kali rolling 2016 and wifiphisher 1.1

**Comment by sophron** [comment]
Okay, update to the latest revision from Github, e.g. `git clone https://github.com/sophron/wifiphisher`

**Comment by moneydream07** [comment]
@sophron I'll tell after updating and thanx for giving me your valuable time

**Comment by moneydream07** [comment]
@sophron I installed the latest version from the link you had provided but its not getting installed after running command (python setup.py).

**Comment by sophron** [comment]
@moneydream07 It's `python setup.py install`.

**Comment by sophron** [comment]
The correct command is `python setup.py install`. Read the guidelines.

I'm closing this, since it's not applicable to the latest revision.
