### ISSUE TITLE
Fill website with information

### ISSUE THREAD

**Issue by sophron** [sophron/wifiphisher#307]
I prepare wifiphisher.org for the upcoming 1.2 release. Is there someone that willing to fill the site with information? 

We need guides / HOW-TOs that present some of the new features of the tool. Specifically:
- A guide that demonstrates common options when targeting a network.
- A guide that shows how the tool can perform in public areas (e.g. not targeting a specific network).
- A HOW-TO for a designer that makes phishing templates.
- A guide for users that want to customize the phishing templates using our template engine.

English writing skills are required.

Reward: 1 x Wifiphisher t-shirt :)

**Comment by bkr32** [comment]
i can help fill it in

**Comment by sophron** [comment]
Sounds cool. Feel free to reach me on IRC (sophron@Freenode) or by email (sophron <at> latthi .dot. com).

**Comment by sophron** [comment]
Website is up. https://wifiphisher.org
