### ISSUE TITLE
[Feature Request] Phishing using only one interface

### ISSUE THREAD

**Issue by garyng** [sophron/wifiphisher#31]
Can wifiphisher add a feature to work using one interface ( to create fake ap and phishing ) ?

Coz I can't get another external wireless card here, but I got another computer that I can use to deauth the clients of an AP...

Thanks!

**Comment by gideontong** [comment]
I believe you are correct, and if there was an upvote button I would click it. :)

**Comment by FurqanHanif** [comment]
So , isn't That Possible to make another Virtual Interface Like wlan0 and create another Virtual wlan1 , half of packets send by wlan0 and half of by wlan1 ( Just Like Virtual Machine in which it Create virtual Resources from Real one (Processor , Ram etc) and Use it to run an OS ) ??

**Comment by sandman6578** [comment]
no you can only create to mon interfaces but this script is written that you need 2 adapters theres no way around this because you cannot share an access point and at the same time death with the same adapter understood?? sry for my english XD

**Comment by sandman6578** [comment]
if understood please close the issue

**Comment by yasoob** [comment]
@sophron kindly close this issue.

**Comment by garyng** [comment]
@sandman6578  i mean make wifiphisher handle the create AP thing
i can use **another computer** to deauth clients...

**Comment by yasoob** [comment]
Thats a really good idea! :+1:

**Comment by sophron** [comment]
Hi @garyng,

Wifiphisher combines other tools to automate the attack. You can use them separately for this, for example <a href="https://github.com/DanMcInerney/fakeAP">fakeAP</a> on one machine and <a href="https://github.com/DanMcInerney/wifijammer">wifijammer</a> on the other.

**Comment by garyng** [comment]
@sophron  oh thanks! :+1:
