### ISSUE TITLE
Using target's router interface template

### ISSUE THREAD

**Issue by kaliPOwned** [sophron/wifiphisher#310]
Hi,

I want to use the router's brand template interface of the target, for example the target has Sagemcom 1704 router (target_ap-vendor) which has a firmware upgrade page like this: 
![update_software](https://cloud.githubusercontent.com/assets/20462237/16852730/29ebd460-4a01-11e6-8758-c3610729419b.jpg)

i should tweak the firmware-upgrade index.htm file to achieve that. the target will be less suspecting when he sees the same interface usually used for configs and checking connection ... etc 

Thank you for your hard work!

**Comment by sophron** [comment]
Hi @kaliPOwned,

I'm not sure I understand your question. If you are asking how can you tweek this page and make it work with Wifiphisher, maybe <a href="https://thevivi.net/2016/06/18/wifi-social-engineering-playing-with-wifiphisher/">this guide</a> by VIVI will help you.

Let me know if you have any questions.

**Comment by kaliPOwned** [comment]
Thank you Sophron great tutorial. looking forward for next release with much enhancements.

**Comment by sophron** [comment]
Sure!
