### ISSUE TITLE
Execution Stops - Running on Arch Linux

### ISSUE THREAD

**Issue by thebeav26** [sophron/wifiphisher#311]
**Version**: Use `git show | grep commit` command and paste here the output.
commit 0c0075dce7eadbaef01acc4a9c76487b7aa91d41

**Distribution**: 
Arch Linux x86_64

**Summary**:
Stops execution after selecting option "2 - Firmware Upgrade Page" and outputs errors.

**Description**: 
[+] Selecting Firmware Upgrade Page template
Traceback (most recent call last):
  File "./wifiphisher", line 12, in <module>
    
  File "/home/adam/build/wifiphisher/wifiphisher/pywifiphisher.py", line 875, in run
    ap_logo_path = template.use_file(mac_matcher.get_vendor_logo_path(ap_mac))
  File "/home/adam/build/wifiphisher/wifiphisher/phishingpage.py", line 156, in use_file
    if os.path.isfile(path):
  File "/usr/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Steps to Reproduce**:
run wifiphiser -> select an AP to copy -> select phishing scenario #2 -> execution stops and errors are outputted

**Comment by sophron** [comment]
A sanity check was missing.

Please try again now and let me know if the problem persists.

**Comment by thebeav26** [comment]
That fixed that issue, but now it's stopping with the following error:

[+] Choose the [num] of the scenario you wish to use: 2
[+] Selecting Firmware Upgrade Page template
[*] Starting the fake access point...
[+] Failed to start the fake access point! (hostapd error)
[+] Try a different wireless interface using -aI option.
[!] Closing

**Comment by sophron** [comment]
Wifiphisher needs two wireless interfaces. You can try and set these manually with the `-aI`, `-jI` options. E.g. `-aI wlan0 -jI wlan1` and vice versa.

**Comment by thebeav26** [comment]
Yes, I'm using the built-in wireless card on my laptop as the rogue AP interface and a USB (Alfa) wifi device as the deauthenication attack interface.

**Comment by sophron** [comment]
I'm closing this issue since the first bug has been tackled. 

Regarding the hostapd error, this is described on #292. `-aI`, `jI`, may solve this. Can you post on #292 the output of the following commands?

  ifconfig -a
  iwconfig
  iw dev

**Comment by mrafro** [comment]
eth0      Link encap:Ethernet  HWaddr 18:67:b0:d3:dd:c1  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:190178 errors:0 dropped:128 overruns:0 frame:0
          TX packets:137791 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:213498167 (213.4 MB)  TX bytes:19688792 (19.6 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:8455 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8455 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1216819 (1.2 MB)  TX bytes:1216819 (1.2 MB)

mon0      Link encap:UNSPEC  HWaddr 24-F5-AA-77-0D-A5-3A-30-00-00-00-00-00-00-00-00  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:593 errors:0 dropped:655 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:128346 (128.3 KB)  TX bytes:0 (0.0 B)

wlan0     Link encap:Ethernet  HWaddr 24:f5:aa:77:0d:a5  
          inet addr:192.168.1.5  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::26f5:aaff:fe77:da5/64 Scope:Link
          inet6 addr: fdec:cb30:7560:4400:b91a:57c1:9ef7:3966/64 Scope:Global
          inet6 addr: fdec:cb30:7560:4400:26f5:aaff:fe77:da5/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:97485 errors:0 dropped:0 overruns:0 frame:0
          TX packets:69500 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:119041227 (119.0 MB)  TX bytes:8000310 (8.0 MB)

eth0      no wireless extensions.

mon0      IEEE 802.11bgn  Mode:Monitor  Tx-Power=15 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off
          
wlan0     IEEE 802.11bgn  ESSID:"FIRDAUS"  
          Mode:Managed  Frequency:2.412 GHz  Access Point: EC:CB:30:75:60:4C   
          Bit Rate=135 Mb/s   Tx-Power=15 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=66/70  Signal level=-44 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:1  Invalid misc:13   Missed beacon:0

lo        no wireless extensions.

phy#2
	Interface mon0
		ifindex 9
		type monitor
	Interface wlan0
		ifindex 7
		type managed

**Comment by mrafro** [comment]
i'm using ubuntu 14.04 LTS
