### ISSUE TITLE
i cant install it in my kali linux 2.0 

### ISSUE THREAD

**Issue by PlatinumBullet** [sophron/wifiphisher#312]
i cant install it in my kali linux 2.0

**Comment by sophron** [comment]
I'm sorry to hear that.

If you give us more information (e.g. what are you typing and what you are receiving), we may be able to help you.

**Comment by crazyboogs** [comment]
@PlatinumBullet make sure you are using `python setup.py install`
Some sites that provided guides on Wifiphisher instruct about using `python wifiphisher.py`

`cd wifiphisher`
`python setup.py install`

**Comment by ziadeh** [comment]
what is the error message that you get?
