### ISSUE TITLE
There are not enough wireless interfaces

### ISSUE THREAD

**Issue by ziadeh** [sophron/wifiphisher#313]
Why I'm getting this error when I have wifi tp-link tl-wn722n and connected to the computer

[*] Starting Wifiphisher 1.1GIT at 2016-07-19
[!] There are not enough wireless interfaces for the tool to run! Please ensure that at least two wireless adapters are connected to the device and they are compatible. At least one must support Master (AP) mode and another must support Monitor mode.
[!] Closing

**Comment by sophron** [comment]
The error message is self-explanatory. You need two (2) wireless cards for the tool to run.

**Comment by ziadeh** [comment]
Thank you, I'll try to have another wireless card.
but why this tool need two wireless cards?

**Comment by bkr32** [comment]
one card (capable of monitor mode) deauthenticates the users of targeted AP and the other creates a AP with the same mac address etc of the target

**Comment by sophron** [comment]
@ziadeh In general, the tool requires two wireless network adapters that support AP and Monitor mode accordingly. These are for creating the rogue AP and de-authenticating victims with efficiency at the same time. 

However, I just introduced an option `--nojamming`. This will allow the tool to run with only one interface. There will be no de-authentication phase though. This option is useful in public areas and when you don't want to be intrusive.
