### ISSUE TITLE
Syntax Error on py file

### ISSUE THREAD

**Issue by johnnyblaze1999** [sophron/wifiphisher#314]
Hi I'm just a newbie, I got a syntax error when I try to run py file. 

   File "wifiphisher.py", line 304
    print '\n[' + R + '!' + W + '] Closing'
                 ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by sophron** [comment]
This error message means that you are attempting to use Python 3 to run code in Python 2. Try executing the script again using Python 2.

**Comment by johnnyblaze1999** [comment]
Thank you for your reply. Unfortunately, there is an ImportError here:

[https://postimg.org/image/eamca0pp3/](url)

**Comment by johnnyblaze1999** [comment]
Sorry, I'm using windows 10 and run your py file with Cygwin. 
Are there anyway that I can use your file on windows operating system?

**Comment by sophron** [comment]
No, we do not support Windows.

**Comment by blackHatMonkey** [comment]
@luce-rookie The problem could be your internet connection. Alternatively you can install `setuptools` using `pip` with the following command:
```bash
sudo pip install setuptools
```
