### ISSUE TITLE
"Enter the [Full Path] to the payload you wish to serve"

### ISSUE THREAD

**Issue by Ie0h** [sophron/wifiphisher#315]
After selecting which method I want to use it asks me this.. What is this and where is it?

**Comment by pungvit** [comment]
Use the fake ap method and fake connection web pages ..

**Comment by pungvit** [comment]
I mean number 2 option. Connection reset web pages.

**Comment by Ie0h** [comment]
Oh ok, that got past that point I am connected to the AP on my mobile device and once it starts nothing happens to the WiFi. I dont get disconnected and I don't see another one show up. I am assuming this is because the selected card can't be used to create AP's but I am not sure how to check? I have a AWUS036H, now will i need another model as well to create an AP? If so what is a good model for that? 

I appreciate your help

**Comment by pungvit** [comment]
For wlan0 using in built wlan card from thinkpad x220/intel. And for wlan1 I am using usb external wifi from tplink tlwn722n. Both works well.. just need to some modif script in how to client to load phising web without lag and pass from security scan android system check.

**Comment by Ie0h** [comment]
So it works now, just tried it again and it is working but the only problem is even when it kicks the user off, they automatically re-authenticate with their proper one..

**Comment by pungvit** [comment]
Try .wifiphisher -t .00001

**Comment by Ie0h** [comment]
What is that going to do? I understand time but what is that changing?

**Comment by pungvit** [comment]
Its described at readme.md already..

**Comment by si452772** [comment]
> После выбора метода, который я хочу использовать, он меня спрашивает .. Что это и где это?

подскажите какой путь вводить если вы еэто поняли???

**Comment by Photon420** [comment]
When i try to Inject Payload through wifiphisher it gives the Recent Phonecall tracebox error. What is the problem and what is the solution??
