### ISSUE TITLE
Wifiphisher Error "[Errno 2] No such file or directory".

### ISSUE THREAD

**Issue by AhmedMeso** [sophron/wifiphisher#316]
when i launch Wifiphisher i get this error
![mesooo 1-2016-07-27-20-48-38](https://cloud.githubusercontent.com/assets/20683008/17197410/e0f79138-546c-11e6-803b-96d62d3e19be.png)
Any help?

**Comment by crazyboogs** [comment]
Do you get this same error each tome you run wifiphisher? What happens if you run wifiphisher command a second time, directly after receiving this error?

**Comment by Motasembt** [comment]
i do get this error if i press Cntrl + c , and if i run it again i will have the same error until i reboot 
why i press Cntrl + c  ? because when it start scanning for networks i dont get any networks at all 0
i have alfa neh and tplink 722

**Comment by sophron** [comment]
Hi @AhmedMeso,

What distro are you using?

Have you also tried `python bin/wifiphisher`?

**Comment by AhmedMeso** [comment]
it's all good now, i install the full package Kali linux AMD 2016, and it's working fine thank you though :)
 

    On Sunday, August 7, 2016 4:34 PM, George Chatzisofroniou <notifications@github.com> wrote:
 

 Hi @AhmedMeso,What distro are you using?Have you also tried python bin/wifiphisher?—
