### ISSUE TITLE
cert file expired

### ISSUE THREAD

**Issue by gamin12** [sophron/wifiphisher#317]
When I'm opening the new Open WiFi network when I'm clicking to chrome on an ordinary URL I'm getting page not unsecure beacause chrome detect that the cert is expired how that can be resolved

**Comment by Kingbalou** [comment]
Maybe you can add your own SSL cert file with https://letsencrypt.org/ 

Didn't try but sure it can work

**Comment by gamin12** [comment]
how can I create it

**Comment by Kingbalou** [comment]
Can't do it for you ...

https://letsencrypt.org/getting-started/

**Comment by sophron** [comment]
Hi, 

There is no way to provide a valid certificate that will bypass browser warnings. This is how SSL works.
