### ISSUE TITLE
Wifiphisher unable to jam any clients on the Real AP and Fake access point does not work

### ISSUE THREAD

**Issue by Spyro289** [sophron/wifiphisher#319]
I'am running Kali linux in a Virtual machine and i have a 'AWUS036NH ALFA' and a 'LINKSYS Wireless-G'
plugged and successfully connected into the virtual machine, both never had a problem with deauthenticating or packet injection 

I installed Wifiphisher straight from the Kali Repositories just for your information

I also notice that the isc-dhcp-server was messing from the package so i also installed also from Kali Repositories.

So I started wifiphisher and it choose the ALFA adapter as the deathenticating Interface and LINKSYS adapter as the Rogue AP.

Everything went smoothly until the final page, the page with the "Jamming devices" on the top, "DHCP Leases" in the middle and "HTTP Request" at the bottom

Now i noticed two things when i ran this against my network as a test, that it only jams the router hence it's mac address appears under the "Jamming devices" sections when there is another host on the Network and that host however still has full access to the internet

I tried to use airmon-ng and start the ALFA adapter as monitor mode went back to wifiphisher which used the ALFA adapter to deauth but it just gave the same result [Note: i also used the command airmon-ng check kill to kill the processes that interfere with monitor mode] 

So I then ignored it and proceeded to check the Rogue access point which was smoothly cloned from my main WiFi network, it had the same ESSID. but when i tried to connect my host to it, emulating an unsuspecting user It failed to connect and opening up the browser to go to any website just gives an time out error instead of the fake firmware Update page

By the way wifiphisher was packaged into the repositories of Kali linux I was the one to request it 
https://bugs.kali.org/view.php?id=3421

Run 'apt-get install wifiphisher' to get it

**Comment by sophron** [comment]
> I installed Wifiphisher straight from the Kali Repositories just for your information

What do you mean? I don't think wifiphisher has been packaged for Kali yet.

**Comment by sophron** [comment]
Hi @Spyro289,

Sorry for the extremely late response. I assume this should be fixed right.
