### ISSUE TITLE
Router Page is not shown Message:File not found

### ISSUE THREAD

**Issue by sandman6578** [sophron/wifiphisher#32]
hey guys hope someone can help me out of my problem.
first of all sorry for my bad english im german guy xD

ok so now i can make the access point with no problem and jamming others out but when i connect to the fake access point and open browser and go to i don't know a URL with no https (http and https also don't work) it gives me this error 

Error response

Error code 404.

Message: File not found.

Error code explanation: 404 = Nothing matches the given URI.

i have tried to give permissions 777 but nothing changes

i have tried this because at PWNstar you have to give permission to folder otherwise router page not shown. but not worked for this script

maybe someone can help me thanks guys bye.

**Comment by soneke** [comment]
hallow

**Comment by sandman6578** [comment]
hy your german?

**Comment by sandman6578** [comment]
sophron why is this

**Comment by gideontong** [comment]
The fake access point is not going to have an internet connection. Because there's no internet connection, you will get a 404 error which means that it doesn't seem to exist. You need to connect to the real access point, as I'm assuming the real access point has an Internet connection. I don't see the issue here, if there is one can you please explain it a little more?

**Comment by sandman6578** [comment]
no thats not my problem. i dont need internet connectiion i only want to phish the wpa key
my problem is i create everything with the script after the dhcp and http loop comes which checks if the victim is typing in the password but when i want to connect the fake access point to check if eversthing is working well. i do this with a macbook air  i connect to the fake accesspoint but the router fake wpa phishing page is not shown i became the error in browser when i want to open a site to test if it forwards to the phishing page

**Comment by sandman6578** [comment]
sorry for Grammer

**Comment by sandman6578** [comment]
by the way running kali-linux

**Comment by gideontong** [comment]
The way I see it, this tool uses a MITM attack where the target computer connects to the fake access point with the WiFi password and that's how you capture it. Correct me if I'm wrong.

**Comment by sandman6578** [comment]
Yes thats right but in view of my victim he cannot arrive my Phishing page but i solved the problem for now.
Solution:
copy the folder access-point-pages to /var/www/ and give permissions to read and write to every file in folder minimal also the folder minimal needs this permissions.
then search in wifiphisher.py with leaped in ##basic configuration##  section in code for parameter PHISHING_PAGE= change it to "var/www/access-point-pages/minimal"
but now a new problem appears for me .
the phishing page shows no pictures and the style.css is also not binded in page. So for me theres only the index.html with no styles and no pictures

**Comment by sandman6578** [comment]
heres an image of the page.
How to fix this.
![screenshot of phishing page](https://cloud.githubusercontent.com/assets/10436946/5659361/5928941a-9711-11e4-97d8-c34ba4aa1985.png)

**Comment by sandman6578** [comment]
yes i have all files include bg.jpg, index.html, upgrading.html, loading.gif, logo.jpg, and style.css in the same folder. permissions to read and write are given in folder options(file options)

**Comment by HassenPy** [comment]
checked if the paths in the html file are correct?, sometimes i miss the smallest detail, just sayin...

**Comment by sandman6578** [comment]
yes have checked this for now everything works perfect for me .
my solution was to copy all of the script to the /var/www folder + the script and start it there now the page appears perfect

**Comment by kawaiixyrene** [comment]
can you help me.. i have the same problem as yours, i put the script to the /var/www folder + the script and run it there but the problem still exist.. i also give permission to read and write to all files in minimal folder, but same result.. it always give me the error:

Error response

Error code 404.

Message: File not found.

Error code explanation: 404 = Nothing matches the given URI.

i will appreciate any help.. sorry for my english..

**Comment by darkkrow** [comment]
hi guys first of all sorry for my bad english but I'm italian!
@sophron @sandman6578 I Have the same problem!
I try to put the wifiphisher folder in /var/www and i change PHISHING_PAGE= to "var/www/wifiphisher/phishing-scenarios/minimal" in wifiphisher.py. i give permission to read and write to all files and subfolder but i see this page:
![5928941a-9711-11e4-97d8-c34ba4aa1985](https://cloud.githubusercontent.com/assets/13767360/9236849/b0d4fb0a-4147-11e5-8632-977e7ecaec73.png)
The script work fine with no error.
maybe have i wrong  some step?
Thank's in advance

**Comment by vincentmoglia** [comment]
Same problem for me guys...
