### ISSUE TITLE
Unable to set AWUS036H card as rogue AP (-aI)

### ISSUE THREAD

**Issue by crazyboogs** [sophron/wifiphisher#320]
iwconfig output: (wlan0 is my AWUS036H card, wlan1 is an ASUSWL-167g card)

`iwconfig`
`eth0      no wireless extensions.`

`wlan0     IEEE 802.11bg  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off`
          
`lo        no wireless extensions.`

`wlan1     IEEE 802.11bg  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:on`
`

If I run just the wifiphisher command, it will always use my AWUS036H card for deauth, and my WL-167g card as rogue AP. 

`wifiphisher`
`[*] Starting Wifiphisher 1.1GIT at 2016-08-13 10:17
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wlan1 interface for creating the rogue Access Point`

I would prefer the AWUS036H be used as rogue AP so I used 

`wifiphisher -aI wlan0 -jI wlan1`

and received the following response:

`wifiphisher -aI wlan0 -jI wlan1
[*] Starting Wifiphisher 1.1GIT at 2016-08-13 10:15
[!] We have failed to set the access point interface (-aI)! This is either due to the fact that we were unable to find the given interface in the available interfaces or the given interface was incompatible.
[!] Closing
`

Any advice?

**Comment by Chitramani** [comment]
do we see 2 access point with same essid after creating fake access point?
i m using ubuntu 
starting fake accesspoint appears on terminal 
but i only see one original access point and not able to connect to it because of jamming ''
please help......

**Comment by crazyboogs** [comment]
@Chitramani - In my experience, yes, you will see the original AP (will have whatever encryption, WPA/WPA2, etc.) and then you will see an unsecured AP with a matching ESSID (unless you specified -pK command during start of wifiphisher).

**Comment by sophron** [comment]
The reason is that your Linux drivers for AWUS036H don't support AP mode, hence `wifiphisher` cannot create an AP using this wireless card.
