### ISSUE TITLE
Installation Issues [Errno 2] No such file or directory: '.....

### ISSUE THREAD

**Issue by updown1** [sophron/wifiphisher#324]
Morning All,

Installing Issues. I been at this for about two days. Any help is welcome!!!

No LSB modules are available.
Distributor                                       ID: Kali
Description:                                    Kali GNU/Linux Rolling
Release:                                          Kali-rolling
Codename:                                     Kali rolling

Python-scapy installed
Python2.7 installed (version 2.7.12+)
____

Running installer:

python setup.py install

running install
error: can't create or remove files in install directory

The following error occured while trying to add or remove files in the installation directory:

        [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/test-east-install-4144.write-test'

The instllation directory you specified (via --install-dir, --prefix, or the distutils default setting) was:

        /usr/local/lib/python2.7/dist-packages/

This directory does not currently exist. Please create it and try again, or chose a different installation directory (using the -d or --install-dir option).

Thanks & Cheers,

**Comment by wraith-wireless** [comment]
make sure you're running as root i.e. sudo python setup.py install

**Comment by updown1** [comment]
Already done. No difference. I still get the same error. 

Any other ideas?

**Comment by abratar** [comment]
It's the same for me. I don't have the directory dist-packages/ in my python2.7/ folder. I tried reinstalling python but it didn't help. Any ideas? I used this program like 4 months ago or so and it worked fine with the exact same setup. I used had an old version but I don't have it on my pc anymore so I downloaded the newest version but it's not working :/

**Comment by abratar** [comment]
Omg we are so dumb :D Just create the folder dist-packages/ in your python2.7/ folder with root rights and it will work... I found out like 30 secs after I wrote my last post

**Comment by updown1** [comment]
I tried that already without any success. It did a semi-install but it failed on the end.

  What exactly did you type?

**Comment by abratar** [comment]
What do you mean what did i type? As I said, I just created the folder that was not found "dist-packages/" ind my "python2.7/" folder -> In the Error Message.

**Comment by zero77** [comment]
You have to run it as root, use sudo in front of the command when starting it, this worked for me.

**Comment by abratar** [comment]
I had the exact same error and running as root didn't help me. only the method showed above worked for me.

**Comment by Tsotne1998** [comment]
@slow-dow so i did what u did but it says it allready exists what can i do?
