### ISSUE TITLE
Add option for custom page.

### ISSUE THREAD

**Issue by JoshCranna** [sophron/wifiphisher#325]
As the tile says, not really an Issue and I am looking at implementing it myself, but it would be a good feature for someone who wants to mock up a page and use that.

Good work :)

**Comment by Kingbalou** [comment]
Hi, 
You can add your own page by looking a little bit more in the sources.

You have folder :

`wifiphisher/data/phishing-pages`

Now you have to find where does the script call the pages ;) 

(Sorry no time to search for you) 

Good luck

**Comment by sophron** [comment]
Yes, have a look at the `doc/wifiphisher.txt`, there's a section called 'PHISHING SCENARIOS' that goes into detail on how to create your own.  You may also find helpful this blog <a href="https://thevivi.net/2016/06/18/wifi-social-engineering-playing-with-wifiphisher/">post</a> from VIVI.
