### ISSUE TITLE
Improve AP Cloning

### ISSUE THREAD

**Issue by zero77** [sophron/wifiphisher#326]
The devices on the real AP don’t seem to connect to the fake one, would it help to copy the mac address of the real AP, or something else to get the clients to connect to the fake AP.

Or is there something else I can do that will help to get the devices to connect to the fake AP.

**Comment by sophron** [comment]
Have a look at #170 for the reason that we don't clone the MAC address (BSSID). The auto-connection depends on many factors, like the target's Operating System or the auto-connect flag.
