### ISSUE TITLE
Attack Page Improvements

### ISSUE THREAD

**Issue by zero77** [sophron/wifiphisher#327]
Can you add numbers next to the get request instead of displaying every single GET request from a device, in order to save space.

Also can you change the device jamming section to a format that is easier to read quickly, for example, [Device Number] Mac Address  -  Vender  -  SSID

Thanks

**Comment by sophron** [comment]
I'm not sure I understand. How numbers in the HTTP requests will save space? What is the "Device Number" in the Jamming section? Can you provide an example on how exactly you imagine the output?
