### ISSUE TITLE
Wifi Phisher Doesn't Start Monitor Mode

### ISSUE THREAD

**Issue by Plebsteb123** [sophron/wifiphisher#330]
When i run wifiphisher it jams clients but none of the clients connects to the face access point when i do iwconfig i realize none of my cards are in monitor mode and both support it.

root@kali:~# iwconfig
eth0      no wireless extensions.

wlan0     IEEE 802.11bgn  Mode:Master  Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off
          
lo        no wireless extensions.

wlan1     IEEE 802.11bgn  Mode:Monitor  Frequency:2.452 GHz  Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off

**Comment by wraith-wireless** [comment]
wlan1 is in monitor mode. The fake AP would require a card that supports AP mode. Get your phy indexes with 

    iw dev

then 

    iw phy phy0 info

replacing phy0 with whatever index(es) you have. In the output look for "Supported interface modes" and see if your card has AP listed

**Comment by sophron** [comment]
As @wraith-wireless already wrote, `wlan1` is in monitor mode.

Please also note that the clients most of the time, need to manually select the rogue network.
