### ISSUE TITLE
Why I can't find file "wifiphisher.py"  ? plaise help me 

### ISSUE THREAD

**Issue by zedek001** [sophron/wifiphisher#333]
![ghanou](https://cloud.githubusercontent.com/assets/16209410/18338986/7a124f32-7594-11e6-95ed-92d5c2291ed7.png)

**Comment by Efpkaf** [comment]
sudo python setup.py install

**Comment by sophron** [comment]
Please read the README.md before posting. Execution script is in `bin/wifiphisher`.
