### ISSUE TITLE
Problem with remote VPN (vpnc) connection via ppp0

### ISSUE THREAD

**Issue by leblitzdick** [sophron/wifiphisher#335]
Everything works fine on my armbian cubietruck(vanilla,xenial) installed wifiphisher,
but if i try the same then connected remotely, or even a tunnel (ppp0, tun0) is just open, there will be an error message:

![2](https://cloud.githubusercontent.com/assets/22169878/18488930/d38cc09a-79fb-11e6-85bd-15b937bdd3fa.jpg)
![1](https://cloud.githubusercontent.com/assets/22169878/18489527/2a42b8b6-79fe-11e6-97d5-e5f0dd595f95.png)

How can I wifiphisher say that it does not consider these devices? 
Wifiphisher probably thinks it would be wireless devices, but this is obviously not!

Thanks and I hope you can help me
Matthias

**Comment by sophron** [comment]
@wraith-wireless Can you have a look at this? Is it possible that `winterfaces()` returns tunneled interfaces too?

**Comment by wraith-wireless** [comment]
Just saw this, looking into it

**Comment by wraith-wireless** [comment]
@leblitzdick 
It looks like the tunneled devices are getting an EINVAL error which is not covered yet. I think I'm just going to cover all errors by returning False. 

Can you try deleting lines 167 and 168

    if e.errno == pyric.ENODEV or e.errno == pyric.EOPNOTSUPP: return False
    else: raise pyric.error(e.errno)

and replace with

    return False     

This should be a stopgap until I can update the code

**Comment by wraith-wireless** [comment]
Code changed on Github and uploaded to Pypi

**Comment by sophron** [comment]
Nice, thanks. @leblitzdick you can check if it's working properly now.

**Comment by leblitzdick** [comment]
thanks @wraith-wireless this will fix the Problem, now its working!

**Comment by leblitzdick** [comment]
of course also thanks @sophron for the right idea!
