### ISSUE TITLE
Closing after one credential grab

### ISSUE THREAD

**Issue by CamelToeJoe** [sophron/wifiphisher#336]
I have been playing around with WiFiphisher and things are working pretty well.  

I have noticed:

The Deauth doens't seem to work well.  Clients joining the Fake AP at the start will capture but don't seem to get booted if already connected to the Real AP

Also after one credential grab the program closes it needs to stay running if using something than router grabs, of which I understand. 

Anyway to clone websites or import custom phishing pages.

Thanks for your work.

**Comment by ammarkhder** [comment]
can someone show me who to work with last version of wifiphisher ..its different form the other version

**Comment by sophron** [comment]
I plan to push improvements on jamming soon enough.

Yes, we should also introduce an option that does not terminates the script when it captures a pair of credentials.

**Comment by CamelToeJoe** [comment]
Great
