### ISSUE TITLE
Wifiphisher cannot install hostapd package.

### ISSUE THREAD

**Issue by djdisikd** [sophron/wifiphisher#338]
**Version**: wifiphisher 1.1

**Distribution**: Kali Linux

![img_20160918_155615](https://cloud.githubusercontent.com/assets/17978000/18614077/de744ee4-7db9-11e6-9145-aa8a404289e7.jpg)

What is the problem exactly here?
I am using Alfa 802.11 b/g long range wireless USB adapter

Thanks for helping!

**Comment by sophron** [comment]
The script output is pretty clear. Read <a href="http://docs.kali.org/general-use/kali-linux-sources-list-repositories">here</a>.

**Comment by djdisikd** [comment]
Thanks sophron
