### ISSUE TITLE
Just Stuck in Somekind of Loop.

### ISSUE THREAD

**Issue by FurqanHanif** [sophron/wifiphisher#34]
See This. it's Just Keep repeating it again and again and Nothing Happens..
[*] M.B.A set up on channel 6 via wlan0 on wlan0
[*] Monitor mode: wlan0 - c0:18:85:2b:xx:xx

Jamming devices: 

DHCP Leases: 

HTTP requests: 

Jamming devices: 

DHCP Leases: 

HTTP requests: 

Jamming devices: 

DHCP Leases: 

HTTP requests: 

Jamming devices: 

DHCP Leases: 

HTTP requests: 

^C
[!] Closing

**Comment by sandman6578** [comment]
thats normal try to connect to your created access point and look if something changes

**Comment by sandman6578** [comment]
please write back if problem sold and close the issue if it will work

**Comment by F0xD3** [comment]
Hi, i have the same problem, when i try to connect to my created acces point, nothing happen,i get this message :  Connected, waiting for authentication (waiting for ip address.)

**Comment by sandman6578** [comment]
guys post your ifconfig

**Comment by F0xD3** [comment]
root@kali:~# ifconfig -a
eth0      Link encap:Ethernet  HWaddr 08:00:27:6d:30:40  
          inet addr:192.168.2.21  Bcast:192.168.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe6d:3040/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:11598 errors:0 dropped:0 overruns:0 frame:0
          TX packets:51556 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:835072 (815.5 KiB)  TX bytes:3433070 (3.2 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:175792 errors:0 dropped:0 overruns:0 frame:0
          TX packets:175792 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:33304927 (31.7 MiB)  TX bytes:33304927 (31.7 MiB)

wlan0     Link encap:Ethernet  HWaddr 00:0f:13:08:0a:f9  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wlan1     Link encap:Ethernet  HWaddr 68:7f:74:7f:0a:f1  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

**Comment by sophron** [comment]
Hi @FurqanHanif,

The DHCP problem is already mentioned on another ticket. Thanks for contributing.
