### ISSUE TITLE
We have failed to find a wireless interface that supports AP mode!

### ISSUE THREAD

**Issue by Daithy** [sophron/wifiphisher#340]
Hi, I am using Kali. Wlan0 is my normal laptop's chip, wlan1 is Alfa AWUS036H. Can you please help to figure out what is going on? Thanks.

root@kali:~# wifiphisher
[*] Starting Wifiphisher 1.1GIT at 2016-09-21 14:57
[!] We have failed to find a wireless interface that supports AP mode! Please make sure that all the wireless adapters are connected and they are compatible.
[!] Closing
root@kali:~# ifconfig
eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 00:1d:ba:86:e9:d6  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 18  bytes 1058 (1.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 18  bytes 1058 (1.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.11  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::c53c:7147:4df6:2cfe  prefixlen 64  scopeid 0x20<link>
        ether 00:21:5d:9f:82:52  txqueuelen 1000  (Ethernet)
        RX packets 2455  bytes 1651358 (1.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1887  bytes 311702 (304.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 00:c0:ca:72:97:c2  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@kali:~# wifiphisher -jI wlan1 -aI wlan0
[*] Starting Wifiphisher 1.1GIT at 2016-09-21 15:01
[!] We have failed to set the access point interface (-aI)! This is either due to the fact that we were unable to find the given interface in the available interfaces or the given interface was incompatible.
[!] Closing
root@kali:~#

**Comment by Daithy** [comment]
I even swapped the interfaces' roles and still problem with -aI

_**wifiphisher -jI wlan0 -aI wlan1
[*] Starting Wifiphisher 1.1GIT at 2016-09-21 16:47
[!] We have failed to set the access point interface (-aI)! This is either due to the fact that we were unable to find the given interface in the available interfaces or the given interface was incompatible.**_

**Comment by sophron** [comment]
Hi,

Not all hardware / driver combinations do all modes. Try `iw list` and see if one of your cards support AP mode.

**Comment by Daithy** [comment]
Hi. I will try it later and get back with results.

**Comment by Daithy** [comment]
Okay. So here's Iwconfig to see what's available. Wlan1 is my Alfa. Besides I had it set as an AP before in Backtrack5 R3 no problem.

_root@kali:~# iwconfig
lo        no wireless extensions.

wlan1     IEEE 802.11bg  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
wlan0     IEEE 802.11abgn  ESSID:"Cablesurf_5G_D0018295"  
          Mode:Managed  Frequency:5.22 GHz  Access Point: 70:5A:9E:33:AB:DA   
          Bit Rate=135 Mb/s   Tx-Power=15 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=66/70  Signal level=-44 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:72   Missed beacon:0

eth0      no wireless extensions._


**And here's the list, which I cannot read very well.**

root@kali:~# iw list
Wiphy phy1
	max # scan SSIDs: 4
	max scan IEs length: 2285 bytes
	Retry short limit: 7
	Retry long limit: 4
	Coverage class: 0 (up to 0m)
	Device supports RSN-IBSS.
	Supported Ciphers:
		* WEP40 (00-0f-ac:1)
		* WEP104 (00-0f-ac:5)
		* TKIP (00-0f-ac:2)
		* CCMP (00-0f-ac:4)
		* 00-0f-ac:10
		* GCMP (00-0f-ac:8)
		* 00-0f-ac:9
	Available Antennas: TX 0 RX 0
	Supported interface modes:
		 * IBSS
		 * managed
		 * monitor
	Band 1:
		Bitrates (non-HT):
			* 1.0 Mbps
			* 2.0 Mbps
			* 5.5 Mbps
			* 11.0 Mbps
			* 6.0 Mbps
			* 9.0 Mbps
			* 12.0 Mbps
			* 18.0 Mbps
			* 24.0 Mbps
			* 36.0 Mbps
			* 48.0 Mbps
			* 54.0 Mbps
		Frequencies:
			* 2412 MHz [1] (20.0 dBm)
			* 2417 MHz [2] (20.0 dBm)
			* 2422 MHz [3] (20.0 dBm)
			* 2427 MHz [4] (20.0 dBm)
			* 2432 MHz [5] (20.0 dBm)
			* 2437 MHz [6] (20.0 dBm)
			* 2442 MHz [7] (20.0 dBm)
			* 2447 MHz [8] (20.0 dBm)
			* 2452 MHz [9] (20.0 dBm)
			* 2457 MHz [10] (20.0 dBm)
			* 2462 MHz [11] (20.0 dBm)
			* 2467 MHz [12] (20.0 dBm)
			* 2472 MHz [13] (20.0 dBm)
			* 2484 MHz [14] (disabled)
	Supported commands:
		 * new_interface
		 * set_interface
		 * new_key
		 * start_ap
		 * new_station
		 * new_mpath
		 * set_mesh_config
		 * set_bss
		 * authenticate
		 * associate
		 * deauthenticate
		 * disassociate
		 * join_ibss
		 * join_mesh
		 * set_tx_bitrate_mask
		 * frame
		 * frame_wait_cancel
		 * set_wiphy_netns
		 * set_channel
		 * set_wds_peer
		 * probe_client
		 * set_noack_map
		 * register_beacons
		 * start_p2p_device
		 * set_mcast_rate
		 * Unknown command (104)
		 * connect
		 * disconnect
	Supported TX frame types:
		 * IBSS: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * managed: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * AP: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * AP/VLAN: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * mesh point: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-device: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
	Supported RX frame types:
		 * IBSS: 0x40 0xb0 0xc0 0xd0
		 * managed: 0x40 0xd0
		 * AP: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * AP/VLAN: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * mesh point: 0xb0 0xc0 0xd0
		 * P2P-client: 0x40 0xd0
		 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * P2P-device: 0x40 0xd0
	software interface modes (can always be added):
		 * monitor
	interface combinations are not supported
	HT Capability overrides:
		 * MCS: ff ff ff ff ff ff ff ff ff ff
		 * maximum A-MSDU length
		 * supported channel width
		 * short GI for 40 MHz
		 * max A-MPDU length exponent
		 * min MPDU start spacing
	Device supports TX status socket option.
	Device supports HT-IBSS.
	Device supports SAE with AUTHENTICATE command
	Device supports low priority scan.
	Device supports scan flush.
	Device supports AP scan.
	Device supports per-vif TX power setting
	Driver supports full state transitions for AP/GO clients
	Driver supports a userspace MPM
Wiphy phy0
	max # scan SSIDs: 20
	max scan IEs length: 195 bytes
	Retry short limit: 7
	Retry long limit: 4
	Coverage class: 0 (up to 0m)
	Device supports RSN-IBSS.
	Supported Ciphers:
		* WEP40 (00-0f-ac:1)
		* WEP104 (00-0f-ac:5)
		* TKIP (00-0f-ac:2)
		* CCMP (00-0f-ac:4)
		* 00-0f-ac:10
		* GCMP (00-0f-ac:8)
		* 00-0f-ac:9
	Available Antennas: TX 0 RX 0
	Supported interface modes:
		 * IBSS
		 * managed
		 * monitor
	Band 1:
		Capabilities: 0x1072
			HT20/HT40
			Static SM Power Save
			RX Greenfield
			RX HT20 SGI
			RX HT40 SGI
			No RX STBC
			Max AMSDU length: 3839 bytes
			DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 4 usec (0x05)
		HT RX MCS rate indexes supported: 0-15
		TX unequal modulation not supported
		HT TX Max spatial streams: 1
		HT TX MCS rate indexes supported may differ
		Bitrates (non-HT):
			* 1.0 Mbps
			* 2.0 Mbps (short preamble supported)
			* 5.5 Mbps (short preamble supported)
			* 11.0 Mbps (short preamble supported)
			* 6.0 Mbps
			* 9.0 Mbps
			* 12.0 Mbps
			* 18.0 Mbps
			* 24.0 Mbps
			* 36.0 Mbps
			* 48.0 Mbps
			* 54.0 Mbps
		Frequencies:
			* 2412 MHz [1] (15.0 dBm)
			* 2417 MHz [2] (15.0 dBm)
			* 2422 MHz [3] (15.0 dBm)
			* 2427 MHz [4] (15.0 dBm)
			* 2432 MHz [5] (15.0 dBm)
			* 2437 MHz [6] (15.0 dBm)
			* 2442 MHz [7] (15.0 dBm)
			* 2447 MHz [8] (15.0 dBm)
			* 2452 MHz [9] (15.0 dBm)
			* 2457 MHz [10] (15.0 dBm)
			* 2462 MHz [11] (15.0 dBm)
			* 2467 MHz [12] (15.0 dBm) (no IR)
			* 2472 MHz [13] (15.0 dBm) (no IR)
	Band 2:
		Capabilities: 0x1072
			HT20/HT40
			Static SM Power Save
			RX Greenfield
			RX HT20 SGI
			RX HT40 SGI
			No RX STBC
			Max AMSDU length: 3839 bytes
			DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 4 usec (0x05)
		HT RX MCS rate indexes supported: 0-15
		TX unequal modulation not supported
		HT TX Max spatial streams: 1
		HT TX MCS rate indexes supported may differ
		Bitrates (non-HT):
			* 6.0 Mbps
			* 9.0 Mbps
			* 12.0 Mbps
			* 18.0 Mbps
			* 24.0 Mbps
			* 36.0 Mbps
			* 48.0 Mbps
			* 54.0 Mbps
		Frequencies:
			* 5180 MHz [36] (13.0 dBm) (no IR)
			* 5200 MHz [40] (15.0 dBm) (no IR)
			* 5220 MHz [44] (15.0 dBm) (no IR)
			* 5240 MHz [48] (15.0 dBm) (no IR)
			* 5260 MHz [52] (15.0 dBm) (no IR, radar detection)
			  DFS state: usable (for 207 sec)
			  DFS CAC time: 60000 ms
			* 5280 MHz [56] (15.0 dBm) (no IR, radar detection)
			  DFS state: usable (for 207 sec)
			  DFS CAC time: 60000 ms
			* 5300 MHz [60] (15.0 dBm) (no IR, radar detection)
			  DFS state: usable (for 207 sec)
			  DFS CAC time: 60000 ms
			* 5320 MHz [64] (13.0 dBm) (no IR, radar detection)
			  DFS state: usable (for 207 sec)
			  DFS CAC time: 60000 ms
			* 5500 MHz [100] (15.0 dBm) (no IR, radar detection)
			  DFS state: usable (for 207 sec)
			  DFS CAC time: 60000 ms
			* 5520 MHz [104] (15.0 dBm) (no IR, radar detection)
			  DFS state: usable (for 207 sec)
			  DFS CAC time: 60000 ms
			* 5540 MHz [108] (15.0 dBm) (no IR, radar detection)
			  DFS state: usable (for 207 sec)
			  DFS CAC time: 60000 ms
			* 5560 MHz [112] (15.0 dBm) (no IR, radar detection)
			  DFS state: usable (for 207 sec)
			  DFS CAC time: 60000 ms
			* 5580 MHz [116] (15.0 dBm) (no IR, radar detection)
			  DFS state: usable (for 207 sec)
			  DFS CAC time: 60000 ms
			* 5600 MHz [120] (15.0 dBm) (no IR, radar detection)
			  DFS state: usable (for 207 sec)
			  DFS CAC time: 60000 ms
			* 5620 MHz [124] (15.0 dBm) (no IR, radar detection)
			  DFS state: usable (for 207 sec)
			  DFS CAC time: 60000 ms
			* 5640 MHz [128] (15.0 dBm) (no IR, radar detection)
			  DFS state: usable (for 207 sec)
			  DFS CAC time: 60000 ms
			* 5660 MHz [132] (15.0 dBm) (no IR, radar detection)
			  DFS state: usable (for 207 sec)
			  DFS CAC time: 60000 ms
			* 5680 MHz [136] (15.0 dBm) (no IR, radar detection)
			  DFS state: usable (for 207 sec)
			  DFS CAC time: 60000 ms
			* 5700 MHz [140] (15.0 dBm) (no IR, radar detection)
			  DFS state: usable (for 207 sec)
			  DFS CAC time: 60000 ms
			* 5745 MHz [149] (disabled)
			* 5765 MHz [153] (disabled)
			* 5785 MHz [157] (disabled)
			* 5805 MHz [161] (disabled)
			* 5825 MHz [165] (disabled)
	Supported commands:
		 * new_interface
		 * set_interface
		 * new_key
		 * start_ap
		 * new_station
		 * new_mpath
		 * set_mesh_config
		 * set_bss
		 * authenticate
		 * associate
		 * deauthenticate
		 * disassociate
		 * join_ibss
		 * join_mesh
		 * set_tx_bitrate_mask
		 * frame
		 * frame_wait_cancel
		 * set_wiphy_netns
		 * set_channel
		 * set_wds_peer
		 * probe_client
		 * set_noack_map
		 * register_beacons
		 * start_p2p_device
		 * set_mcast_rate
		 * Unknown command (104)
		 * connect
		 * disconnect
	Supported TX frame types:
		 * IBSS: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * managed: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * AP: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * AP/VLAN: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * mesh point: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-device: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
	Supported RX frame types:
		 * IBSS: 0x40 0xb0 0xc0 0xd0
		 * managed: 0x40 0xd0
		 * AP: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * AP/VLAN: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * mesh point: 0xb0 0xc0 0xd0
		 * P2P-client: 0x40 0xd0
		 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * P2P-device: 0x40 0xd0
	software interface modes (can always be added):
		 * monitor
	interface combinations are not supported
	HT Capability overrides:
		 * MCS: ff ff ff ff ff ff ff ff ff ff
		 * maximum A-MSDU length
		 * supported channel width
		 * short GI for 40 MHz
		 * max A-MPDU length exponent
		 * min MPDU start spacing
	Device supports TX status socket option.
	Device supports HT-IBSS.
	Device supports SAE with AUTHENTICATE command
	Device supports scan flush.
	Device supports per-vif TX power setting
	Driver supports full state transitions for AP/GO clients
	Driver supports a userspace MPM
	Device supports static SMPS
	Device supports dynamic SMPS
root@kali:~#

**Comment by Daithy** [comment]
**Here I used the airbase command and created an AP with my Alfa, even without switching to monitor mode. I can see the access point with my phone and my 2nd Wifi.**

root@kali:~# airbase-ng -e "test" -c 11 -a 00:12:23:34:45:56 wlan1
ioctl(SIOCSIWMODE) failed: Device or resource busy
14:46:49  Created tap interface at0
14:46:49  Trying to set MTU on at0 to 1500
14:46:49  Trying to set MTU on wlan1 to 1800
14:46:49  Access Point with BSSID 00:12:23:34:45:56 started.

**I even created an AP with the native chip and it also works. Although it fails for some reason after about 30s. But the Alfa is stable and does not crash.**

root@kali:~# airbase-ng -e "test2" -c 11 -a 00:12:23:34:45:56 wlan0
ioctl(SIOCSIWMODE) failed: Device or resource busy
14:51:52  Created tap interface at0
14:51:52  Trying to set MTU on at0 to 1500
14:51:52  Access Point with BSSID 00:12:23:34:45:56 started.
read failed: Network is down
wi_read(): Network is down
Error: Got channel -1, expected a value > 0.

**Comment by wraith-wireless** [comment]
In your iw list output, look for the below:

    Supported interface modes:
    * IBSS
    * managed
    * monitor

which means your card only supports those three modes and not AP mode. You are able to set up an AP with airbase because airbase uses ioctl to communicate with the kernel/device. ioctl is deprecated and while still useful for simple tasks it has shortcomings such as your created AP crashing after 30 seconds.

Alfa cards are excellent cards for some tasks but have many shortcomings. For example, even in monitor mode, Alfa firmware will drop STA to STA and STA to AP traffic.

**Comment by Daithy** [comment]
> 

In your iw list output, look for the below:

Supported interface modes:
* IBSS
* managed
* monitor

which means your card only supports those three modes and not AP mode. You are able to set up an AP with airbase because airbase uses ioctl to communicate with the kernel/device. ioctl is deprecated and while still useful for simple tasks it has shortcomings such as your created AP crashing after 30 seconds.

Alfa cards are excellent cards for some tasks but have many shortcomings. For example, even in monitor mode, Alfa firmware will drop STA to STA and STA to AP traffic.

> 

Right, I understand, but the Alfa does not crash, and setting up a fake AP for 1 client is a simple task, I would imagine. But okay, so what cards are compatible with Wifihisher?

Thanks.

**Comment by sophron** [comment]
One card needs to support AP mode, the other one needs to support monitor mode (on Linux). For example, the TP-LINK TL-WN722N supports both.

**Comment by johntheh4cker** [comment]
when i run wifiphisher then it close with "Interface "ALL" is controlled by NetworkManager.You need to manually set the devices that should be ignored by NetworkManager using the keyfile plugin (unmanaged-directive). For example, '[keyfile] unmanaged-devices=interface-name:"ALL"' needs to be added in your NetworkManager configuration file." message....how to fix this error..??

**Comment by blackHatMonkey** [comment]
Hi @johntheh4cker Take a look at #641.
