### ISSUE TITLE
addeting index html does not work ! 

### ISSUE THREAD

**Issue by loudjedi** [sophron/wifiphisher#343]
please help when i try to change the index html ! 
it does not work 
please help

**Comment by sophron** [comment]
Sorry, but it's hard to understand what you mean. What exactly are you trying to accomplish?

**Comment by unkownhesoka** [comment]
same issue when i try to change index.html in oauth-login and when i access fake AP it shows me the default webpage from oauth-login not the one i edited

**Comment by sophron** [comment]
You are probably receiving a cached version. Ctrl + F5 on your browser should refresh the page with the edited contents for you.

**Comment by unkownhesoka** [comment]
no it didnt wor even i tried connect from my tablet to fake AP and still giving me the default page

**Comment by sophron** [comment]
If you are running the tool after installing it in your system, using `python setup.py install`, you need to make sure you are editing the files in the installed directory (e.g. under `/usr/local/lib/python2.7/dist-packages`). Otherwise, you can run the script with `python bin/wifiphisher`.

**Comment by unkownhesoka** [comment]
thanks it work
