### ISSUE TITLE
cant creat fake AP

### ISSUE THREAD

**Issue by unkownhesoka** [sophron/wifiphisher#345]
well i have two adapter  

> wlp3s0    Link encap:Ethernet  HWaddr 62:5a:d0:09:42:42  
          inet addr:192.168.1.105  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::dfb2:e7ed:b826:3059/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1400  Metric:1
          RX packets:33451 errors:0 dropped:566 overruns:0 frame:0
          TX packets:29946 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:35558203 (35.5 MB)  TX bytes:4147856 (4.1 MB)  

> 

 

> wlx983f9f221d7e Link encap:Ethernet  HWaddr 98:3f:9f:22:1d:7e  
>           UP BROADCAST MULTICAST  MTU:1400  Metric:1
>           RX packets:342 errors:0 dropped:86 overruns:0 frame:0
>           TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000 
>           RX bytes:53635 (53.6 KB)  TX bytes:0 (0.0 B) 

when i use  `python wifiphisher.py -aI wlp3s0 -jI wlx983f9f221d7e`
it jam the signal but it doesnt create fake AP 
and when i use the other way around `python wifiphisher.py -aI wlx983f9f221d7e -jI wlp3s0`
it doesnt even jam the signal

**Comment by sophron** [comment]
Don't use version 1.1. Clone and use the latest revision instead.

**Comment by unkownhesoka** [comment]
> Don't use version 1.1. Clone and use the latest revision instead

i didnt get

**Comment by sophron** [comment]
Okay, please check the other issue.
