### ISSUE TITLE
Pre-shared key checking possibility

### ISSUE THREAD

**Issue by dennishrv** [sophron/wifiphisher#347]
I am not sure if this is the right place to put this question so excuse me if it is wrong. I was thinking would it be possible to check given password against target AP? Usually when script gets password from user it shuts down. Would it be possible to check password first, and then if it is valid one, script shuts down. Otherwise it replies with error message to user asking for correct pore-shared key

**Comment by sophron** [comment]
This has been an issue already (#321).
