### ISSUE TITLE
Add some installation and usage instructions to README

### ISSUE THREAD

**Issue by E3V3A** [sophron/wifiphisher#348]
Please provide some installation and usage instructions in the README.

**Comment by Vigilence** [comment]
I think this project was abandoned a few months ago.

**Comment by E3V3A** [comment]
@sophron Is that true or are you just busy?

**Comment by sophron** [comment]
@E3V3A What exactly you want to be explained better? There's already a "Usage" section.

@Vigilence No and I'm not sure what led you to that conclusion. This is an open-source project. Developers usually have a full-time job and contribute on their spare time.

**Comment by Vigilence** [comment]
@sophron  I am glad to see your back.  This project hasn't been updated in several months and no messages from you made.  I deeply understand people have lives outside of these projects, but when no comments are made we conclude the project is abandoned like so many others.  See linset as an example.

**Comment by E3V3A** [comment]
> What exactly you want to be explained better? There's already a "Usage" section.

Hi @sophron I know this was built for Kali, but I was hoping to port this and make it work on an out-of-the-box Raspberry Pi 3. 

- What are the specific hardware requirements?
- Do the wifi cards also need **injection** capabilities, or is *monitoring* enough?
- What HW info is needed?
- What are the dependencies?

Usually, *installation* instructions are written in the form:
```bash
git clone https://github.com/sophron/wifiphisher.git
cd wifiphisher
sudo ./**something**
```

Then some *examples* of command lines for running it (since you have many options there).

**Comment by sophron** [comment]
Thanks for explaining it, I'll push a new version of README soon.

**Comment by sophron** [comment]
Hi @E3V3A,

I just pushed a new version of README. Please let me know if any information is missing or not clear.

**Comment by sophron** [comment]
I'm closing this. Feel free to re-open if you need additional information.
