### ISSUE TITLE
bad ssl cert warnings from browsers

### ISSUE THREAD

**Issue by oscalation** [sophron/wifiphisher#35]
upon first connection it seems almost impossible to get a user to the fake router update pages without first getting the "insecure connection" error in most browsers. 

Cant you redirect all traffic to the router login/update page first to prevent this?

**Comment by sandman6578** [comment]
it already redirects all traffic to the fake page but some Webservers dont accept insecure(http) connections. 
try
www.google.com

**Comment by sophron** [comment]
Hi, this is not possible. When the attacker becomes MiTM it needs to present a self-signed certificate for SSL connections.

**Comment by testica** [comment]
A solution would be use a database to catch the password and not use a sniffer... I think.

**Comment by sophron** [comment]
@testica I'm not sure i understand your solution. Again, there is no way to avoid the warning from the browsers.

**Comment by testica** [comment]
In this case, I think browsers shows warnings because detect a sniffer. Some Evils Twins methods implements database to save the passwords and not sniffing the network to catch GET HTTP. Maybe I'm wrong but will be possible replace sniffer method by database, or use sniffer is essential?
