### ISSUE TITLE
wifiphisher closing

### ISSUE THREAD

**Issue by Omarovhunt** [sophron/wifiphisher#353]
somebody help me please?
root@kali:~# wifiphisher
[*] Starting Wifiphisher 1.1GIT at 2016-10-12 07:20
[!] There are not enough wireless interfaces for the tool to run! Please ensure that at least two wireless adapters are connected to the device and they are compatible (drivers should support netlink). At least one must support Master (AP) mode and another must support Monitor mode.
Otherwise, you may try --nojamming option that will turn off the deauthentication phase.
[!] Closing

**Comment by kelwin17** [comment]
same here..

**Comment by sophron** [comment]
Hi guys,

As you can see in the Requirements section on the README, you need two wireless cards to run the tool.

> * One wireless network adapter that supports AP mode. Drivers should support netlink.
> * One wireless network adapter that supports Monitor mode and is capable of injection. Again, drivers should support netlink. If a second wireless network adapter is not available, you may run the tool with the --nojamming option. This will turn off the de-authentication attack though.
