### ISSUE TITLE
Device or resource busy. Make sure your card is up..? 

### ISSUE THREAD

**Issue by thisisALPINE** [sophron/wifiphisher#354]
**Distribution**: Ubuntu 16.04 running on MacBook Pro (early 2015)

**Summary**: When I run wifiphisher with the following command 'sudo wifiphisher -aI xx -jI xx' it gives me this problem. I already disconnected the network devices from internet, and I don't really know in what else could they be busy.

![forgithub](https://cloud.githubusercontent.com/assets/12964909/19345896/f59ad13e-9140-11e6-9469-bf04f9311a77.png)

**Expected VS actual behavior**: I expected it to run normally, but it isn't.
**Script output**:

**Comment by sophron** [comment]
There are some processes that might interfere. You can try stopping your network manager completely from running. Or even better, if you have airmon-ng installed, you can try running `airmon-ng check kill`.

**Comment by thisisALPINE** [comment]
Thanks a lot! It worked perfectly!!
