### ISSUE TITLE
Error while executing setup

### ISSUE THREAD

**Issue by zipippino** [sophron/wifiphisher#355]
Hi, i'm using BackBox , latest version.
I open the folder in terminal , so i write "sudo python setup.py install" and here what happens:

francesco@backboxfrancesco:~/Scrivania/wifiphisher-master$ sudo python setup.py install
[sudo] password for francesco: 
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

What should i do?

**Comment by sophron** [comment]
You can try `sudo apt-get install python-setuptools`.

**Comment by zipippino** [comment]
A other process makes it unaivable

Sent by Francesco Buccoliero's iPad Air

**Comment by sophron** [comment]
@zipippino I'm not sure understand what you mean. Are you having a different error now?

**Comment by zipippino** [comment]
Yes but nowi have power off pc. It says i can't do it (installing python tools) because another process prevents it

Sent by Francesco Buccoliero's iPhone 

**Comment by sophron** [comment]
This is not an issue regarding Wifiphisher though. I recommend you asking a different forum.
