### ISSUE TITLE
hi please help ! its was working fine until this !! 

### ISSUE THREAD

**Issue by loudjedi** [sophron/wifiphisher#359]
![screenshot from 2016-10-24 15-33-49](https://cloud.githubusercontent.com/assets/20914496/19649944/90a7e81c-99ff-11e6-83de-9485820229cc.png)

**Comment by sophron** [comment]
Your device is either Soft Blocked or Hard Blocked. Check with `rfkill list all`. You can try unblocking it with `sudo rfkill unblock wlan` or reconnecting the card.

**Comment by loudjedi** [comment]
am soft blocked how do i unblock ?

**Comment by sophron** [comment]
As I have already written, try `sudo rfkill unblock wlan`. Subtitute `wlan` with your interface name.

**Comment by loudjedi** [comment]
done thanks bro 
close this issue
