### ISSUE TITLE
Everything works great but I still can't connect my devices to the rogue ap

### ISSUE THREAD

**Issue by fafualex** [sophron/wifiphisher#36]
Everything works great but I still can't connect my devices to the rogue ap, I see two networks with the same SSID, the rogue ap wich is the open one and the original network, my devices gets disconnected from the original but when the devices tries to reconnect to the open they fail.
I launch the command without any flags, I'm using an alfa network awus036h chipset rtl8187 for monitor mode and jamming devices and my laptop internal wifi card Ralink RT3290 for rogue ap. Hoping for an help ;) great job however.

**Comment by sandman6578** [comment]
try to change it take the ralink as accesspoint and the alfa for jamming with these commands
python wifiphisher.py - aI wlanX(ralink)  - jI wlanX (alfa)

**Comment by sandman6578** [comment]
o sry read false

**Comment by sandman6578** [comment]
kill networkmanager and give your AP card an ip with ifconfig wlanX (fill in the x with the number) 10.0.0.1

**Comment by fafualex** [comment]
I'm still not able to connect to my AP.. I think that's my internal Ralink that doesn't support it.. maybe it's because monitor mode gotta be enabled on both card interfaces but my ralink doesn't have it..

**Comment by sophron** [comment]
Hi @fafualex,

Thanks for reporting. There's already ticket #29 for this.
