### ISSUE TITLE
Import error:No module named scapy.all

### ISSUE THREAD

**Issue by Verg92** [sophron/wifiphisher#360]
Sorry if this isn't the right place to post but after launching "python setup.py" i got this message:

_"Import error:No module named scapy.all"_

So i typed _"apt-get install python-scapy"_ and then the error become:

_"Import error:No module named setuptools"_

Then i typed _"apt-get install python-setuptools"_ but nothing changed.
I get the last error everytime.
Any suggestions? Thank you in advance ( and sorry for my bad english =(  )
You guys are amazing, hope one day i can learn at least half the knowledge of yours.

PS: Already launched _apt-get dist-upgrade_

**Comment by sophron** [comment]
Hi,

You don't mention your distro but I suppose it's Debian-based. Is `python-setuptools` installed properly after you run the `apt-get` command?

Excuse my late response. :)

**Comment by sophron** [comment]
Feel free to re-open if needed.
