### ISSUE TITLE
Request: Allow one interface usage

### ISSUE THREAD

**Issue by crazyboogs** [sophron/wifiphisher#361]
Would it be possible to allow for wifiphisher to run when only one interface is available? Perhaps the user would need to specify whether it is the jamming interface or access point interface at run time.

My reason for this is that I would like my jamming interface to be on a separate device than my access point interface.

**Comment by jnaulty** [comment]
In the README.md:

```
One wireless network adapter that supports Monitor mode and is capable of injection. Again, drivers should support netlink. If a second wireless network adapter is not available, you may run the tool with the --nojamming option. This will turn off the de-authentication attack though.
```

**Comment by crazyboogs** [comment]
Thanks for pointing that out.
