### ISSUE TITLE
Index files failed to download.

### ISSUE THREAD

**Issue by djdisikd** [sophron/wifiphisher#363]
![img_20161112_165951](https://cloud.githubusercontent.com/assets/17978000/20236756/cf259e98-a884-11e6-91c5-d40e76ec2e32.jpg)

**Comment by djdisikd** [comment]
Please close this issue

**Comment by djdisikd** [comment]
Please close this issue

**Comment by johkeidude** [comment]
Can i use tl-wn722n will this work

16.11.2016 11.31 "toh" <notifications@github.com> kirjoitti:
