### ISSUE TITLE
oauth - Phishing Page - Facebook png file not display

### ISSUE THREAD

**Issue by cupiddidi** [sophron/wifiphisher#364]
Hello

Experience the phishingpage's facebook logo unable to display in both laptop and mobile devices.

Appreciated if anyone can point me to the right direction.

Thank you.

**Comment by Ie0h** [comment]
Same issue here, URL shows http://go.microsoft.com/logos/facebook-logo.png which is correct spelling and everything so I am at a loss.

**Comment by sophron** [comment]
Thanks for reporting. Will push a fix soon.

**Comment by Ie0h** [comment]
Also please note it is more than just the logo it is the whole page being broken, nothing is lined up or centered like it shows on my linux box opening the HTML. all on the left hand side in plain text.

**Comment by sophron** [comment]
Thanks. What distro are you using and which browser have you tested this on?

**Comment by Ie0h** [comment]
Kali shows the page fine,

On Windows 10 using Chrome it does not show properly. 

Have not tested on other browsers but I can do that later, bout to jump on a plane.

**Comment by sophron** [comment]
That's fine, I'll have a look later. Travel safe.

**Comment by kbeflo** [comment]
Also tested this on a Raspberry Pi 3 B, running raspbian-jessie-lite using 2 Ralink RT5370 wireless adapters, oauth-login currently not working properly.

**Comment by djdisikd** [comment]
I have the same problem too.

**Comment by sophron** [comment]
Should be good now.

**Comment by cupiddidi** [comment]
@sophron Hello Sophron, firstly thanks for your quick attention to the reported issue. But I have tried again it still never show the Facebook logo. I am using Apple iOS 10.1.1 open in Safari browser.

I re-download the entired WifiPhisher and run but it still the same.

Hope you can assist us here again.

Thank you

**Comment by sophron** [comment]
Hi @cupiddidi,

Are you downloading the latest revision using `git clone`? Also, make sure you hit ctrl+f5 on your browser to verify you are not in browser's cache.

**Comment by cupiddidi** [comment]
![photo 24-11-16 4 30 48 pm](https://cloud.githubusercontent.com/assets/23649192/20591870/b4a7cf42-b265-11e6-9841-a09c119f31e7.jpg)

Hi @sophron Yes, I have clone it again entirely but still no luck. I using iPhone with iOS, once connected to the fake AP it will then automatic open the Safari browser. Anywhere I might be missed? Thanks.

**Comment by sophron** [comment]
I can't replicate this. Are you sure your are not in cache? Try hitting something else in the address bar and see how it works.

**Comment by sophron** [comment]
Hm, I think I found a case where this may occur. I just pushed a fix. Can you try again and let me know?
