### ISSUE TITLE
don't get password

### ISSUE THREAD

**Issue by dienpv58** [sophron/wifiphisher#366]
Hi all,
I have a question about don't getting password.
When victim enter password and then click "start upgrade" button. I only seen GET method
ex:
HTTP requests
[*] GET 10.0.0.62
[*] GET 10.0.0.62
[*] GET 10.0.0.62
[*] GET 10.0.0.62 
victim entered passwd and sent passwd, it not show: [*] POST 10.0.0.62 pass=xxxxxx
i used firmwave upgrade method.
what happen? And how to fix this?
so sorry because my english not well
Thanks.

**Comment by sophron** [comment]
Which version are you using?

Make sure that Javascript is enabled on your browser.

**Comment by sophron** [comment]
I'm closing this. Feel free to re-open if needed.

**Comment by phamdien** [comment]
i am using latest wifiphisher version, and my browser is firefox on kali linux

**Comment by phamdien** [comment]
javascript is enable
