### ISSUE TITLE
Fake Authentication Page Only Working on iPhones and iPads

### ISSUE THREAD

**Issue by JumboPeak** [sophron/wifiphisher#367]
Version: Wififisher 1.1 and newest version.

Current distribution: Kali 2916.2 (However I had this issue on older versions of Kali)

Ok so I've had success using wifiphisher but this was when an iPhone connected to my AP and displayed the fake page and I got their password. However I noticed that I only ever got DHCP leases from either iPhones or iPads and never PCs etc.

I've recently started using the tool again and have done some home testing and I have the exact same issue. I jam all devices on my network which is fine however I'm opening multiple web pages on my PC and I either can't connect to the website (not connecting to my AP) or the page manages to load. Please note my router pc and network cards are all in the same room with very strong signal strength.

So I go over to my iPhone which has disconnected me from my wifi. When I connect again and browse to a page I get adn instand DHCP lease and the iphone connects to my AP with the fake log in page and I can get the password. 

I saw a note on Nullbyte stating 'The big problem is HSTS detect on chrome an firefox'. Could this be the problem?

**Comment by sophron** [comment]
Hi,

What exactly is happening when you click to connect on the network from your PC? HSTS is a countermeasure that you cannot easily bypass but has nothing to do with your case.

Also, make sure you are using the latest 1.2 version.

**Comment by jeretc** [comment]
i made a fake page template that works well with Rogue_AP :

https://github.com/jeretc/fake-portal

**Comment by sophron** [comment]
@JumboPeak I'll now close this issue. Feel free to re-open if necessary.
