### ISSUE TITLE
How to clear the DHCP Leases?

### ISSUE THREAD

**Issue by Criticize** [sophron/wifiphisher#369]
When running a new instance of wifiphisher following the successful MITM penetration.  The previous DHCP Lease addresses including the MAC addresses of the previous victims show up under "DHCP_Leases:" How do I clear those out? OR Where is the .conf file to delete them?

Thanks!

**Comment by sophron** [comment]
Hi @Criticize,

You can try removing /var/lib/misc/dnsmasq.leases file for now. We should probably clear the leases when the script terminates. I'm adding to our list.

**Comment by laozi999** [comment]
I've added a fork to clear the DHCP leases when you launch wifiphisher:

[https://github.com/sophron/wifiphisher/compare/master...laozi999:patch-1](https://github.com/sophron/wifiphisher/compare/master...laozi999:patch-1)

**Comment by sophron** [comment]
@laozi999 Feel free to make a PR for this too.
