### ISSUE TITLE
i cant use it

### ISSUE THREAD

**Issue by martan122** [sophron/wifiphisher#37]
when i do python wifiphisher.py it say
root@Pachenko:~/Desktop/wifi# python wifiphisher.py
[*] isc-dhcp-server not found in /usr/sbin/hostapd, install now? [y/n] y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package hostapd is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'hostapd' has no installation candidate
[*] Starting HTTP server at port 8080
[*] Starting HTTPS server at port 443
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "wifiphisher.py", line 738, in <module>
    sniffing(mon_iface, targeting_cb)
  File "wifiphisher.py", line 319, in sniffing
    sniff(iface=interface, prn=cb, store=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 561, in sniff
    s = L2socket(type=ETH_P_ALL, *arg, **karg)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 455, in __init__
    self.ins.bind((iface, type))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 19] No such device

 
my cards are 

wlan0		Atheros AR9285	ath9k - [phy0]
wlan1		Atheros AR9271	ath9k - [phy4]  this for injection 

and please give me tut on how to use the script

**Comment by martan122** [comment]
and this happen too

[+] Ctrl-C at any time to copy an access point from below
num  ch   ESSID
---------------
1  - 4  - Etisalat-Jkie
^C   
[+] Choose the [num] of the AP you wish to copy: 1
[*] Starting the fake access point...
Traceback (most recent call last):
  File "wifiphisher.py", line 745, in <module>
    start_ap(ap_iface, channel, essid, args)
  File "wifiphisher.py", line 377, in start_ap
    Popen(['hostapd', '/tmp/hostapd.conf'], stdout=DN, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
root@Pachenko:~/Desktop/wifi#

**Comment by martan122** [comment]
also doing thiis 

[+] Ctrl-C at any time to copy an access point from below
num  ch   ESSID
---------------
1  - 4  - Etisalat-Jkie
^C   
[+] Choose the [num] of the AP you wish to copy: 1
[*] Starting the fake access point...
Traceback (most recent call last):
  File "wifiphisher.py", line 745, in <module>
    start_ap(ap_iface, channel, essid, args)
  File "wifiphisher.py", line 377, in start_ap
    Popen(['hostapd', '/tmp/hostapd.conf'], stdout=DN, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
root@Pachenko:~/Desktop/wifi#

**Comment by sibichakkaravarthy** [comment]
SIOCDDRT : Network is unreachable
Starting the fake access point...
Traceback (most recent call last):
File "wifiphisher.py", line 745, in
start_ap(ap_iface, channel, essid, args)
File "wifiphisher.py", line 377, in start_ap
Popen(['hostapd', '/tmp/hostapd.conf'], stdout=DN, stderr=DN)
File "/usr/lib/python2.7/subprocess.py", line 679, in init
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory

Same Error i am also facing. I tried to install hostapd manually in Kali linux but the result goes in vain 
Resulting with hostapd does not have installation candidate.
![erro](https://cloud.githubusercontent.com/assets/3365954/5676199/72381318-97f7-11e4-926a-c21659011618.jpg)

**Comment by sandman6578** [comment]
you have to add the repository to your sources list

**Comment by sibichakkaravarthy** [comment]
Sandman6578

Can you explain it clearly. I am Not getting you

I ve tried installing hostapd, libnl, isc-dhcp-server but all goes in vain . Please help me out


Thanks in advance


Regards

**Comment by mvrutaal** [comment]
Hi Guys, I am having the same problem as "sibichakkaravarthy".

@ sandman6578: can you explain in more details what you mean with "you have to add the repository to your source list" ? 
I myself am also new to this, I am practicing. Your help is much apreciated.
Thx a lot.

**Comment by sandman6578** [comment]
look at issue #41 theres the solution

**Comment by sophron** [comment]
Hi guys,

As mentioned, you need to install hostapd for the script to work on Kali. Check how to add the Kali repositories to your sources.list.

**Comment by lashze** [comment]
unable to do this
   git clone https://github/sophron/wifiphisher


showing 

root@kali:~# git clone https://github/sophron/wifiphisher
Cloning into 'wifiphisher'...
fatal: unable to access 'https://github/sophron/wifiphisher/': Could not resolve host: github

**Comment by sandman6578** [comment]
git clone https://github{.COM}/sophron/wifiphisher

you forgot the (dot)com

**Comment by astra22** [comment]
hi

**Comment by astra22** [comment]
i need help

**Comment by astra22** [comment]
need help

**Comment by astra22** [comment]
Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for wifiphisher==1.2
[*] hostapd not found in /usr/sbin/hostapd, install now? [y/n] y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 google-chrome-stable : Depends: libappindicator1 but it is not going to be installed
 hostapd : Depends: libssl1.0.2 (>= 1.0.2d) but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

[-] Unable to install the 'hostapd' package!
[*] This process requires a persistent internet connection!
Please follow the link below to configure your sources.list
http://docs.kali.org/general-use/kali-linux-sources-list-repositories
[+] Run apt-get update for changes to take effect.
[+] Rerun the script to install hostapd.
[!] Closing
root@RahulYadav-PC:/home/astra/wifiphisher# 


help me please
