### ISSUE TITLE
[QUESTION] How to select wlan1 when simply spawn an open AP?

### ISSUE THREAD

**Issue by wikijm** [sophron/wifiphisher#370]
**Version**: commit cf097ccc256bcfe8ad2bebcce04fbe024a115633

**Distribution**: Linux RaspAP3 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT 2016 armv71 GNU/Linux

**Summary**: How to select specific wlan interface when simply spawn an open AP?

**Description**: I don't know how to select a specific wlan interface when I try to simply spawn an open AP. Automatically, WifiPhisher select wlan0, which I use to connect and control my Raspberry Pi 3 over SSH.

**Steps to Reproduce**: Start WifiPhisher with this command:
`wifiphisher --nojamming --essid "FREE WI-FI" -p oauth-login`

**Expected VS actual behavior**:
```
[*] Selecting wlan1 interface forcreating the rogue Access Point
VS
[*] Selecting wlan0 interface forcreating the rogue Access Point
```

**Script output**: N/A

**Comment by sophron** [comment]
Thanks for reporting this.

There is `--apinterface`  but it won't really work as it conflicts with the `--nojamming`. I will push a fix soon.

**Comment by sophron** [comment]
Just pushed a commit that fixes this. You should be able to use `--apinterface` using the latest revision now . This will of course work only if the given interface does support AP mode.

**Comment by wikijm** [comment]
Works like a charm for choosing interface. 

New issue: Wifiphisher won't get IP to the victimes. I need more test to check this.


Thanks for your wonderful job !
