### ISSUE TITLE
Custom phishing scenario.

### ISSUE THREAD

**Issue by LeXaaN73** [sophron/wifiphisher#378]
Fluxion has sites 'vodafone-esp' , how to add in wifiphisher?Sorry for my English, I translate through google translator

**Comment by hg8** [comment]
Please see "**Creating a custom phishing scenario**" in https://github.com/sophron/wifiphisher/blob/master/docs/wifiphisher.txt

**Comment by LeXaaN73** [comment]
I created config.inibut the program does not see.Something in the script may need to be changed.Why I ask

**Comment by LeXaaN73** [comment]
wifiphisher/wifiphisher/data/phishing-pages/vodafone-esp.In this way I put config.ini

**Comment by hg8** [comment]
Name it _config.ini_ not _vodafone-esp.ini_.

**Comment by LeXaaN73** [comment]
config.ini I put in a folder vodafone-esp. and does not work
