### ISSUE TITLE
Hostapd restart

### ISSUE THREAD

**Issue by wvthoog** [sophron/wifiphisher#396]
hi,

i'm using a Raspberry Pi 3 and like to use it as a mobile Fake Access Point using Wifiphisher. The problem i'm facing is that when i start Wifiphisher it kills the original Hostapd process which i use to connect to, to initialize wifiphisher. So how do i append a Wifiphisher configuration file with my own (wlan0 raspberry pi 3 onboard wifi) access point, or maybe prevent Wifiphisher to kill the original Hostapd. (which is run at boot)

Second question: Is there a way to launch Wifiphisher in a background process and let it write to a log file with the captured credentials ?

The thing i'd like to accomplish is, take the Pi in my backback. Move around and capture oauth-login credentials.

-Using Kali Linux 2
-2 TP-Link WN722N USB adapters

Thanks in advance!

**Comment by laozi999** [comment]
Why are you trying to run 2 access points on the same interface? As far as I know that's not possible.

**Question 1**
When you run Wifiphisher, it automatically configures hostapd for you, so there's no need to configure your own. You can change the hostapd settings of Wifiphisher in `/wifiphisher/wifiphisher/pywifiphisher.py` on `line 437`.

**Question 2**
This is a good idea, would be a nice addition. I know that wifiphisher does print the credentials when you terminate (ctrl + c) the process.

For now you can launch a PHP script when the user submits the form, and save those credentials in a log file on your web server.

You would need to change the permissions of the log file to give writing access to the www-data user group, like so:

Change permissions:

`chown -R www-data:www-data /path/to/log.txt`
`chmod -R 775 /path/to/log.txt`

Disable executing (safety):

`chmod -X /path/to/log.txt`

**Comment by wvthoog** [comment]
@laozi999 

**Question 1**

i'm not trying to run two accesss points at the same interface, but rather want to use the on board interface as a hotspot (wlan0) to connect my phone/laptop to in order to login with ssh (for example)

so my setup is like this. The onboard interface (wlan0) is used for a static access point for myself to log into the Pi. The second and third interface (tp-link wn722n usb wlan1/wlan2) are used for wifiphisher. 

i've tried to append my hostapd configuration at /wifiphisher/wifiphisher/pywifiphisher.py but hostapd needs to have a configuration file for each access point. Wifiphisher launches /etc/hostapd.conf but it also needs to launch /etc/hostapd/hostapd.conf (second hostapd process) for my own (private) access point for me to connect to. 

`nano /usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py`

```
    with open('/tmp/hostapd.conf', 'w') as dhcpconf:
        dhcpconf.write(config % (mon_iface, essid, channel))

    hostapd_proc = Popen(['hostapd', '/tmp/hostapd.conf'],
                         stdout=DN, stderr=DN)
```

so i need some code to also launch a second hostapd process running /etc/hostapd/hostapd.conf 

also, if i crtl-c out of wifiphisher it should relaunch hostapd with /etc/hostapd/hostapd.conf or only kill the wifiphisher hostapd process. Maybe only killing the wifiphisher hostapd process at the startup of wifiphisher would prevent me from fiddling with wifiphisher/pywifiphisher.py as my original hostapd (/etc/hostapd/hostapd.conf) would not be killed.

**Question 2**

sounds good, i will take a look at that

**Comment by laozi999** [comment]
Ok.

A few things:

1. Wifiphisher kills the `airbase-ng`, `dnsmasq` and `hostapd` processes on launch
2. Wifiphisher resets the iptables on launch

The best way is to let Wifiphisher reset everything, then set up both APs for you.

You will have to configure your other AP (iptables, hostapd & dnsmasq) accordingly in pywifiphisher.py

**Comment by laozi999** [comment]
Made me think of a cool feature:

Have wifiphisher ask how many access points you want to set up on launch.

**Comment by wvthoog** [comment]
just a little update. I've been doing some fiddling the last few days and came up with this

like @laozi999 mentioned. Replacing `subprocess.call('pkill hostapd', shell=True)` with `#subprocess.call('pkill hostapd', shell=True)` prevents Wifiphisher killing my original Hostapd process and only kills it own while CRTL-C out of Wifiphisher. So problem solved there

Capturing the credentials is a two way answer. Since i can't launch Wifiphisher in the background and in need to CRTL-C out of the process i've done two thing. 

1: added the line to pywifiphisher.py
```
for c in phishinghttp.creds:
print c
f = open('creds', 'w')
f.write(c)
```

2: maybe more important and making 1: irrelevant. Use the linux command `screen`
so first i run screen when in log into a shell. Then i use the Wifiphisher command. (eg wifiphisher -jI wlan1 -aI wlan2 -p oauth-login) 

Quit ssh, not exit. Just click it away. Then i login back into ssh and type `screen -r` and voila. I'm back into the current running Wifiphisher process.

This is what i needed. Thanks for helping

**Comment by Mess69** [comment]
hi everyone,
am newbies with raspberry pi3 and wifiphisher too.
so i have problem when i try to run wifiphisher from my mobile phone android with ssh root access 
it run but show me screen with lines like : 
 _____lqqqqqqqqqqqq 
_____lqqqqqqqqqqqq
_____lqqqqqqqqqqqq
_____lqqqqqqqqqqqq
_____lqqqqqqqqqqqq

when i use wifiphisher from hdmi with screen it work well 
any advice plz ?
