### ISSUE TITLE
How can edit fake pages

### ISSUE THREAD

**Issue by Miayke** [sophron/wifiphisher#399]
hello i use last version but i need to edit html 

/root/wifiphisher/wifiphisher/data/phishing-pages

when i edit there pages it is dont work or when i delete pages still work anyone know where are they?

**Comment by cicina** [comment]
not quite sure what you mean, but to edit those files you would need basic understanding of web developing.

**Comment by Miayke** [comment]
no  i edit but when i start wifiphisher fake pages still same it can not change so page didn't update

sorry 4 english

**Comment by laozi999** [comment]
Make sure you're not mixing up 2 copies of wifiphisher.

You can ensure that you launch the correct one by specifying the python file:

`python /wifiphisher/bin/wifiphisher -e "Fake AP"`

instead of:

`wifiphisher -e "Fake AP"`
