### ISSUE TITLE
Correct README

### ISSUE THREAD

**Issue by michaelvs** [sophron/wifiphisher#40]
It is mentioned that you need two interfaces.Make it clear that you need two adapters.

**Comment by jalcine** [comment]
Couldn't you have one adapter, but have a monitor that could be used for injection like with `airmon-ng`?

**Comment by jalcine** [comment]
Wait, no, I get your stance. One for actually _connecting to_ the target AP and another to _attack_ it.

**Comment by michaelvs** [comment]
That's right

**Comment by jalcine** [comment]
Cool, just made a PR for it :)

**Comment by jalcine** [comment]
Let me know if that text makes sense.
