### ISSUE TITLE
i need reset after stop wifiphisher for start wlan?

### ISSUE THREAD

**Issue by Miayke** [sophron/wifiphisher#400]
hello when i stop wifiphisher after that i need to reset my pc for join internet anyone know how i can fix it

**Comment by cicina** [comment]
Hello, if you use Kali linux, quit wifiphisher
open terminal and type
1. ifconfig (check if your wlan is still in monitor mode)
2. if its in monitor mode, stop it first using airmon-ng stop wlan0mon (use interface you se in ifconfig, this is example)
3. service network-manager restart

if your card is not in monitor mode after you quit wifiphisher, (it shouldn't be)
then go straight to step 3. command will restart network manager so you can connect to wifi without rebooting your PC. cheers
