### ISSUE TITLE
how i can add new fake pages

### ISSUE THREAD

**Issue by Miayke** [sophron/wifiphisher#402]
When I make a new page it does not appear in the PHISHING SCENARIOS list 

 or when  I edit the page It does not change 

i put or edit there /root/wifiphisher/wifiphisher/data/phishing-pages

Where do i make mistakes

**Comment by ImDoode** [comment]
Did you find the answer?

**Comment by blackHatMonkey** [comment]
@Miayke @ImDoode Currently there is no easy way to do this. You must use the Github version of Wifiphisher. Then place the new scenario in `wifiphisher/data/phishing-pages` folder followed by `python install`.
