### ISSUE TITLE
i use old version's fake page  but 

### ISSUE THREAD

**Issue by Miayke** [sophron/wifiphisher#403]
i use old version's wifi fake page but its giving error no shows css and logo and when i write ( victim ) password it not shows i use config.ini too what i forget to do

wifi page old version

wifiphisher new version

srry 4 english

**Comment by sophron** [comment]
What exactly is the old-version WiFi page that you are using?

**Comment by Miayke** [comment]
fake page name "minimal" i add this one to new wifiphisher but its giving error not show password or css or logo

**Comment by Miayke** [comment]
I'm trying to add a different page, but it fails.  Example old version of the page or a different page

**Comment by laozi999** [comment]
make sure you have a `config.ini` file inside the folder of your site, and make sure that you change `config.ini` so that you can select the scenario with wifiphisher.

**Comment by laozi999** [comment]
Save this in your config.ini file:

```
[info]
Name: YOUR SCENARIO
Description: DESCRIBE YOUR SCENARIO

[context]
organization:
```

**Comment by sophron** [comment]
The `minimal` template that we used to support is not working indeed with the new version. You may be able to port it though by following the <a href="http://wifiphisher.org/docs.html">documentation</a>.

Is there a particular reason that you want to use that template? I consider the new `firmware-upgrade` scenario way more realistic.

**Comment by Miayke** [comment]
because if i attack router , router has 1 admin , 5 normal user if normal users down maybe they dont want to upgrade router

**Comment by laozi999** [comment]
https://github.com/sophron/wifiphisher/issues/238

This scenario will take care of that, adding a bit of legitimacy for mobile devices.

I've been taking longer than I had hoped to make a PR for this, but I think it's optimised sufficiently for attacks.

**Comment by Labseb** [comment]
Miayke: Don't forget with the latest wifiphiser to put all your CSS and logos in a "/static" directory

**Comment by sophron** [comment]
@Miayke I'm closing this. If you still encounter issues importing the old template, feel free to open a new one.
