### ISSUE TITLE
Can't install on Kali

### ISSUE THREAD

**Issue by Hemza** [sophron/wifiphisher#406]
OS: Kali Linux,

**Script output**: 

root@Anonymous:~/wifiphisher# sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to wifiphisher.egg-info/requires.txt
writing wifiphisher.egg-info/PKG-INFO
writing top-level names to wifiphisher.egg-info/top_level.txt
writing dependency_links to wifiphisher.egg-info/dependency_links.txt
writing entry points to wifiphisher.egg-info/entry_points.txt
reading manifest file 'wifiphisher.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'wifiphisher.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/wifiphisher
copying build/lib.linux-x86_64-2.7/wifiphisher/interfaces.py -> build/bdist.linux-x86_64/egg/wifiphisher
copying build/lib.linux-x86_64-2.7/wifiphisher/__init__.py -> build/bdist.linux-x86_64/egg/wifiphisher
copying build/lib.linux-x86_64-2.7/wifiphisher/constants.py -> build/bdist.linux-x86_64/egg/wifiphisher
copying build/lib.linux-x86_64-2.7/wifiphisher/pywifiphisher.py -> build/bdist.linux-x86_64/egg/wifiphisher
copying build/lib.linux-x86_64-2.7/wifiphisher/phishingpage.py -> build/bdist.linux-x86_64/egg/wifiphisher
creating build/bdist.linux-x86_64/egg/wifiphisher/data
creating build/bdist.linux-x86_64/egg/wifiphisher/data/cert
copying build/lib.linux-x86_64-2.7/wifiphisher/data/cert/server.pem -> build/bdist.linux-x86_64/egg/wifiphisher/data/cert
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/jquery.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/static/jquery.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/static/bootstrap.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/static/bootstrap.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/loading.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/bootstrap.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/bootstrap.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/index.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/config.ini -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/upgrading.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/static
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/static/update
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/static/update/update.exe -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/static/update
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/static/css/theme.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/static/css/bootstrap.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/static/css
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/static/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/static/js/jquery.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/static/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/static/js/bootstrap.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/static/js
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/static/images
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/static/images/plugins.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/static/images
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/static/images/favicon.ico -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/static/images
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/update
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/update/update.exe -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/update
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/css/theme.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/css/bootstrap.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/index.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/js/jquery.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/js/bootstrap.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/js
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/images
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/images/plugins.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/images
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/images/favicon.ico -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/images
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/config.ini -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/oauth.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/static
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/static/logos
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/static/logos/facebook-logo.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/static/logos
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/static/css/style.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/static/css/font-awesome.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/static/css/reset.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/static/css/roboto.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/static/css
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/static/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/static/js/jquery.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/static/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/static/js/index.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/static/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/loading.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/logos
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/logos/facebook-logo.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/logos
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/css/style.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/css/font-awesome.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/css/reset.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/css/roboto.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/index.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/js/jquery.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/js/index.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/license.txt -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/config.ini -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/style.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/mac-network-manager.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/wifi-icon.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/static/style.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/static/mac-network-manager.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/static/wifi-icon.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/static/question.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/static/win-behavior.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/static/opensans.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/static/dinosaur.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/static/opensans.ttf -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/static/behavior.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/static/chrome-offline.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/question.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/loading.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/win-behavior.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/opensans.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/dinosaur.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/index.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/opensans.ttf -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/behavior.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/config.ini -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/chrome-offline.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
creating build/bdist.linux-x86_64/egg/wifiphisher/data/logos
copying build/lib.linux-x86_64-2.7/wifiphisher/data/logos/linksys.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/logos
copying build/lib.linux-x86_64-2.7/wifiphisher/data/logos/cisco.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/logos
copying build/lib.linux-x86_64-2.7/wifiphisher/data/logos/netgear.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/logos
copying build/lib.linux-x86_64-2.7/wifiphisher/data/logos/tplink.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/logos
copying build/lib.linux-x86_64-2.7/wifiphisher/data/logos/dlink.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/logos
copying build/lib.linux-x86_64-2.7/wifiphisher/data/logos/asus.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/logos
copying build/lib.linux-x86_64-2.7/wifiphisher/data/wifiphisher-mac-prefixes -> build/bdist.linux-x86_64/egg/wifiphisher/data
copying build/lib.linux-x86_64-2.7/wifiphisher/macmatcher.py -> build/bdist.linux-x86_64/egg/wifiphisher
copying build/lib.linux-x86_64-2.7/wifiphisher/phishinghttp.py -> build/bdist.linux-x86_64/egg/wifiphisher
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/interfaces.py to interfaces.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/constants.py to constants.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/pywifiphisher.py to pywifiphisher.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/phishingpage.py to phishingpage.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/macmatcher.py to macmatcher.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/phishinghttp.py to phishinghttp.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
wifiphisher.constants: module references __file__
creating 'dist/wifiphisher-1.2-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing wifiphisher-1.2-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg
Extracting wifiphisher-1.2-py2.7.egg to /usr/local/lib/python2.7/dist-packages
wifiphisher 1.2 is already the active version in easy-install.pth
Installing wifiphisher script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg
Processing dependencies for wifiphisher==1.2
Searching for blessings
Reading https://pypi.python.org/simple/blessings/
Download error on https://pypi.python.org/simple/blessings/: [Errno 101] Network is unreachable -- Some packages may not be found!
Couldn't find index page for 'blessings' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno 101] Network is unreachable -- Some packages may not be found!
No local packages or download links found for blessings
error: Could not find suitable distribution for Requirement.parse('blessings')
root@Anonymous:~/wifiphisher#

**Comment by laozi999** [comment]
`pip install blessings`

[https://github.com/sophron/wifiphisher/issues/389](https://github.com/sophron/wifiphisher/issues/389)

[https://github.com/sophron/wifiphisher/issues/386](https://github.com/sophron/wifiphisher/issues/386)

**Comment by laozi999** [comment]
If you don't have pip installed

`gem install pip`

**Comment by Hemza** [comment]
i've used : pip install blessings  --proxy http://user:pass@proxyAddress:proxyPort

it was installed with success
