### ISSUE TITLE
Cant load CSS on template

### ISSUE THREAD

**Issue by fearedteddz** [sophron/wifiphisher#407]
Greetings. I've installed the script and then modified the firmware-upgrade scenario template in order to make it look more realistic with the router vendors I've been testing in my area. Didn't change much to the Index.html file, just the path for the bootstrap.min.css, bootstrap.min.js and jquery.min.js after installation. Also replaced the default vendor PNG with one of my choice. The thing is, i cant get the CSS or PNG to load up when I run the script with the webserver. If I click on the Index.html file and run it locally on the browser of the machine I'm using to run the script, the webpage is displayed correctly. Everything works flawlessly, fake AP is created, DHCP and HTTP server are running, but when i connect to the fake AP from another device and open the browser, the webpage is displayed without the CSS content or the PNG, so everything looks all messed up. Plain text that was modified in the Index.html file DOES show changes, but the CSS is missing so all the content and the top menu bar is all messed up. I've modified the path several times with no results. Where does the script execute the webpage from? I know its not in the var/www directory. The path im using for the files is: 

link rel="stylesheet" href="/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/data/phishing-pages/firmware-upgrade/bootstrap.min.css"

script src="/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/data/phishing-pages/firmware-upgrade/jquery.min.js"

script src="/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/data/phishing-pages/firmware-upgrade/bootstrap.min.js"

img src="/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/data/phishing-pages/firmware-upgrade/router.png"

**Comment by sophron** [comment]
Hi @fearedteddz,

Which version are you using? 

If you are using the latest development version you will have to put all your included files under the `static` directory. See how the other scenarios are structured.

In either case, you should include the files using relative paths (instead of absolute). For example, "/static/jquery.min.js" instead of "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/data/phishing-pages/firmware-upgrade/bootstrap.min.css".

I'm curious on the changes that you made in the scenario to make it more realistic. If you feel that others could benefit from them, feel free to make a Pull Request.

**Comment by laozi999** [comment]
If a victim had access to your root folder, that'd be extremely risky

**Comment by laozi999** [comment]
@sophron, the wifi_connect scenario is brilliant, but the CSS needs some refining, I wouldn't personally fall for it when I look at the input outlines or the checkboxes, buttons, or the font. I will optimise this to make it look 99% like Mac OS :+1:

**Comment by sophron** [comment]
@laozi999 This issue refers to the `firmware-upgrade` scenario (not the `wifi_connect`). Great, feel free to make improvements in any of them.

**Comment by laozi999** [comment]
Happily!

I have just made a new PR for the device-modal scenario.

That's what I'm calling it, but change it to your liking :)

**Comment by fearedteddz** [comment]
@sophron , Thanks for that tip! Everything works perfect now! I didn't change much to the original template, just edited some plain text in the index.html and changed the vendor PNG to match it to the routers in my area and the SSID of the router. Used the same CSS style and layout. I don't know much about CSS/HTML coding, just some basic mods, but I'm watching tutorials from w3schools and will definitely be working on making some major modifications in the future as I improve my coding skills. Thanks for your help and this amazing script!

<a href='https://postimg.org/image/g2hvehaoz/' target='_blank'><img src='https://s29.postimg.org/4q59wp207/Screenshot_from_2017_01_11_22_11_30.png' border='0' alt='Screenshot from 2017-01-11 22-11-30'/><br /><br /><br />

<a href='https://postimg.org/image/58jv3a6xv/' target='_blank'><img src='https://s29.postimg.org/d1aiv9cx3/Screenshot_from_2017_01_11_22_09_01.png' border='0' alt='Screenshot from 2017-01-11 22-09-01'/><br /><br /><br />

**Comment by sophron** [comment]
@fearedteddz Sure, no problem!
