### ISSUE TITLE
SIOCADDRT:network is unreachable

### ISSUE THREAD

**Issue by RolandBrake** [sophron/wifiphisher#41]
when i use python wifiphisher.py then chose a AP ,it shows this error 
![untitled](https://cloud.githubusercontent.com/assets/7880697/5685185/a103b8c0-9840-11e4-8e50-66ef46ff5c3d.png)
any help?

**Comment by chaunceydavs** [comment]
You gotta install your hostapd dependancy that was on the previous step.  It wont install unless you add the official kali repos to your sources.list file as described here:
http://www.blackmoreops.com/2013/10/30/add-official-kali-linux-repositories/

**Comment by chaunceydavs** [comment]
And you gotta have 2 external wireless cards plugged into your machine, while your internal one is connected to the internets (not the same AP you're cloning).

**Comment by sophron** [comment]
Hi,

As mentioned in #37, you need to install hostapd for the script to work on Kali. Check how to add the Kali repositories to your sources.list.
