### ISSUE TITLE
Does Wifiphisher 1.2  work on Kali Linux 16.2?

### ISSUE THREAD

**Issue by Machiko123** [sophron/wifiphisher#410]
One can read that Wifiphisher doesn′t work on the latest Kali Linux versions but only till Kali 2.0.
I don′t know whether it is true. I could install it on Kali 16.2 but it loops at DHCP Leases.

Why don′t you add in the official description on which Kali version it works? There are so many.

**Comment by sophron** [comment]
Yes, it works on latest Kali.
