### ISSUE TITLE
Can someone on different network also connect to the fake access point?

### ISSUE THREAD

**Issue by Machiko123** [sophron/wifiphisher#414]
Is the fake access point also visible for not attacked users on different networks? Assumed wifiphisher creates fake access point "abc_verizon". Is it also possible that people connected to different networks can see it and can connect to the fake access point?

Somehow wifiphisher creates always an "open" fake access point. It shows it as unsecured, therefore 
other people could try to connect to it. I don′t know if only the victim see it on its own computer or everybody that is in reach.

**Comment by blackHatMonkey** [comment]
Yes, **Everyone** is able to connect to the "fake" access point. This type of attack is really successful in airports where all the access points are open.

**Comment by sophron** [comment]
Everyone can connect to the rogue AP. Use the `--presharedkey` option to create a password-protected AP if needed.
