### ISSUE TITLE
Can connect to acces point with an iphone but PC don't work, can't establish connection.

### ISSUE THREAD

**Issue by tripformoney** [sophron/wifiphisher#416]
Hi, I am using the newest version of wifiphisher, for my wireless adapters I've got 2x TP-Link Wn722n.
When I am starting acces point, iphone can connect and I see the scenario page (firmware update etc), everything is fine till I try to connect with my computer, then I can't connect to the network. I tried to restart network manager, give a tp-link adapter other ip adress. Do you guys have any ideas ? 
I use ath9 drivers. Thanks for any help !

**Comment by blackHatMonkey** [comment]
Just to clarify are you trying to connect using the **same** computer that is running the _Wifiphiser_ or a **different** one?

**Comment by tripformoney** [comment]
I'm running Wifiphisher on Kali installed in virtual machine (VMware) and I'm connecting through my windows from the same computer but outside virtual machine. Do You think this may be a problem ?

**Comment by blackHatMonkey** [comment]
Have you tried connecting from a different computer?

**Comment by tripformoney** [comment]
Yes, from another pc everything works fine, thanks for help. Colse
