### ISSUE TITLE
Errno 2 

### ISSUE THREAD

**Issue by mcocigra** [sophron/wifiphisher#417]
Hi guys I am new one here and I could use your help. Please 
I am attaching a picture of the output please help where is the solution. Everything works until you choose a scenario then this is the error.
![img_20170121_043351_2](https://cloud.githubusercontent.com/assets/25259626/22171696/e4219cd4-df93-11e6-85df-f74a99aaf7a0.jpg)

**Comment by JustMev** [comment]
I get this sometimes i just run the command line again

**Comment by mcocigra** [comment]
No matter how many times I run it I get the same. Tried both commands. This is everything I used
Git clone ..........
Cd wifiphisher
Sudo python setup.py install
Wifiphisher or from bin 
And always the same result on the picture

**Comment by tripformoney** [comment]
Try to reinstall python maybe.

**Comment by blackHatMonkey** [comment]
You may want to do 
```bash
pip uninstall wifiphisher
```
and also removing the clone folder all together. Let me know if you still have difficulties after performing above tasks.

**Comment by mcocigra** [comment]
Thanks. Will try and let you know.

**Comment by JustMev** [comment]
make sure its python 2.7 also see if scapy is also installed

have you tried sudo apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y

**Comment by mcocigra** [comment]
The update worked and the program is starting but it isn't jamming anything everything is empty on the 3 fields: jamming devices, dhcp leasses and http requests

**Comment by mcocigra** [comment]
Thanks Justmev  I am gonna open another and attach picture
