### ISSUE TITLE
everything goes well, however, can`t connect to the honeypot ap.

### ISSUE THREAD

**Issue by hackingangle** [sophron/wifiphisher#42]
everything goes well, however, can`t connect to the honeypot ap.

**Comment by hackingangle** [comment]
IFCONFIG LOGS:
root@kali:~/dev/wifiphisher# ifconfig
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:907 errors:0 dropped:0 overruns:0 frame:0
          TX packets:907 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:267127 (260.8 KiB)  TX bytes:267127 (260.8 KiB)

mon.wlan0 Link encap:UNSPEC  HWaddr 08-57-00-37-79-73-3A-30-00-00-00-00-00-00-00-00  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2185 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:600290 (586.2 KiB)  TX bytes:0 (0.0 B)

wlan0     Link encap:Ethernet  HWaddr 08:57:00:37:79:73  
          inet addr:10.0.0.1  Bcast:10.0.0.255  Mask:255.255.255.0
          inet6 addr: fe80::a57:ff:fe37:7973/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1400  Metric:1
          RX packets:88 errors:0 dropped:0 overruns:0 frame:0
          TX packets:75 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:13081 (12.7 KiB)  TX bytes:14787 (14.4 KiB)

wlan1     Link encap:UNSPEC  HWaddr 08-57-00-32-CC-8B-3A-30-00-00-00-00-00-00-00-00  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1507 errors:0 dropped:83 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:367982 (359.3 KiB)  TX bytes:0 (0.0 B)

**Comment by hackingangle** [comment]
I can see the fisher page by brower ,Loaction:http://10.0.0.1:8080

**Comment by hackingangle** [comment]
mon.wlan0 Link encap:UNSPEC HWaddr 08-57-00-37-79-73-3A-30-00-00-00-00-00-00-00-00

UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:2185 errors:0 dropped:0 overruns:0 frame:0
TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000 
RX bytes:600290 (586.2 KiB) TX bytes:0 (0.0 B)


This config is auto-generated,not my settings.

**Comment by hackingangle** [comment]
how`s it ?plz help me.


SYST:kali linux
WIRELESS CHIP:Tplink tl=wn821n(the same two chip,one jamming, another server for brower.)

**Comment by tbaggh** [comment]
how is it used , can somebody make a read me about it plse

**Comment by snip3r007** [comment]
Hello,
i have the same problem...did you find any solution for this?
i think the problem is in the iptables....there must be some tunneling....
i wait for ur respons

**Comment by tbaggh** [comment]
we can talk on skype, kik or any chatting app so that we can share ideas ,

**Comment by snip3r007** [comment]
add me on skype:
pr3torian3 (skype name)
btw, i got mine working now

**Comment by hackingangle** [comment]
Resolved?please show the result here ,thanks

**Comment by rhythmer** [comment]
add me on skype please
loading.chen
 2015年1月20日 下午3:36于 "Wang Gang" <notifications@github.com>写道：

**Comment by sophron** [comment]
Ηι @hackingangle,

Thanks for reporting. There's already ticket #29 for this.

**Comment by tbaggh** [comment]
Tbaggh1995 that's  my Skype id add me let's share ideas over there
