### ISSUE TITLE
How can I customise the update firmware scenario? 

### ISSUE THREAD

**Issue by Ozymandias2000** [sophron/wifiphisher#420]
I have been trying to set up my own version of the scenario but using a Virgin Media logo, how is the best way to do this without messing with the python code? The attack works well as is but the router list available doesn't really fit with the routers that are common in my area of the UK. Is there any way that you can select the router and bypass the automatic router detection? 

I have tried just replacing the logo file with my own but this didn't work. 

Thanks in advance.

**Comment by sophron** [comment]
Virgin Media is a company that provides telephone/mobile and broadband Internet services, not a router manufacturer. That being said, there are no Virgin Media routers.

However, if you want to display the Virgin Media logo on the `firmware-upgrade` scenario you need to do the following:

1) Rename your logo to `logo.png` and save it under `wifiphisher/wifiphisher/data/phishing-pages/firmware-upgrade/static/` directory.

2) Go to <a href="https://github.com/sophron/wifiphisher/blob/master/wifiphisher/data/phishing-pages/firmware-upgrade/index.html#L137">this line</a> and change `{{ target_ap_logo_path }}` to `logo.png`.

3) When you make the above changes, you can either re-install wifiphisher (e.g. by typing `python setup.py install`) or run wifiphisher w/o installing (e.g. `python bin/wifiphisher`).

That should do it.

**Comment by Ozymandias2000** [comment]
Excellent, thank you!
