### ISSUE TITLE
--nojamming <-What would be the way to use this with one wireless interface 

### ISSUE THREAD

**Issue by ramadansanli** [sophron/wifiphisher#421]
root@kali:~/Desktop/wifiphisher# python bin/wifiphisher[*] Starting Wifiphisher 1.2GIT at 2017-01-23 17:23
[!] There are not enough wireless interfaces for the tool to run! Please ensure that at least two wireless adapters are connected to the device and they are compatible (drivers should support netlink). At least one must support Master (AP) mode and another must support Monitor mode.
Otherwise, you may try --nojamming option that will turn off the deauthentication phase.
[+] Captured credentials:
[!] Closing

**Comment by tripformoney** [comment]
Read description or read again your post. If You that lazy just type wifiphisher --nojamming.
