### ISSUE TITLE
Creating a module for wifi pineapple

### ISSUE THREAD

**Issue by kn0wledge** [sophron/wifiphisher#424]
Hi, are you considering creating a module for wifi pineapple? If not, any other way of making your html templates to work with Captive portals? 

Thanks,

**Comment by Foxtrot** [comment]
While I have nothing to do with this project, I myself am already working on a module for this for use with the WiFi Pineapple.

**Comment by kn0wledge** [comment]
awesome, anywhere we can follow your updates?

**Comment by sophron** [comment]
Hi, 

No I don't have the time to port Wifiphisher functionality to Pineapple and I'm not sure this is even possible. 

Some of the templates could possibly be integrated. Keep in mind that Wifiphisher is under GPL though and this may be restrictive.
