### ISSUE TITLE
Fake ap stop working after a while 

### ISSUE THREAD

**Issue by atgeek** [sophron/wifiphisher#425]
I'm running wifiphisher on kali 2016.2, using integrated Broadcom wifi card for jamming and an external USB adapter (ralink 28700), the target ap is jammed but the fake ap after some hours dissappear. What could be the problem? There is a way for view a real time output log?

**Comment by sophron** [comment]
We currently do not support logging.

My suspicion is that your card tends to fall out. Can you try using another interface for the AP (using the `-aI` option) and see if you have the same results?
