### ISSUE TITLE
Problem installing tool

### ISSUE THREAD

**Issue by LordNDHuy** [sophron/wifiphisher#429]
**Version**: sorry my git is currently not working idk why.

**Distribution**: I am using arch 

**Summary**: Problem with installing Python2-jinja2

**Description**: As title, I install wifiphisher from some sources, they all require python2-jinja2, which I cannot find a way to install.

**Comment by blackHatMonkey** [comment]
Have you tried installing it using ```pip``` like so:
```bash
pip install Jinja2
```

**Comment by sophron** [comment]
Have you tried `python setup.py install`?

**Comment by LordNDHuy** [comment]
i got
`Using /usr/lib/python3.6/site-packages/PyRIC-0.1.6.3-py3.6.egg
Finished processing dependencies for wifiphisher==1.2
Traceback (most recent call last):
  File "setup.py", line 111, in <module>
    get_hostapd()
  File "setup.py", line 57, in get_hostapd
    install = raw_input(
NameError: name 'raw_input' is not defined
`
when i run 'python setup.py install'

**Comment by LordNDHuy** [comment]
any way i have figured out how to fix it. i have successfully installed it tks all

**Comment by charcchii** [comment]
how did you fix it

**Comment by charcchii** [comment]
i am having another error ~\Documents\GitHub\wifiphisher [master ≡]> python setup.py install
Traceback (most recent call last):
  File "setup.py", line 137, in <module>
    get_libdbus()
  File "setup.py", line 108, in get_libdbus
    install = raw_input(("[" + constants.T + "*" + constants.W + "] libdbus-1 no
t found " +
NameError: name 'raw_input' is not defined
