### ISSUE TITLE
Selecting Interfaces Manually

### ISSUE THREAD

**Issue by kn0wledge** [sophron/wifiphisher#430]
Hi Sophron, 

Is it possible to select which wireless interface does what? although the automated one is good but i have 3 interfaces and would like to select which to be used since auto selecting the default laptop wifi card is horrible gain. 

Thanks

**Comment by sophron** [comment]
Have you read the manual (`wifiphisher --help`)? The options that you are looking for are `-aI` and `-jI`.

**Comment by mcocigra** [comment]
Solved close it

**Comment by Tusharsharma86** [comment]
Hi Sophron, 

I am trying to follow the steps to start wifiPhisher but getting below error -
wifiphisher.common.interfaces.InvalidMacAddressError: The provided MAC address is invalid

What I am doing wrong?

**Comment by anakin1028** [comment]
Can you provide with the `-iNM` option and see if tool works for you?
Your card looks like cannot change mac address.

**Comment by Tusharsharma86** [comment]
I had changed the mac address using this wifi card. But today when I am
using command macchanger. It is throwing me error.
Is this issue because of this?

**Comment by Tusharsharma86** [comment]
I just saw that yes I can still change my Mac add-
ifconfig wlan0 down
macchanger --random wlan0

and this works fine and changes the Mac address of my card. 

Please help if you have any solution to fix wifiphisher error.

**Comment by anakin1028** [comment]
Yes.wifiphisher will default spoof the mac address and looks like there has problem for changing mac address of your card. We may add exception handling for this. That is catching the mac address exception and let the tool run continuously.

**Comment by Tusharsharma86** [comment]
Thanks for the response. 
Can you please guide me how to add exception.

**Comment by anakin1028** [comment]
You can first use the following command:
`wifiphisher -iNM` and see if this works

**Comment by Tusharsharma86** [comment]
yes it works.. !!

What is the reason this works and other one does not.

**Comment by anakin1028** [comment]
Wifiphisher will default spoof the mac address of the adaptor by the python module `pyric` and for some reason it fails for your card, but tool doesn't catch that exception so it fails to run.

With `-iNM` this means you don't want to change the mac address of your card. You can use `wifiphisher --help` to see the available commands.

**Comment by Tusharsharma86** [comment]
ok that sounds great. thanks a lot for helping this out quickly.

**Comment by anakin1028** [comment]
You're welcome : ) btw I'm just curious what adaptor do use?

**Comment by Tusharsharma86** [comment]
I am using AWUS036NH

**Comment by Tusharsharma86** [comment]
BTW, I had one more question, if you are aware of that too.
I was earlier using mana-toolkit for creating Fake AP. 

But that works for 10 secs I get connected from a android device and then it disconnects and never gets connected on that channel. Any idea how to solve this?

Can it be issue due to conflicting IPs or channels. I tried multiple channels but no luck.

**Comment by anakin1028** [comment]
Does your Android device cannot get dhcp release or it cannot get connect with the fakeAP?

If the device cannot get the dhcp release it may because of the IP conflict.

**Comment by anakin1028** [comment]
Do you have two cards on your system? If so do they have the same IP address?

**Comment by anakin1028** [comment]
Our fake AP will default have the IP address `10.0.0.1` and make sure you only have one adaptor has that IP address.

**Comment by Tusharsharma86** [comment]
How do I make sure the IP address is 10.0.0.1

**Comment by anakin1028** [comment]
Can you post the output of `ifconfig`?

**Comment by Tusharsharma86** [comment]
root@kali:~# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::a00:27ff:fea1:b6e6  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:a1:b6:e6  txqueuelen 1000  (Ethernet)
        RX packets 11146  bytes 16670429 (15.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2125  bytes 130544 (127.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 20  bytes 1116 (1.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 20  bytes 1116 (1.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 10.0.0.1  netmask 255.255.255.0  broadcast 10.0.0.255
        ether 00:11:22:33:44:00  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16  bytes 1584 (1.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by anakin1028** [comment]
Hmm. Do you see the main terminal of wifiphisher output the dhcp release ?

Also from the ifconfig output you only have one adaptor in the system. Can you output the `ifconfig` again when the tool is running?

You can post a new issue and provide us with these information :) since your question is not relevant in this thread.

**Comment by Tusharsharma86** [comment]
Ok sure will open new thread

**Comment by Tusharsharma86** [comment]
@anakin1028 I got the mana-toolkit issue resolved too. Thanks for your help today.

**Comment by temoora82** [comment]
The error is showing in my screen wifiphisher error argument  -i/--interface: expected one argument
