### ISSUE TITLE
Probe Request Support

### ISSUE THREAD

**Issue by zero77** [sophron/wifiphisher#433]
Can you add the option to create fake AP based on probe request of nearby devices.
Thanks,

**Comment by laozi999** [comment]
You can use airodump-ng to monitor networks for activity, and then target them.

**Comment by laozi999** [comment]
You can use **airodump-ng** to monitor networks for activity, and then target them.

**Comment by kn0wledge** [comment]
@zero77  u mean such as the pineapple pine ap?

**Comment by sophron** [comment]
I think you mean something like KARMA attack. There's already #76 for this.
