### ISSUE TITLE
AP problem with connecting device . No internet connection . 

### ISSUE THREAD

**Issue by Georgestrmina08** [sophron/wifiphisher#438]
Before opening a new issue, please make sure that what you are about to report has not been reported already. If not, use the following template for reporting:

**Version**: Use `git show | grep commit` command and paste here the output.

**Distribution**: On which GNU/Linux distribution are you using the tool? (e.g. Kali Linux, Gentoo, Debian)  Linux Mint 18.1 Serena

If you know the bug happens on all distributions please mention it. Otherwise, let us know the distribution that you found the bug on.  Linux Mint 18.1 Serena

**Summary**: Describe the bug in a short paragraph:

Everything is working fine they creating AP  but they not allowing mi to connect from a phone or any other device.

**Description**: Give a more analytical description here. If the bug you are about to report has to do with the WiFi jamming module, please specify the network cards you are using. If the bug has to do with the rogue Access Point (eg NAT or IP addressing issues), also post the output of the `ifconfig -a` and `iwconfig` commands. Finally, if the bug is about the phishing pages or our HTTP minimal server, please specify the browser you are using to connect to it. 
![airmon-ng](https://cloud.githubusercontent.com/assets/25528842/22654940/52eb9922-ec86-11e6-8c32-f49a8bc7bab5.png)
![ifconfig](https://cloud.githubusercontent.com/assets/25528842/22654941/5416f7b0-ec86-11e6-9f31-622951508751.png)

**Steps to Reproduce**: The minimal set of steps necessary to trigger the bug. 

wifiphisher-master $ sudo wifiphisher

**Expected VS actual behavior**: How were you expecting the tool to behave and what actually happened?
![wifiphisher](https://cloud.githubusercontent.com/assets/25528842/22654964/6873be96-ec86-11e6-86b6-c274fd75562e.png)

**Script output**: Paste the output of the tool, including any stack traces.

**Comment by mcocigra** [comment]
The jamming works surprising but maybe it is something with the leasing what scenario are you using the first one isn't mobile friendly

**Comment by Georgestrmina08** [comment]
I tried all scenario and still nothing, I really can't figure out whats problem . If someone knows please help I will provide all information .. thanks

**Comment by blackHatMonkey** [comment]
@Georgestrmina08 Can you be more specific about when you connect to the access point. Does it give you any errors?

**Comment by mcocigra** [comment]
Try connecting with your own mobile phone to the fake network you are creating does it then show up in the leases section and even can you connect     if you can connect what shows up when you open chrome and ask for any web page does it give the scenario you have chosen

**Comment by sophron** [comment]
Hi @Georgestrmina08,

Apparently, there's a conflict with two of your interfaces set to 192.168.1.0/24 subnet. I just pushed a commit that uses 10.0.0.0/24 (for the wireless network) instead.

Can you update to the latest revision and try again?

**Comment by Georgestrmina08** [comment]
Guys thanks for answering: 

In this case, I tried scenario num 2 Firmware update and this is what I'm getting on the phone screen: 
![0-02-04-2e371f2d57abb979f5a54870f5b4a7539e754277c9e85f01f7847d1522f0d1e2_full](https://cloud.githubusercontent.com/assets/25528842/22686414/feff5d26-ed1b-11e6-95ff-9851aa260efc.jpg)
![0-02-04-9245c9af7a019485e14957464f9e33de7d8c618e4de5cecdef77031be67352e1_full](https://cloud.githubusercontent.com/assets/25528842/22686415/ff5af618-ed1b-11e6-858b-5ec748a8b948.jpg)



This is my wifiphisher screen on laptop : 

![0-02-04-9e389525d68d16d83653ed03eae572a1aacdc85240a4b0917a542d9da99c3925_full](https://cloud.githubusercontent.com/assets/25528842/22686438/0e370aa0-ed1c-11e6-86c2-8466c0bd8b87.jpg)
![0-02-04-d74612cd16695b642120bfab5b43bc37050cc03abeba7f41dbe1dac5237a8aa4_full](https://cloud.githubusercontent.com/assets/25528842/22686439/0e5cbae8-ed1c-11e6-9c7a-92409fdbe5f2.jpg)

**Comment by sophron** [comment]
Did you update to the latest revision as I asked you? I will also need the output of `ifconfig` once more.

**Comment by Georgestrmina08** [comment]
No, i did not please explain me steps to do that: 
this is mine output of ifconfig :

legend08@legend08-Aspire ~ $ ifconfig
enp1s0    Link encap:Ethernet  HWaddr 30:65:ec:99:cb:fb  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:227 errors:0 dropped:0 overruns:0 frame:0
          TX packets:227 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:40312 (40.3 KB)  TX bytes:40312 (40.3 KB)

wlp2s0    Link encap:Ethernet  HWaddr 44:1c:a8:0a:d4:fb  
          inet addr:192.168.1.77  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::65f3:e3e8:cfb7:c324/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:261 errors:0 dropped:0 overruns:0 frame:0
          TX packets:168 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:39979 (39.9 KB)  TX bytes:22310 (22.3 KB)

wlx00c0ca91ec8c Link encap:Ethernet  HWaddr 00:c0:ca:91:ec:8c  
          inet addr:192.168.1.94  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::595b:655c:721b:27d7/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:26 errors:0 dropped:0 overruns:0 frame:0
          TX packets:41 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:7746 (7.7 KB)  TX bytes:7102 (7.1 KB)

**Comment by sophron** [comment]
Download the tool again and re-install.

**Comment by Georgestrmina08** [comment]
No, i did not please explain me steps to do that:  
My ifconfig command output : 



![screenshot from 2017-02-07 10-19-47](https://cloud.githubusercontent.com/assets/25528842/22688040/6c626a7e-ed22-11e6-8de8-9c3d10098ac2.png)

**Comment by Georgestrmina08** [comment]
Some advice for my problem please ?

**Comment by sophron** [comment]
I think I was clear. Re-download the tool, re-install it and run the script again.

**Comment by Georgestrmina08** [comment]
I reinstall my Linux completely because of this tool and same problem  .
