### ISSUE TITLE
Modify phishing website

### ISSUE THREAD

**Issue by dumper93** [sophron/wifiphisher#453]
Hello,

i modified (changed language of the Text) the phishing website and put it into the directory:

/root/wifiphisher/wifiphisher/data/phishing-pages/firmware-upgrade

But it doesn't use it, if I start wifiphisher an. It still use the old page. I wondering because the old page isn't in the directory anymore.

Best Regards

dumper93

**Comment by blackHatMonkey** [comment]
Can you show us your `data` directory?

**Comment by dumper93** [comment]
[url=http://abload.de/image.php?img=data2epjn.jpg][img]https://abload.de/thumb/data2epjn.jpg[/img][/url]

**Comment by blackHatMonkey** [comment]
If you open the selected `index.html` file can you see your modifications?

**Comment by dumper93** [comment]
Yes.

**Comment by mcocigra** [comment]
Did you reinstall it
Reinstall the setup.py

**Comment by dumper93** [comment]
Thanks. Not it works 👍.

**Comment by sophron** [comment]
You need to either `python setup.py install` again or run the tool as `python bin/wifiphisher`.
