### ISSUE TITLE
Victim AP not shown in list

### ISSUE THREAD

**Issue by sandman6578** [sophron/wifiphisher#46]
Hello guys,

Why does the script do not show a router in the list either airodump shows the AP why is this?
and when i use the -a argument the list with the access points still shown but not the one i want to attack.

Hope some one can help thanks in advance

**Comment by sandman6578** [comment]
by the way the ESSID is A1 is it possible that the Script only show Access Points with ESSID longer than 3 chars??

**Comment by sandman6578** [comment]
if this is the case can some one change it pls

**Comment by arthurbarros** [comment]
@sandman6578 I've looked at the code and didn't find any char length constraints. Can you tell us more about "A1" hotspot setup?

**Comment by arthurbarros** [comment]
@sandman6578 please, also include your USB wireless adapters chipset models

**Comment by sandman6578** [comment]
rtl8187 alfa adapter 1 and the other is an atheros ar242x /ar542x 
A1 on channel 11 wpa2 ccmp psk
technicolor tg788a1vn

**Comment by sandman6578** [comment]
i dont understand why the script do not show the router

**Comment by arthurbarros** [comment]
@sandman6578 Ok, asap I'll try to reprocue the hotspot scenario and see what is going on.

**Comment by sandman6578** [comment]
thanks in advance

**Comment by sandman6578** [comment]
hey arthur did you find a solution??

**Comment by sandman6578** [comment]
@arthurbarros

**Comment by arthurbarros** [comment]
@sandman6578 Didn't find the solution yet, but I can confirm that some SSID don't show up. But I cant thell yet if this is a problem with my wireless adapter model or the wifiphisher, because the wireless isn't showing even at the Network Manager

**Comment by sophron** [comment]
Hi guys,

The captured access points depend only on you wireless card's strength. If the script doesn't show them, a network manager won't show them either.

**Comment by sandman6578** [comment]
hey sophron the accesspoint is 10 meters away from me. its not possible because ive changed something at the code and now it shows every access point but its a long time ago i cant say you were i made the changes but anywhere at the scanning procedure in the code. means its a failure at code
