### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by phuongs3v3r** [sophron/wifiphisher#47]
after install hostapd -> 

![screenshot from 2015-01-11 23 50 29](https://cloud.githubusercontent.com/assets/5646810/5706749/45bf76e4-9a51-11e4-9275-453132eb5c7d.png)

**Comment by sophron** [comment]
That basically means that another process runs on port 80. Try changing the value by editing line 26.

**Comment by arthurbarros** [comment]
try kill apache before run wifiphisher

**Comment by phuongs3v3r** [comment]
restart the program @@ normal .

**Comment by phuongs3v3r** [comment]
usb wifi connection need not ???

**Comment by xcellardoor** [comment]
A USB WiFi adapter wouldn't change anything. Port 80 on your machine is still bound by Apache or similar. Kill Apache, nginx or whatever you're running. Then retry.
