### ISSUE TITLE
Use the MAC address of the target AP to get info for the hardware vendor

### ISSUE THREAD

**Issue by sophron** [sophron/wifiphisher#5]
It is possible to determine the router manufacturer using the MAC address of the target AP. <a href="http://www.coffer.com/mac_find/">Here<a/> is an API that matches a MAC address to its vendor.

By determining the hardware vendor, we can fill the fake router configuration page with valid information and make the phishing part more effective. 

Anyone with good Python knowledge can help on this.

This idea was proposed by @ConX.

**Comment by Josso** [comment]
Without having any affiliations with any MAC address lookup sites, I'd say that macvendorlookup.com looks better as it even has [an API](http://www.macvendorlookup.com/mac-address-api).

[PortForward.com](http://screenshots.portforward.com/) also has a lot of screenshots of various routers, although I don't know what the legal grounds are on using any logos etc.

**Comment by rolandshoemaker** [comment]
I'd suggest using either the IEEE list (http://www.ieee.org/netstorage/standards/oui.txt) or the NMAP prefix list (https://svn.nmap.org/nmap/nmap-mac-prefixes) rather than a 3rd party service.

**Comment by Josso** [comment]
That is probably the best. And you only need to include the prefixes for the companies/brands you have a custom router configuration page for.

**Comment by strasharo** [comment]
Since GNU macchanger already has this functionality, I guess its mac lists can be used as well, they're already converted in an easy to parse format:
https://github.com/alobbs/macchanger/tree/master/data
It already has a separate list with mac addresses related only to wireless adapters:
https://github.com/alobbs/macchanger/blob/master/data/wireless.list

**Comment by gudoz20** [comment]
were i can download the tool.. i can't find the downloadable link

**Comment by strasharo** [comment]
Which tool?

**Comment by yasoob** [comment]
If anyone can explain the implementation of this feature I can implement it! :+1:

**Comment by Kryptonit3** [comment]
![Image of Linksys page](http://i.snag.gy/sWMgL.jpg)

Here is a sample linksys login page fabricated. I could do this all day for any router.

**Comment by chandanchowdhury** [comment]
Friends... I am new to github so please pardon in case I sound like one...
 
"The first three octets (in transmission order) identify the organization that issued the identifier and are known as the Organizationally Unique Identifier (OUI)." - Wikipedia

As I understand, the first three numbers of MAC address represents the company that built the NIC card and so most probably the router too.
 
For example, if the first three numbers are
0C-4D-E9
2C-BE-08
Then your NIC was manufactured by Apple.

I find the IEEE listing as the latest and always up to date
http://www.ieee.org/netstorage/standards/oui.txt

Did an ARP on my router IP and got
%arp 192.168.1.1 
? (192.168.1.1) at 40:4a:3:7f:31:3c on en1 ifscope [ethernet]

Searched the public listing database and got ZyXEL which is the router we use
40-4A-03   (hex)          ZyXEL Communications Corporation

Hope I have been able to explain how we can use the listing to know the router manufacturer and show a custom page accordingly which I guess is what we want to achieve.

Please let me know if I can help any other way.

**Comment by FurqanHanif** [comment]
i'm Not Good in Programming , So please Someone Tell me how i Put Copyright in Default Page Footer?? i Think Copyright is already define but Don't Know Why it's Not Showing (See menu.html)..

**Comment by networkmagician419** [comment]
In my opinion, once we get the victim to connect to us, this IS the most important step of getting the password. Having a configuration page that matches the vendor by the MAC address is an amazing idea. Currently, only the "stupids" will reveal the password. However, if we can get this implemented, almost everyone except for the tech people will be vulnerable. 

Until this is available, there should be an option for the user to upload our own page, that way we can make our own to look realistic. And by using it in the tool, it automatically uploads to a database online and others can select it..like that idea?

**Comment by chandanchowdhury** [comment]
Friends...
have written two simple classes to download and find the manufacturer/vendor based on Mac address...

1. MacToVendor will first check if "manuf.txt" file exists on current directory.
2. If not, uses DownloadURLText to download the MAC address data from WireShark repository (they keep their list always up to date).
3. Then MacToVendor will use the data in the file to return the manufacturer/vendor short/long name based on provided mac address (first 6 octets).

https://github.com/chandanchowdhury/PyRecipes/blob/master/MacToVendor.py

Please give it a try and let me know your suggestions/improvements.

Cheers!

**Comment by sophron** [comment]
Hi @chandanchowdhury,

Your script looks good. Do you think you can include this to wifiphisher and make a PR?

**Comment by Cybosusu** [comment]
sophron if you can edit the code  to make like this : 
-don't make the router open change it to router accept any password 
-when the user or the system automatically  enter the password from the setting the code will catch it

**Comment by chandanchowdhury** [comment]
Hi @sophron 
How are you doing? sorry could not reply earlier.. got wee bit busy...

I have already started on the work you suggested... currently at first step i.e. understanding how the current code works... will keep all posted.

Regarding the router login pages, I was thinking that we should store the pages in individual folders along with any logo/images the page would need to display just like the real router page and come up with a naming convention we should use to name the folders. 
Do you think that would be useful or in case any other way would better?

**Comment by sophron** [comment]
Hi @chandanchowdhury,

Let's keep the conversation for the phishing pages to #4. But yes, i agree. That's the idea.

**Comment by sophron** [comment]
Just for the record, <a href="http://insecure.org/fyodor/">Fyodor</a>, the author of Nmap Project, gave me permission to use <a href="https://svn.nmap.org/nmap/nmap-mac-prefixes">nmap-mac-prefixes</a> file, an easy-to-parse file that contains MAC prefixes along with their vendor.

**Comment by blackHatMonkey** [comment]
This feature has been implemented. Please upgrade to the latest version to use it.
