### ISSUE TITLE
found net but not watch list ...problem script

### ISSUE THREAD

**Issue by 5485** [sophron/wifiphisher#52]
![20150112_213809](https://cloud.githubusercontent.com/assets/10505547/5711062/f0eb6ea0-9aa7-11e4-86cd-e0bbfd0b899d.jpg)
![20150112_213536](https://cloud.githubusercontent.com/assets/10505547/5711071/fec02ee4-9aa7-11e4-9d91-086c4aca5e4c.jpg)

**Comment by 5485** [comment]
The script arrive to point cleaared leasis started dhcp and then the script is block.... why ?

**Comment by arthurbarros** [comment]
@5485 What is the model of yours wifi adapters? Are you sure at least one of them are capable of packet injection?

**Comment by 5485** [comment]
I use two adapters alfa awus036nh, awus036h.... This device found the net but  the script block in this point.... 
cleaared leasis started dhcp......

**Comment by 5485** [comment]
![kali](https://cloud.githubusercontent.com/assets/10505547/5854778/9cde7726-a231-11e4-8d39-2bcbc049f9cc.png)

**Comment by 5485** [comment]
the problem may be that?
http://...................................../hostpad_1.0+b2_amd64 not found ?

**Comment by sophron** [comment]
Hi @5485,

Yes, you need hostapd for the script to run. Check #37.
