### ISSUE TITLE
[Feature Request] Phishing using two different computers

### ISSUE THREAD

**Issue by d-oliveros** [sophron/wifiphisher#54]
Hi, I unfortunately don't have an extra wifi card, but have a spare computer to use. 

Is it possible to use `wifiphisher` in two separate computers? Like, one acting as the jamming interface and the other one as the api interface?

**Comment by arthurbarros** [comment]
You could setup this scenario without wifiphisher. Note that wifiphisher ONLY automate the task for you. But this kind of attack is well known for the role InfoSec community.
Try to google about "wifi honeypot"

**Comment by d-oliveros** [comment]
ohh I see, Thanks @arthurbarros, I'm reading about it now.
