### ISSUE TITLE
Some Problems i don't understand why?

### ISSUE THREAD

**Issue by sandman6578** [sophron/wifiphisher#55]
Hey,

The first problem is as follows.

If I Attack the target router, then there are occasional problems that the client is not on the jamming devices list.
Also, the router is not listed.
But only sometimes.
sometimes it works sometimes it does not work (ON THE SAME ROUTER)
The next problem is that the victims are not redirected from every page to our Fake Page.
the only page which everytime works is google.com
In example when i connect to the FAKE AP and refresh the Github Page i will  be no redirected to the Fake Router Page.

What is responsible for these problems. 
are there any solutions for this??
I would understand why this is like it is

**Comment by sophron** [comment]
Regarding your first question, check #46.

What exactly happens when you try to load Github or any other page that won't get you redirected?

**Comment by sophron** [comment]
Feel free to re-open if needed.

**Comment by sandman6578** [comment]
no i dont get redirected sry for late answer
