### ISSUE TITLE
About Wifiphisher.

### ISSUE THREAD

**Issue by Faouzi47** [sophron/wifiphisher#56]
Hello there,
I got some questions about wifiphisher and need some answers to clear my mind.
1-I m using my desktop and I got 2 wireless cards,both are Linfox using RLT8187 cheapest 
I'm I good with this ?

2-Do I need internet while waiting to get the WPA key ? if yes,is that necessary ? why ? and does this mean that I need 3 adapters ? because I got no internet at home..

3-Some of the nearby WIFI cant be reached by regular wifi adapter,phone,laptop.That's why I'm using an outdoor antenna to reach them.
Will this make a problem when the Victim client try to connect to the fake AP (cant reach it maybe ?)

Thank you and have a good day !

**Comment by jalcine** [comment]
1) The easiest way to know is to test it out yourself and confirm. I personally know that RLT8187 chipsets are okay.

2) No, you don't. Please read the [About](https://github.com/sophron/wifiphisher#about) closely.

3) Your distance from the victim AP might affect your ability to poison the client so yeah, the closer the better.

**Comment by Faouzi47** [comment]
I tried but didnt succeed.
I always fail connecting to the fake AP.I tried to use ALFA with Ralink cheapest as AP interface but didnt get any positive results.
Any advices ?

**Comment by sophron** [comment]
Hi @Faouzi47,

Maybe your connection problem has to do with #29. I'll work on this as soon as i can.

**Comment by Faouzi47** [comment]
Hi @sophron 
what I understand so far is that problem related to the cheapest that I'm using as a fake AP no matter weather there is an internet connection or not.
I hope you can find a solution for this since I couldnt find any good adapter with better cheapest nearby..

**Comment by sandman6578** [comment]
Which RALINK you are use more information please
