### ISSUE TITLE
Help Me Please I want Solution for this ... hostapd in Kali Linux

### ISSUE THREAD

**Issue by ouarougzane92** [sophron/wifiphisher#57]
Help Me Please I want Solution for this ... hostapd in Kali Linux
Im Using Card WIfi ( RALINK and Athereos ).

![hhh](https://cloud.githubusercontent.com/assets/10553704/5783140/d273fade-9dc0-11e4-89ba-281783a8aae9.jpg)

**Comment by hessamx** [comment]
i have this problem , any one can help !??

**Comment by hessamx** [comment]
i use another live on vmware ,its work

**Comment by ouarougzane92** [comment]
Thank You @hessamx

**Comment by sophron** [comment]
Please check #37.
