### ISSUE TITLE
DHCP Leases not working!

### ISSUE THREAD

**Issue by onopop** [sophron/wifiphisher#60]
I got Jamming devices But no DHCP Leases or HTTP requests !
i wait for 60 minutes nothing worked! 
![untitled](https://cloud.githubusercontent.com/assets/10569371/5787486/e87998e0-9e09-11e4-894b-dfd3b748f50b.jpg)

**Comment by ibrahim101** [comment]
so do i .......

**Comment by sophron** [comment]
Hi @onopop,

A device needs to connect to the rogue AP to actually see a lease. If you are indeed trying to connect to it with a device and you still can't get an IP, maybe you ran into #29.

**Comment by debit7** [comment]
I got Jamming devices But no DHCP Leases or HTTP requests !
  what should I do now?

**Comment by m0265554** [comment]
Not sure why everyone keeps stating that the RTL8187 is not hostapd compatible... I've been running several several pi3/hostapd/dnsmasq access points reliably for months using Alfa cards with that chipset.
