### ISSUE TITLE
[HELP] WiFiPhisher (Jamming devices and DHCP doesn't work)

### ISSUE THREAD

**Issue by leg3ndnj** [sophron/wifiphisher#61]
SIOCADDRT: Network is unreachable

![screenshot from 2015-01-17 02 29 25](https://cloud.githubusercontent.com/assets/10570150/5787818/060186e8-9df1-11e4-9083-feb903fd868a.png)

![screenshot from 2015-01-17 02 31 41](https://cloud.githubusercontent.com/assets/10570150/5787819/08ef12da-9df1-11e4-9761-c306c7407b03.png)

Can some one help me, please?

Deauthenticate doesn't work and it doesn't start the fake AP.

**Comment by FurqanHanif** [comment]
You Need Two Adapters For Successful Attack (Read The Read-em) . if You'r using one adapter you'll get this message..

**Comment by leg3ndnj** [comment]
@FurqanHanif Oh, thx dude :)

**Comment by slmafiq** [comment]
sophron  Hello!
i use two wi fi injector packets adapters but i see only how to script Jamming victim and doesnt have results where is the problem? Thanks!
python wifiphisher.py -aI wlan0 -jI wlan1
....
