### ISSUE TITLE
wifiphisher stopped with no password!

### ISSUE THREAD

**Issue by italy2010** [sophron/wifiphisher#64]
Jamming devices: 
[*] 00:e3:b2:33:4f:7a - 04:8d:38:01:3f:86 - 6  - Aida-m
[*] c8:19:f7:bc:f3:72 - 04:8d:38:01:3f:86 - 6  - Aida-m
[*] cc:fe:3c:7b:19:1a - 04:8d:38:01:3f:86 - 6  - Aida-m
[*] 18:1e:b0:36:df:b3 - 04:8d:38:01:3f:86 - 6  - Aida-m
[*] e8:cd:2d:21:ad:bd - 04:8d:38:01:3f:86 - 6  - Aida-m
[*] 04:8d:38:01:3f:86 - bc:b1:f3:f5:89:bc - 6  - Aida-m
[*] 04:8d:38:01:3f:86 - 6  - Aida-m

DHCP Leases: 
1421640153 d4:6e:5c:52:84:34 10.0.0.50 android-44959a206d27bcfc *

HTTP requests: 
[*] POST 10.0.0.50 password==

there is not any password, i tested with my phone, and i dont posted anythin, when i connected to ap, wifiphisher stoped, and  said

[*] POST 10.0.0.50 password==

seem there are some problem, because i dont posted anything and also wifiphisher stopped

**Comment by snip3r007** [comment]
bro...when u connected with ur phone to the rogue ap...did u get any ip address?

**Comment by italy2010** [comment]
no at all.

**Comment by snip3r007** [comment]
bro use this..it is much better
http://www.hackinsight.org/news,38.html

enjoy

Date: Sun, 18 Jan 2015 09:22:23 -0800

**Comment by italy2010** [comment]
i think wifiphisher need creat db, and put dumpet info on database, it will be better, or have a admin panel and see logs.


we should wait & see. still not complete.

**Comment by snip3r007** [comment]
maybe
i think it has to do with the tunneling of the ip....
im looking at it now...the script is stolen and modified from other source

Date: Sun, 18 Jan 2015 09:35:49 -0800

**Comment by snip3r007** [comment]
can u post the settings pls?....

**Comment by italy2010** [comment]
which setting?

i used kali live usb, one alfa card, and another atheros card,
afther i connected to fake ap, i got ip, but i dont see any page for posting password on it, also wifiphisher stoped without password!

**Comment by snip3r007** [comment]
i think u must put all the files in /var/www...i think u are almost done...

**Comment by italy2010** [comment]
heem, maybe,

according this video 
https://www.youtube.com/watch?v=qcfDapCjCg4
he dont put wifiphisher files in /var/www

**Comment by Faouzi47** [comment]
@italy2010  which adapter are you using AP interface?

**Comment by italy2010** [comment]
i think fake ap started with atheros card, and alfa card sent packet to real ap.
yes.

**Comment by snip3r007** [comment]
btw, i got mine working now...
i had very slow internet, after i changed to a hacked network with fast internet, the phisher start to work
nice ...
:-)

Date: Mon, 19 Jan 2015 10:23:05 -0800

**Comment by Faouzi47** [comment]
@snip3r007  do you use internet while phishing ? I've heard that's not necessary,is it ?

**Comment by snip3r007** [comment]
@Faouzi47....yes, i use internet for this attack....cos when the victim fall into the trap, and he put in his key, i provide internet access for him, so he will not get suspicious....but dunno if u need internet access for this type of attack..i think it is better if u use internet...

**Comment by snip3r007** [comment]
only thing is the deauthentication is not working in my case, i think many routers are invulnarable for deauthentication....maybe there is another way to shut victim out of his wifi...

**Comment by italy2010** [comment]
but my problem with blank password not solved? also i dont get any page to put pw.

**Comment by snip3r007** [comment]
Try with another system to connect to evil twin
Now u try to connect with ur phone?
Try other phone
I also did with my iphone and no success cos iphone is secured for that

Date: Tue, 20 Jan 2015 12:19:43 -0800

**Comment by italy2010** [comment]
no my device is android,

wifiphisher work for you?

**Comment by justforyouNL** [comment]
It works for me as u can see in this youtube. 

https://www.youtube.com/watch?v=JRn5PvzM9ys

And it worked with 1 internal adapter from laptop and 1 usb wifi stick and i hooked up the LAN cable.
After running wifiphisher and installing "hostapd" then select your network, deauthentication works and i used my android phone(galaxy s3) to connect to some http website. After which the "fake" page appears and u enter password.

So it works for me, also u can see in the video which adapters i used, hope this helps.

Just

**Comment by sophron** [comment]
Hi @italy2010,

When you ran wifiphisher are you able to connect to the fake page at all?

**Comment by yadhurajm** [comment]
In my case the same problem am facing.

After connecting ap iys stop working the results i am getting is

Post 10.0.0.5 password=2.5.1
[!] closing

**Comment by sophron** [comment]
Hi,

This looks similar to #99. I just committed a fix. Please update to the latest revision and let me know if it now works properly.

**Comment by ayoubmenioui** [comment]
Hello guys i am a student of networking and i am new at this so plzz can you help me with this issue ,

* i have two interfaces : 

                                      ♦ ALfa AWUS036H 
                                      ♦ Sagem Zylda
* i have kali linux in as a virtual machine connected with ( NAT)

when i use wifiphisher  i face thi problem shown in this image :
![pb wifiphisher](https://cloud.githubusercontent.com/assets/12171300/7392795/04a034fc-ee82-11e4-94ce-b45b053cb7b6.PNG)


Any suggestions ?

**Comment by ayoubmenioui** [comment]
Hello Again
i got the password when i tried the interface 192.168.1.1 but wifiphisher doesn't spoof the victim automatically so i ended up with this :

![screenshot from 2015-04-29 15_47_43](https://cloud.githubusercontent.com/assets/12171300/7394539/298fed7a-ee8c-11e4-99ff-49d0e28b58f3.png)

**Comment by sophron** [comment]
Hi @ayoubmenioui,

I don't see any problem. Please have a look at the <a href="https://github.com/sophron/wifiphisher/wiki/Frequently-Asked-Questions-(FAQ)#q3">FAQ "I have no success using the tool / Nobody is connecting to the rogue AP. What am I doing wrong?"</a>.

If you still have issues, please open a new issue.
