### ISSUE TITLE
the orginal access point not stop working

### ISSUE THREAD

**Issue by AbdAlrzzaq** [sophron/wifiphisher#68]
when i start thise tool i searched for wireless network and i found 
 one of them the orginal
and the other one it have the same name and an open

**Comment by Med1Bel** [comment]
I have the same problem

**Comment by sophron** [comment]
Hi guys,

I don't understand the problem. You are supposed to see two networks: the original and the rogue one.

**Comment by AbdAlrzzaq** [comment]
why the vicitem si connect to the new access point if the orginal stil work

**Comment by sophron** [comment]
The victim will get deauthed from her access point. Depending on the client and your card's signal, it may automatically connect to the fake AP. This, plain curiosity or confusion are some common cases for the victim to connect to it, depending on the scenario.
