### ISSUE TITLE
URGENT FATAL ERROR

### ISSUE THREAD

**Issue by aelamine** [sophron/wifiphisher#69]
I got Jamming devices But no DHCP Leases or HTTP requests !
i wait for 60 minutes nothing worked! 
![e87998e0-9e09-11e4-894b-dfd3b748f50b](https://cloud.githubusercontent.com/assets/10442246/5888635/2ca2bc86-a3ff-11e4-90b3-bc4769449b72.jpg)

**Comment by sophron** [comment]
See #60.
