### ISSUE TITLE
How to  use wifiphisher with an ap connect on internet?

### ISSUE THREAD

**Issue by beast211** [sophron/wifiphisher#71]
I have read  on some web Pages and forum Thatcher wifiphisher  should  be more efficient  with an ap connected  on internet. I have tired  it But it does not  work. Before  opening  wifiphisher i have killed  network  manager , after  open  wifiphisher, And after  it  has  created  the  ap, i have  tried  to open  network manager  and  connected  ap  to internet  but it does not work because  ap  disappear.How Can i make ThiS?

**Comment by sophron** [comment]
Wifiphisher is not more efficient when your machine is connected to the Internet. I'm not sure where you read that.
