### ISSUE TITLE
Clint cannot connect with Ap (dhcp server not allocate ip for clinets )

### ISSUE THREAD

**Issue by kumarreshraj** [sophron/wifiphisher#73]
![screenshot from 2015-01-25 23 58 28](https://cloud.githubusercontent.com/assets/10698224/5892716/f53fdee6-a4c0-11e4-8c38-0b26e26cd73c.png)
![screenshot from 2015-01-25 23 58 28](https://cloud.githubusercontent.com/assets/10698224/5892722/17671674-a4c1-11e4-90db-b23ff23039cc.png)

no server response ...
clinet connected with fake AP but not fake page load on connection 

help me soon

**Comment by dalwa** [comment]
i have the same problem, i am using 2 Cards the first one is Alfa RTL8187L , and the second is TP-Link Atheros AR9271, i tried to switch between them and nothing change, still facing the same problem.

**Comment by sophron** [comment]
Hi,

There's already #29 for this.
