### ISSUE TITLE
Chrome block connection! Any solution?

### ISSUE THREAD

**Issue by testica** [sophron/wifiphisher#74]
Wifiphisher works me well, but after I connected to the fake AP, my google chrome stop me and notice me that the connection is dangerous and bla bla bla bla... so is impossible access to fake upgrade. how I can fixe it? How I can spoof that? Thanks.

**Comment by beast211** [comment]
Same  problem

**Comment by testica** [comment]
This happens because chrome detected the sniffer when wifiphisher wait for HTTP GET, otherwise, Firebox notice them about insecurity surfing web but the victim can go to fake upgrade.

**Comment by sophron** [comment]
Please see #35.

**Comment by pirance** [comment]
On Jan 28, 2015 9:30 AM, "testica" <notifications@github.com> wrote:
>
> Wifiphisher works me well, but after I connected to the fake AP, my
google chrome stop me and notice me that the connection is dangerous and
bla bla bla bla... so is impossible access to fake upgrade. how I can fixe
it? How I can spoof that? Thanks.
