### ISSUE TITLE
SIOCADDRT: No such device

### ISSUE THREAD

**Issue by gexus** [sophron/wifiphisher#75]
Hi, i've been trying to make this work on a vm with kali but no luck.. 
this is my iwconfig 

wlan1     IEEE 802.11bgn  ESSID:"xxxxxxx"  Nickname:"rtl_wifi"
          Mode:Managed  Frequency:2.462 GHz  Access Point: xx:xx:xx:xx:xx:xx   
          Bit Rate:150 Mb/s   Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:****-****-****-****-****-****-****-****   Security mode:open
          Power Management:off
          Link Quality=100/100  Signal level=100/100  Noise level=0/100
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

eth0      no wireless extensions.

lo        no wireless extensions.

wlan0     IEEE 802.11bgn  Mode:Monitor  Frequency:2.422 GHz  Tx-Power=30 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off

My wlan0 is an alfa awus036nha and wlan1 a belkin adapter which is connected to my ap.
I start wifiphisher and everything looks normal until I select the target AP and shows SIOCADDRT: No such device
It continues execution but no new AP is created.. 

[+] Ctrl-C at any time to copy an access point from below
num  ch   ESSID
---------------
1  - 1  - Speedy-995A19
2  - 1  - ESTUDIO-WiFi
3  - 1  - xtreme
4  - 1  - Vanderholl
5  - 1  - Mordelon
6  - 1  - Speedy-2CC07C
7  - 1  - paulinawifi1
8  - 1  - FamilySports
9  - 1  - FLopez
10 - 1  - Cisco49252
11 - 1  - SigloXX
12 - 1  - Cam24
13 - 4  - HP-Print-DD-Officejet Pro 8600
14 - 1  - IP-Print�	�;Officejet Pro 8600����
                                                $*0��
15 - 11 - Cisco14234
16 - 4  - HP-Print-DD-Officejet Pro �00
17 - 4  - HP-P�ML�+DD-�?LLcejetDt� 8600
18 - 4  - wifi-armado
19 - 4  - ap06
20 - 4  - HP-Print-DD-Of��C#y� ��9600
21 - 0  - HP-Print-DD-Officejet Pro 86��
22 - 6  - Limagui
23 - 6  - Lio2wi
24 - 6  - Personal EAP
25 - 6  - internet
26 - 6  - Personal WiFi
27 - 6  - Anfisanjusa
28 - 8  - ap15
29 - 9  - Tabatha
30 - 9  - Nosotros
31 - 9  - TabatHs
^C
[+] Choose the [num] of the AP you wish to copy: 31
SIOCADDRT: No such device
[*] Starting the fake access poi
ocaddrt: No such device[*] Starting the fake access point...

any idea what im doing wrong?
thanks

**Comment by sophron** [comment]
It looks like the wireless interfaces from the host machine (if any) were not bridged to the VM. The script  needs at least two wireless interfaces to work.

**Comment by gexus** [comment]
I have two wireless connected, wlan0 the alfa card and wlan1 the belkin.. 
When wifiphisher starts shows this:

root@kali:~/wifiphisher# ./wifiphisher.py 
[*] Starting HTTP server at port 8080
[*] Starting HTTPS server at port 443
[+] Networks discovered by wlan0: 5
[+] Starting monitor mode off wlan0
[*] Cleared leases, started DHCP, set up iptables

**Comment by awhitehatter** [comment]
I can confirm this issue as well, have the exact same setup and the exact same error.

**Comment by blackHatMonkey** [comment]
The issue should be solved now. If you still experience any issues after upgrading to the latest version feel free to open a new issue.
