### ISSUE TITLE
Fill wiki with useful information

### ISSUE THREAD

**Issue by sophron** [sophron/wifiphisher#77]
Github provides a wiki for hosting documentation. We can fill the wiki with information such as:
- Installation guides on various OS & distributions.
- HOWTOs.
- Code documentation.
- Extended information on the used techniques (Evil Twin for now).

Anyone that has used the tool can help on this. No development background needed.

**Comment by jalcine** [comment]
Maybe including a `requirements.txt` for installing dependencies :wink:
