### ISSUE TITLE
Wifiphisher card adapters

### ISSUE THREAD

**Issue by Matteo98** [sophron/wifiphisher#80]
I use my pc portatble, for this attack i use a tp-link wn722n and a Intel 5100(it is integreted in my computer)
The Intel 5100 is good? Or i shop another card adapters external?
Because Jamming devices work , i dont have problem for start wifiphisher , But dhcp and http not work , then he can not connect to my fake AP
Help me!
What i mistake?

**Comment by Matteo98** [comment]
And when i close with Ctrl+c i have errno 100

**Comment by Matteo98** [comment]
I have need of TWO (external) ADAPTERS?

**Comment by Gradius2** [comment]
Probably Intel (besides others) aren't supported.  I'm having same issues.

**Comment by Matteo98** [comment]
ok , thaks bro

**Comment by sophron** [comment]
Yes, you need two cards.
