### ISSUE TITLE
Cannot get DHCP leases

### ISSUE THREAD

**Issue by Gradius2** [sophron/wifiphisher#81]
Whatever I try to jamming anything, I never get "DHCP Leases".  I installed the so called isc, updated, etc, etc, and I'm still unable to see anything beyond "Jamming devices".

I'm using:

Ralink RT2870/3070 (rt2800usb) and Atheros AR9271 (ath9k).

I also tried a Intel 6300 (iwlwifi), but no joy too.

Please, help!

**Comment by sophron** [comment]
Please check #29.
