### ISSUE TITLE
Merge/Add Linset Tool (Coding) ... 

### ISSUE THREAD

**Issue by FurqanHanif** [sophron/wifiphisher#84]
i Recently Found a Tool LineSet , which is also based on Evil Twin Attack but it's Much more Stable (No error and Works Like a Charm) and Good. it also Do the Same like Starting fake AP and Jamming Devices etc. 
But the good things Of this Tool is it Only needed one Interface/Adapter , it don't give much errors (Like Dhcp error etc) it's too Much stable and It verifies the Victim Entered password that it's Correct or Not.
Now The Bad Things , Tool is In Spanish ( Many People Don't Know Spanish , and this is the reason i think this Tool is Not Popular) , Changing Fake Login Page Style is Too Difficult (Like in Wifiphisher simply made a Page in DW and give it's Path that's All , but in Lineset their is no Custom page option and it's Difficult too Change the Default Login Page , atleast For me , so if Some one figure out how to change the Style then Tell me too). it has Alot of different Options (use it and you'll see) .. 
So , i Think it would be nice if you change some of Things in Lineset (Like Custom Page and Language ) and Post it , That would be Great , alot of issues will be Resolved . Or add Coding into wifiphisher and make it More stable and Good . (i'll do this by my own but i 'm not much a programmer ). i Hope You'll Think About it.. :) (Link is Given Below)
https://github.com/vk496/linset

Thanks in Advance..

**Comment by sophron** [comment]
Hi,

Linset is written in Bash. Hence, it cannot be merged. It does have a lot of great features, but the project looks dead. It's been 8 months since it's last commit.

Thanks for posting it though. We could get some influence from it.

**Comment by FurqanHanif** [comment]
Hmm Ri8 , but the Project is Not Dead , the developer just not updating it on Github . Latest version of Linset is 0.14 (rev 38) . On Github , Version is 0.14 (rev 5)..
