### ISSUE TITLE
installation issue on Centos 7

### ISSUE THREAD

**Issue by REDASALEH** [sophron/wifiphisher#87]
[root@localhost wifiphisher-master]# python wifiphisher.py 
WARNING: No route found for IPv6 destination :: (no default route?)
[*] isc-dhcp-server not found in /usr/sbin/hostapd, install now? [y/n] y
sh: apt-get: command not found
[*] Starting HTTP server at port 8080
[*] Starting HTTPS server at port 443
Traceback (most recent call last):
  File "wifiphisher.py", line 901, in <module>
    reset_interfaces()
  File "wifiphisher.py", line 330, in reset_interfaces
    monitors = get_interfaces()["monitor"]
  File "wifiphisher.py", line 305, in get_interfaces
    proc = Popen(['iwconfig'], stdout=PIPE, stderr=DN)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[root@localhost wifiphisher-master]# 

any help ?

**Comment by HassenPy** [comment]
What's the output for ``iwconfig`` command?

**Comment by REDASALEH** [comment]
here is the output
[root@localhost network-scripts]# iwconfig 
enp38s0   no wireless extensions.

lo        no wireless extensions.

virbr0-nic  no wireless extensions.

virbr0    no wireless extensions.

wlo1      IEEE 802.11bgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=off   
          Retry  long limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
[root@localhost network-scripts]# 
-----------------------------------------------
-----------------------------------------------
** i found my hardware disabled (locked) , do think it is the main problem ?
-----------------------------------------------
-----------------------------------------------
[root@localhost network-scripts]# sudo rfkill list all
0: phy0: Wireless LAN
        Soft blocked: no
        Hard blocked: yes
1: hp-wifi: Wireless LAN
        Soft blocked: no
        Hard blocked: yes
2: hp-bluetooth: Bluetooth
        Soft blocked: no
        Hard blocked: yes
3: hci0: Bluetooth
        Soft blocked: no
        Hard blocked: no


---

**Comment by HassenPy** [comment]
Try to unblock them and try again.

**Comment by REDASALEH** [comment]
i reset my box BIOS setting so i get different results
[root@localhost wifiphisher-master]# sudo rfkill unblock all
[root@localhost wifiphisher-master]# sudo rfkill list all
0: hp-wifi: Wireless LAN
	Soft blocked: no
	Hard blocked: no
1: hp-bluetooth: Bluetooth
	Soft blocked: no
	Hard blocked: no
2: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: yes
4: hci0: Bluetooth
	Soft blocked: no
	Hard blocked: no

but when i re-run the wifiphisher again i got the following results

[root@localhost wifiphisher-master]# python wifiphisher.py 
WARNING: No route found for IPv6 destination :: (no default route?)
[*] isc-dhcp-server not found in /usr/sbin/hostapd, install now? [y/n] y
sh: apt-get: command not found
[*] Starting HTTP server at port 8080
[*] Starting HTTPS server at port 443
[ + ] Networks discovered by wlo1: 0
[ + ] Starting monitor mode off wlo1
SIOCSIFFLAGS: Operation not possible due to RF-kill
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "wifiphisher.py", line 953, in <module>
    sniffing(mon_iface, targeting_cb)
  File "wifiphisher.py", line 423, in sniffing
    sniff(iface=interface, prn=cb, store=0)
  File "/usr/lib/python2.7/site-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/lib/python2.7/site-packages/scapy/arch/linux.py", line 485, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
socket.error: [Errno 100] Network is down
????
any idea

**Comment by HassenPy** [comment]
It has something to do with a disabled interface, check ``ifconfig

**Comment by REDASALEH** [comment]
[ + ] Ctrl-C at any time to copy an access point from below
num  ch   ESSID
---------------
1  - 1  - Karim
2  - 6  - Max1
3  - 6  - ADSL_2014
^C
[ + ] Choose the [num] of the AP you wish to copy: 3
SIOCADDRT: Network is unreachable
[*] Starting the fake access point...
[3;J

[*] ADSL_2014 set up on channel 6 via wlo1 on False
[*] Monitor mode: wlo1 - [My Mac address here]
[3;J

Jamming devices: 

DHCP Leases: 

HTTP requests: 


[3;J
..... and it keep that way does it working fine or not ? or there is something wrong ?

**Comment by REDASALEH** [comment]
please respond i can not crack any AP ? any steps how to run the program

**Comment by HassenPy** [comment]
The script behaves like that if you don't have the hardware requirements.

**Comment by sophron** [comment]
Hi @REDASALEH,

Please open a different ticket describing your issue.
