### ISSUE TITLE
chipset RTL8187

### ISSUE THREAD

**Issue by osabosabl** [sophron/wifiphisher#89]
Since i see this chipset is not working on this(I have problem when Fake AP gets UP) i can't connect to him.
So, for having high range for this, what AP you advice?
Docooler Mini USB Wifi Adapter 150Mbps Atheros AR9271 Chip with 5dBi Antenna
I see this one is advices, but is 5dBi enough?
Can you suggest some stronger?

**Comment by sophron** [comment]
There's already issue #96 for this.
