### ISSUE TITLE
Erro   File "./wifiphisher.py", line 960, in <module>

### ISSUE THREAD

**Issue by ohyeah521** [sophron/wifiphisher#90]
[ + ] Ctrl-C at any time to copy an access point from below
num  ch   ESSID
---------------
1  - 6  - yutianmeishushe
2  - 6  - 123
3  - 6  - Tenda_35D820
^C
[ + ] Choose the [num] of the AP you wish to copy: 1
SIOCADDRT: Network is unreachable
[*] Starting the fake access point...
Traceback (most recent call last):
  File "./wifiphisher.py", line 960, in <module>
    start_ap(ap_iface, channel, essid, args)
  File "./wifiphisher.py", line 494, in start_ap
    Popen(['hostapd', '/tmp/hostapd.conf'], stdout=DN, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
root@kali:~/wifiphisher#

**Comment by industrias** [comment]
Tengo el mismo problema, por favor, alguien sabe la solución????
Gracias.

**Comment by industrias** [comment]
Tengo el mismo problema, a mi me sale esto, por favor, ¿alguien sabe cómo solucionarlo?
Muchas Gracias.

[ + ] Choose the [num] of the AP you wish to copy: 3
SIOCADDRT: Network is unreachable
[*] Starting the fake access point...
Traceback (most recent call last):
File "./wifiphisher.py", line 960, in <module>
start_ap(ap_iface, channel, essid, args)
File "./wifiphisher.py", line 494, in start_ap
Popen(['hostapd', '/tmp/hostapd.conf'], stdout=DN, stderr=DN)
File "/usr/lib/python2.7/subprocess.py", line 679, in_init_
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
root@kali:~/Desktop/wifiphisher#

**Comment by alib33** [comment]
please help ! got the same probleme

**Comment by frafrichile** [comment]
Seria mejor si posteas que tipo de tarjeta usas.  tienes una , tienes dos?

it would be useful if you post which cards are you using for this . You have one card? two cards? are you running kali or linux on a virtual box ? more information please

**Comment by alib33** [comment]
Hi !   Im running kali   on a real laptop  ! i have two card   of RTL8187
Thnx

2015-03-02 12:10 GMT-05:00 frafrichile <notifications@github.com>:

**Comment by alib33** [comment]
please i  really need a solution

**Comment by sophron** [comment]
Please check #37.

**Comment by industrias** [comment]
Tengo una: una BROADCOM 4313 802.11b/g/n

Gracias.

**Comment by sandman6578** [comment]
@alib33  rtl8187 i not able to go in AP-Mode.
Buy an atheros chipset based wifi stick pcie card or whatever and it will work
