### ISSUE TITLE
WARNING: No route found for IPv6 destination :: (no default route?)

### ISSUE THREAD

**Issue by frafrichile** [sophron/wifiphisher#92]
Hello , Thanks for sharing this amazing tool .
I am having the following problem, when I try to run the script it gives me the error 
WARNING: No route found for IPv6 destination :: (no default route?)
but then it keeps going. Is this affecting the script? or should I ignore.

**Comment by sandman6578** [comment]
Hey 
wanna push this became the same error

**Comment by ZxPwd** [comment]
Yes I also get this Error. Can anybody help ?

**Comment by cleanfile** [comment]
it means your interface cannot inject

**Comment by zerocolTHS** [comment]
I don't agree @cleanfile  i was using the awus036h and a awus036nh which are both capable of injection.
I only tried this script few days ago an that's the same error i get.

**Comment by frafrichile** [comment]
I have the awus036h and the awus036nh as well.

**Comment by casperass** [comment]
I have an ALFA AWUS036NHA. Same warning.

**Comment by sandman6578** [comment]
I also have the awus036h

**Comment by HassenPy** [comment]
You can ignore the error, it doesn't affect the behavior of the script, see #98 for fix.

**Comment by abrahamdecode** [comment]
same problem i also have the alfa awus036h, i tried with a tp link and kind of do the job, just when i connect both of them i can make it go trough, but it doesnt attak , just audit the networks

**Comment by blackHatMonkey** [comment]
Hi @abrahamdecode I will test and see if I am able to reproduce the bug.

**Comment by blackHatMonkey** [comment]
@abrahamdecode 
Just tested the latest version and I can see deauthentication packets in the air. Do you see any MAC addresses in the `jamming clients` section?
