### ISSUE TITLE
Which Wifi Network Adapter is required ( MUST)

### ISSUE THREAD

**Issue by Hitesh96** [sophron/wifiphisher#96]
I want to know which wifi adaptor is must for using this tool. And we need two it is Must or not If yes PLease suggest me :) 
Thanks

**Comment by sandman6578** [comment]
search for chipsets 3070 ralink because alfa awus036h is not AP-Mode possible

**Comment by casperass** [comment]
I have Alfa Awus036NHA, Atheros 9271 chipset. It works for me.

**Comment by sandman6578** [comment]
But you use the atheros for Accesspoint and the Alfa for the jammer right

**Comment by casperass** [comment]
sandman6578, I don't get what you mean.

**Comment by casperass** [comment]
sandman6578, How can we adjust it? I didn't know that. My internal wifi card's chipset is an Atheroes as well. AR9285. However, I don't wanna use it as the AP. It's so weak. What should I do?

**Comment by sandman6578** [comment]
Read the README and you know it

**Comment by sandman6578** [comment]
Why everyone use this script without reading the manual sry but thats not understandable for me

**Comment by sandman6578** [comment]
The alfa is not CANNOT be an access point because it dint support the AP-Mode

**Comment by sandman6578** [comment]
Sry without "is not" at the begining I'm german guy not english xD

**Comment by casperass** [comment]
Thanks sandman :D

**Comment by sandman6578** [comment]
Does it work??

**Comment by casperass** [comment]
No thanks for information :) It was already using atheros as AP, and the alfa for jamming. I was trying to use the internet at the same time from atheros. May be that's why I got those problems. I will try it properly and inform you.

**Comment by Hitesh96** [comment]
Thank You Geeks :)

**Comment by catman85** [comment]
@sophron  Can you PLEASE tell us what interfaces you recommend?

**Comment by starfighter73** [comment]
I use TPLINK 722. It works fine!

**Comment by sophron** [comment]
Hi, please check the <a href="https://github.com/sophron/wifiphisher/wiki/Frequently-Asked-Questions-(FAQ)">FAQ</a> for an answer on this.
