### ISSUE TITLE
When victim enters password and clicks submit, page says 'index.html' not found; Password is not retrieved.

### ISSUE THREAD

**Issue by lifeofpentester** [sophron/wifiphisher#97]
Nice tool you have coded here. Kudos! I plan to mention the tool in a paper I am writing for a popular security journal. However, I have been facing an issue on Kali Linux.

I have two cards: wlan1 and wlan0 (wlan1 is the external adapter). Everything works fine until the phishing page is served. It starts the monitor mode on wlan1 and creates a duplicate open AP. The victim is able to connect to this fake AP and is given an IP address. Victim goes to www.google.com and is served the phishing page (minimal). 

Now, the tool fails at this point.

When the victim enters the password and clicks 'submit', the page fails saying 'google.com/index.html' not found. I have even tried accessing 127.0.0.1:8080 directly from the attacking machine. I get the phishing page, and when I click submit, the page fails saying 'index.html' not found. And of course, the tool does not display a password in the terminal like it is supposed to.

Please check the code where you specify which 'action' to take when victim clicks 'submit' on the phishing page.

**Comment by HassenPy** [comment]
can you post the attacker's console output when you click 'submit' ?

**Comment by lifeofpentester** [comment]
When the victim enters the password and hits 'submit', the page says 'google.com/index.html' in the URL bar and 'No data received'. As if the page index.html does not exist.

On the attacker's console, I have this:

DHCP Leases: 
1426400333 d0:XX:3f:XX:X4:XX 10.0.0.7 android-2baf1a35***f0b5e *




HTTP requests: 
[*] GET 10.0.0.7

That's all. This keeps looping. So, the attacker is told that the client has requested the page, but that's it. No password. I loaded an older version of this tool called 'WiFiPhisher-master' and that seems to be working. So, someone has updated the code wrong recently, because the recent copy obtained from github does not work Please check the issue.

**Comment by casperass** [comment]
Same problem here, it says "index.html' not found"

Can you give the url of the old version?

**Comment by lifeofpentester** [comment]
Original version uploaded!

Since I have been receiving emails from many users about the same issue, asking for a copy of the original version of the tool that is working, I have uploaded that original version on Github at this location:

https://github.com/lifeofpentester/wifiphisher-master

(This version works!)

Author and contributors, 
Let me say once again that someone modified the code wrong recently which has debilitated the functionality of the tool. Please check the code pertaining to what action is taken once a phished user hits 'submit'.

**Comment by HassenPy** [comment]
Looking into it.

**Comment by casperass** [comment]
Thanks lifeofpenteste. But I have an issue

 https://github.com/lifeofpentester/wifiphisher-master/issues/1

**Comment by lifeofpentester** [comment]
@casperass I have updated the code to include the 'connection_reset' pages and load it by default.

**Comment by sophron** [comment]
@lifeofpentester Thanks for reporting this. 

Last night i pushed a fix. Can you update to the latest revision and check it again?

**Comment by sophron** [comment]
@lifeofpentester Thanks for reporting this.

I pushed a fix last night. The latest revision should now work properly. Can you please check it?

**Comment by lifeofpentester** [comment]
@sophron Just tested the tool again, works fine now. Thank you for the fix!

**Comment by casperass** [comment]
It works great now. Thanks!
